- etc/uams/uams_dhx2_pam.c
- etc/uams/uams_dhx2_passwd.c
- include/atalk/uam.h
This removes the overzealous check for the exact libgcrypt version that netatalk was linked with.
At the same time, add scaffolding for future libgcrypt minimum version validation.
> [3.2] uams: Disable incorrect libgcrypt library version validation

- etc/uams/uams_dhx2_pam.c
- etc/uams/uams_dhx2_passwd.c
- include/atalk/uam.h
This removes the overzealous check for the exact libgcrypt version that netatalk was linked with.
At the same time, add scaffolding for future libgcrypt minimum version validation.
> [2.4] uams: Disable incorrect libgcrypt library version validation

- distrib/initscripts/netbsd.a2boot.in
- distrib/initscripts/netbsd.atalkd.in
- distrib/initscripts/netbsd.netatalk.in
- distrib/initscripts/netbsd.papd.in
- distrib/initscripts/netbsd.timelord.in
The superfluous pid definition prevents you from stopping the daemon with the NetBSD init system.
Also cleans up some redundant comments.
> initscripts: Don't define nonexistent pid file for NetBSD scripts

- distrib/initscripts/rc.a2boot.netbsd.tmpl
- distrib/initscripts/rc.timelord.netbsd.tmpl
The superfluous pid definition prevents you from stopping the daemon with the NetBSD init system.
> [2.4] initscripts: Don't define nonexistent pid file for NetBSD scripts

- etc/afpd/fork.c
In some cases, we may read memory that we shouldn't have access to. Revise the EOF check to fix this.
> Fix critical read error in fork.c

- contrib/macipgw/macip.c
- contrib/macipgw/main.c
- contrib/macipgw/nbp_lkup_async.c
- contrib/macipgw/tunnel_bsd.c
- contrib/macipgw/tunnel_linux.c
- etc/papd/session.c
- meson_config.h
<sys/errno.h> is an alias for <errno.h> on all supported OSes
Also, removes obsoleted capability flags in config.h
> errno.h should always be available

- bin/aecho/meson.build
- bin/getzones/meson.build
- bin/nbp/meson.build
- bin/pap/meson.build
- contrib/a2boot/meson.build
- contrib/timelord/meson.build
Copy paste mistake while porting the build scripts from 2.4 to 4.0.
> meson: Don't always build AppleTalk utils with RPATH

- doc/manual/meson.build
A missing build directive left the macipgw html page out of the generated manual.
> docs: Build the macipgw html manual page

- .github/workflows/build.yml
- doc/meson.build
- meson.build
The build system should still continue when XSL dependencies are missing.
In this case, the troff man pages and html pages aren't generated, but the rest of the netatalk build will succeed.
> meson: Missing xsltproc and docbook-xsl treated as non-fatal error

- Dockerfile
Previously, the netatalk build was with 0 optimization and debug symbols enabled.
> docker: Build with optimizations and without debug symbols

- meson.build
The Webmin module is arguably not a feature of Netatalk proper, but an external add-on component. Displaying it as such in the setup summary to avoid misunderstandings.
> meson: In summary, list Webmin module under a new Add-ons section

- .github/workflows/build.yml
curl is available everywhere. Removes the wget dependency.
Also, clarify directory traversal for human readers (in the CI runner the current dir gets reset every step.)
In addition to the GitHub CI workflow, these changes will be reflected in the compile appendix in the html manual.
> GitHub CI: Use curl on UnicodeData.txt and fix directory traversal

- distrib/initscripts/meson.build
The load/unload launchctl subcommands are flagged as Legacy in macOS Sequoia. (Ref: macOS man page)
> initscripts: Use launchctl bootstrap and enable directives for installing on macOS

- etc/afpd/acls.c
- etc/afpd/afp_dsi.c
- etc/afpd/appl.c
- etc/afpd/desktop.c
- etc/afpd/desktop.h
- etc/afpd/directory.c
- etc/afpd/directory.h
- etc/afpd/enumerate.c
- etc/afpd/file.c
- etc/afpd/file.h
- etc/afpd/filedir.c
- etc/afpd/unix.c
- libatalk/acl/unix.c
uint8_t is a POSIX standard while u_char is a BSD-ism.
> Change u_char data types to the portable uint8_t

- etc/netatalk/meson.build
- meson.build
As Avahi includes `dns_sd.h`, currently build will always detect mDNS as Zeroconf provider. Patch changes the logic to first detect and use Avahi and if not found fallback to mDNS.
> meson: Detect native Avahi before mDNS

- distrib/initscripts/systemd.a2boot.service.in
- distrib/initscripts/systemd.macipgw.service.in
- distrib/initscripts/systemd.papd.service.in
- distrib/initscripts/systemd.timelord.service.in
Also is redundant to After and Requires in regular systemd use. Enabling/disabling services is normally handled by wrappers. Also has been shown to cause side effects in a particular wrapper (debhelper).
> initscripts: Remove the redundant systemd Also directive

- .github/workflows/build.yml
- doc/generate_compile_docs.py
In the compile appendix, explain that you need to clone the source code before proceeding with the compile instructions.
Also, break down the binary verbose start and service start steps in CI jobs.
> docs: Flesh out the compile appendix and break down start steps in GitHub CI

- bin/ad/ad_util.c
Check was failing if the `ea = ad` option was set.
> [3.x] Fix volume check for "ad" tools.

- bin/ad/ad_util.c
Check was failing if the `ea = ad` option was set.
> [2.x] Fix volume check for "ad" tools.

- meson.build
- meson_options.txt
Rewrite of Berkley DB detection in meson aimed to handle issues when multiple versions of library are installed on the system (such as #1604):
* Added `with-bdb-version` option that allows to specify particular Berkley DB version to link against
* Leave option to link against lib file that does not have version in its name as a last resort only (as it could lead to mismatch between header and lib versions)
* Check against minimum supported library version did not work previously
* Extend and rearrange list of potential `db` installation subdirectories for searching from older to newer version
> meson: Rewrite Berkley DB detection

- doc/ja/manpages/man5/afp.conf.5.xml
- doc/ja/manual/upgrade.xml
- doc/manpages/man5/afp.conf.5.xml
- doc/manual/upgrade.xml
The Upgrade chapter has some misleading information about extmap.conf and the AppleTalk config files.
> docs: Improve upgrade chapter and add usage note for afp listen/ifs

- .github/workflows/build.yml
We keep the db, gcc, and openldap-client packages versions, to avoid ambiguous versioning.
> GitHub CI: Bump to OpenBSD 7.6 vmactions runner

- etc/afpd/afp_asp.c
- include/atalk/globals.h
* Completely remove `afp_options.authprintdir` in `include/atalk/globals.h`
* Remove `afp_authprint_remove` from `etc/afpd/afp_asp.c`
> AFP over ASP: Cleanup unused code

- libatalk/util/netatalk_conf.c
- meson.build
- meson_config.h
- test/afpd/meson.build
- test/afpd/test.c
When enabling tests with `-Dwith-tests=true`, `last` volumes are made writable.
Enabling and touching up all write tests in the afpd test suite.
> Make last CNID backend writable when running tests

- .github/workflows/build.yml
Compile the tests on all platforms. Additionally, execute the tests on FreeBSD and OmniOS (where they now pass, which they didn't before.)
Only on DragonflyBSD and OpenBSD do we not execute the tests because of flakiness.
> GitHub CI: Enable tests for all OSes

- meson.build
In case unable to grep Berkeley DB version from header file, show warning and continue to next header file location
> meson: More robust Berkeley DB version detection

- INSTALL.md
- doc/manpages/man5/afp.conf.5.xml
- doc/manual/configuration.xml
- doc/manual/install.xml
- etc/afpd/meson.build
- etc/netatalk/netatalk.c
- etc/spotlight/meson.build
- meson.build
- meson_config.h
- test/afpd/meson.build
As of version 3.8 Tracker has [split into TinySPARQL and LocalSearch](https://blogs.gnome.org/carlosg/2024/07/14/goodbye-tracker-hello-tinysparql-and-localsearch/) with command line tool renamed to `localsearch`.
> Spotlight: Support TinySPARQL/LocalSearch

- test/afpd/meson.build
- test/afpd/test.c
AFP version shouldn't make a difference at this test level, but bumping to the latest version for good measure.
> test: Bump tested protocol version to AFP 3.4

- .github/workflows/build.yml
It seems heimdal is broken in NetBSD right now, so disabling the krbV UAM for the time being.
> GitHub CI: Bump NetBSD vmactions runner, skip krbV UAM

- .github/workflows/build.yml
The apt packages env variable was polluting all the other jobs. And since the static analysis job has an optimized package list now, there is little overhead to maintaining apt package lists for Debian and Ubuntu.
Also rename the test steps for clarity
> GitHub CI: Define Debian and Ubuntu packages individually

- etc/papd/main.c
As per "Inside AppleTalk", the PAPStatus string can be a max of 255 characters, not 254 characters. The packed struct already accommodates the prefixed byte (`buf->buf_len`) containing the string length. This should silence the compiler error in papd encountered in: #1576
> Fix papd PAPStatus string copy

- test/testsuite/FPByteRangeLock.c
- test/testsuite/FPByteRangeLockExt.c
- test/testsuite/FPDisconnectOldSession.c
- test/testsuite/FPGetACL.c
- test/testsuite/FPSetDirParms.c
- test/testsuite/FPSetFileDirParms.c
- test/testsuite/T2_spectest.c
- test/testsuite/afparg.c
- test/testsuite/fail_spectest.c
- test/testsuite/logintest.c
- test/testsuite/rotest.c
- test/testsuite/sleeptest.c
- test/testsuite/spectest.c
The extended AFP login method is broken, so use the simple one even for AFP3 tests for now.
Also, throw error when AFP login fails, and disable broken AFP3 tests.
> testsuite: Workaround for enabling AFP 3.x tests

- test/testsuite/afp_ls.c
- test/testsuite/afpcli.c
- test/testsuite/afpclient.h
- test/testsuite/afpcmd.c
- test/testsuite/encoding_test.c
- test/testsuite/lantest.c
- test/testsuite/test.h
All test settings are now global, declared in test.h and defined in afpcli.c. They can be overridden by individual test module optargs.
Also cleans up obsoleted code.
> testsuite: Make all test settings global, remove dead code

- .github/workflows/build.yml
- test/testsuite/FPCopyFile.c
- test/testsuite/T2_spectest.c
- test/testsuite/afpcli.c
- test/testsuite/afphelper.c
- test/testsuite/meson.build
- test/testsuite/sleeptest.c
- test/testsuite/spectest.c
- test/testsuite/spectest.sh
- Clean up and shore up validation in spectest.sh
- Allow for running without the local-only T2_spectest
- Make colorized terminal output an opt-in option in spectest, to avoid escape chars when logging to file
- meson test fails now when spectest.conf is missing
- Only build testsuite in Static Analysis CI job to avoid test failures elsewhere
- Disable a single spectest TC that is flaky when testing a remote AFP server
> testsuite: Touch up spectest suite for remote execution

- Dockerfile
A few Dockerfile convention fixes flagged by VSCode.
I deliberately kept "redundant" RUN commands for more atomic layer cache.
> docker: Touch up syntax of Dockerfile

- contrib/shell_utils/docker-entrypoint.sh
Aligns the behavior of the Docker container with the other init systems.
> docker: Register the conventional NBP entities when starting up

- distrib/initscripts/systemd.atalkd.service.in
As concluded elsewhere, nbpunrgstr is redundant when atalkd is already shutting down. The NBP registrations are automatically released.
> initscripts: Remove redundant nbpunrgstr cleanup in atalkd systemd config

- test/testsuite/spectest.sh
The initial run of the spectest.sh script generates a config file that needs to be edited before running the whole suite. Before we treated this as a failed test to call attention this this fact. However this blocked CI jobs when tests and testsuite were both enabled and tests were ran.
> testsuite: Don't treat initial spectest.sh run as a failure

- etc/afpd/acls.c
- etc/afpd/catsearch.c
- etc/afpd/file.c
- etc/afpd/fork.c
- include/atalk/adouble.h
- libatalk/adouble/ad_lock.c
- libatalk/adouble/ad_open.c
- libatalk/adouble/ad_write.c
- libatalk/dsi/dsi_tcp.c
- libatalk/util/netatalk_conf.c
- libatalk/vfs/vfs.c
- test/testsuite/FPByteRangeLockExt.c
- test/testsuite/FPGetForkParms.c
- test/testsuite/T2_FPOpenFork.c
- test/testsuite/adoublehelper.c
- test/testsuite/afpcli.c
- test/testsuite/afpcli_asp.c
- test/testsuite/temp.c
The "ressource fork" misspelling is proliferating in this code base. Let's fix it in one go.
> Fix the spelling of resource forks

- test/testsuite/FPAddIcon.c
- test/testsuite/FPByteRangeLockExt.c
There were a few cases where a failing test caused the entire spectest execution to halt, or get memory corruption.
> testsuite: Fail tests early to keep execution alive

- test/testsuite/README
- test/testsuite/meson.build
This installs the spectest, tier 2 spectest, speedtest, and lantest binaries. The binaries have been renamed with an `afp_` prefix to distinguish them from other similarly named binaries on a system.
The other test binaries are still buggy, so keeping them off the install manifest for now.
Note that the binaries are only built when `with-testsuite=true` is enabled, so this won't affect normal builds.
> testsuite: Install the stabilized test binaries

- etc/afpd/auth.c
- etc/afpd/status.c
- include/atalk/globals.h
Early AppleTalk clients struggle with FPGetSrvrInfo packets that have a payload larger then 512 bytes. In many cases they claim that they received no response from the server. In some cases they may even crash.
To resolve this, craft a response just for AppleTalk clients without most of the AFP3.x only options (UTF8 server name, Directory Name, etc.). In addition, unless a custom icon is sent, the server will not send an icon image to AppleTalk clients by default.
Fixes: #1661
> Limit FPGetSrvrInfo packet for AppleTalk clients

- libatalk/dsi/dsi_stream.c
Under certain conditions, logging on and then immediately logging off of an AFP server may generate the following error: `dsi_stream_read: len:0, unexpected EOF`
This state is harmless since the user has already logged off and closed the shared volume. So don't log the error by checking if we are indeed logged off.
Fixes #1631
> Fix EOF error reporting in dsi_stream_read()

- libatalk/util/netatalk_conf.c
This fixes a regression introduced in commit: https://github.com/Netatalk/netatalk/commit/f4ae924843e376e96ea46de5e23c176dbe959682
The file containing the volume UUID should be opened read-only because in some contexts, the user does not have read-write privileges (ex: running the `ad` tool suite).
> Fix regression in get_vol_uuid()

- .github/workflows/containers.yml
- Dockerfile.testsuite
- contrib/shell_utils/docker-entrypoint.sh
- test/testsuite/T2_FPMoveAndRename.c
Create a Docker container that builds both netatalk and the testsuite. While the baseline spectest test suite can be run remotely, the tier 2 spectest requires access to the local filesystem, so I opted to have the netatalk instance under test in the same container as the testsuite. AFP requests still done over port 548 but on a local socket.
Additionally, create a new GitHub actions workflow that builds the Docker containers, publishes them to the GitHub container store, and then runs the two containerized spectest suites.
> docker: Containerized testsuite and build containers in CI workflow

- meson.build
In case `-Dwith-pam-config-path` was not explicitly specified, even if actual `pam.d` directory was located on the system, `{prefix}/etc/pam.d` was used instead to install `netatalk.pamd`
> meson: Fix PAM config directory detection

- meson.build
Add the quotations to the indexer command only at the time of substitution, to give a consistent look of the Meson setup summary.
> meson: Consistent formatting in setup summary

- test/testsuite/FPByteRangeLock.c
- test/testsuite/FPOpenFork.c
- test/testsuite/speedtest.c
- test/testsuite/test.h
test151 opens up thousands of forks which causes instability for other tests. Uncomment it but allow it only to be run by itself (i.e. `-f test151`)
Also, refactor the `Test` variable (which controls the -f option) to be global.
> testsuite: Restore test151 but only when run by itself

- libatalk/util/netatalk_conf.c
We need the file to be in  read-write mode after all. The function later writes to the file to append data.
> Fix regression in get_vol_uuid() 2nd attempt

- .github/workflows/containers.yml
Only the mother repo can generate tokens with the privileges to push to the container registry.
> GitHub CI: Skip container builds when code originates from a fork

- test/testsuite/meson.build
This enables the `-f test000` option to run individual tests (at least on Debian Linux.)
> testsuite: Link test executables with -rdynamic to allow sole test case runs

- .github/workflows/build.yml
- .github/workflows/containers.yml
Sometimes the vmactions jobs in particular can stall badly and run for an hour or longer before failing by themselves. Setting a hard timeout prevents this.
> GitHub CI: Define hard timeouts for workflow actions

- libatalk/unicode/make-casetable.pl
- libatalk/unicode/make-precompose.h.pl
- meson.build
The problem that's being solved here, is that an incorrect search path could lead to silently failing Perl scripts and therefore broken Unicode sources.
Two major changes here:
- Add error handling when `open()` fails in the Perl scripts
- Normalize UnicodeData.txt search paths to absolute paths in the Meson detection routine
> Shore up Unicode char table script error handling and detection

- .github/workflows/build.yml
- etc/afpd/desktop.c
- etc/afpd/file.c
- etc/afpd/messages.c
- etc/uams/uams_dhx2_pam.c
- libatalk/atp/atp_bufs.c
- libatalk/atp/atp_close.c
- libatalk/atp/atp_rreq.c
- libatalk/atp/atp_rsel.c
- libatalk/atp/atp_sreq.c
- libatalk/atp/atp_sresp.c
- libatalk/unicode/charcnv.c
- libatalk/util/bprint.c
- meson.build
- Enable the `EBUG` flag when build type is debug
- Print the build type in Meson summary
- Remove remnants of the obsoleted `DEBUG` flag
- Fix static analysis bugs
> Clean up debug flags and code

- .github/workflows/build.yml
We have a good idea that the AppleTalk code is cross-platform friendly now, so let's only build it for OSes that actually ship an AppleTalk kernel module.
> GitHub CI: Build with appletalk only on OSes that support it

- libatalk/adouble/ad_open.c
Fixes a regression introduced in this commit: https://github.com/Netatalk/netatalk/commit/8e8430ea012c57e2285b04e3b2567b75d7d1a38f
Fixes these two bug reports over on SourceForge:
https://sourceforge.net/p/netatalk/bugs/580/
https://sourceforge.net/p/netatalk/bugs/600/
This bug only affects the `ea` AppleDouble backend when using separate files for resource fork storage. Platforms like Solaris that store resource forks in EAs are not affected and the `v2` backend uses a different code path.
When creating new files to a Netatalk volume, the FinderInfo data for that file was being reinitialized to the default after a resource fork was added. In most cases this did not cause an issue as the client usually (re)writes the FinderInfo data in a FPSetFileParams call after the fork copy is …
> Fix loss of FinderInfo on resource fork creation with AppleDouble EA.

- .github/workflows/containers.yml
- contrib/shell_utils/docker-entrypoint.sh
- test/testsuite/afp_ls.c
- test/testsuite/afparg.c
- test/testsuite/encoding_test.c
- test/testsuite/lantest.c
- test/testsuite/logintest.c
- test/testsuite/spectest.c
- test/testsuite/speedtest.c
- Standardize test app options as much as possible
- Order options alphabetically for easier maintenance
- Fix a bunch of bugs in some of the tests
- Add afp_encodingtest CI job
> testsuite: Clean up test executable options and helptext

- contrib/shell_utils/docker-entrypoint.sh
The CUPS daemon is no longer starting up by itself, so adding a step to the Docker entrypoint script.
> docker: Explicitly launch the cupsd daemon on startup

- doc/ja/manpages/man1/afptest.1.xml
- doc/ja/manpages/man1/meson.build
- doc/ja/manual/manual.xml.in
- doc/ja/manual/meson.build
- doc/manpages/man1/afptest.1
- doc/manpages/man1/afptest.1.xml
- doc/manpages/man1/meson.build
- doc/manual/manual.xml.in
- doc/manual/meson.build
A single `afptest.1` man page for all six test tools.
> docs: Create manual page for afptest tools

- .github/workflows/containers.yml
- test/testsuite/FPDisconnectOldSession.c
- test/testsuite/FPRead.c
- test/testsuite/afparg.c
- test/testsuite/afpcmd.c
- test/testsuite/afphelper.c
- test/testsuite/lantest.c
- test/testsuite/logintest.c
- test/testsuite/spectest.c
- test/testsuite/speedtest.c
Since the spectest suite has been stabilized now, let's have Not Tested trigger test run failures again. The meaning of Not Tested in the context of this test suite is that a setup step failed unexpectedly, blocking the execution of the test. Such an outcome should be escalated. In comparison, The Skipped status means that a test is deliberately disabled.
> testsuite: Treat the Not Tested test result as a failure (again)

- contrib/shell_utils/docker-entrypoint.sh
- test/testsuite/FPMapID.c
- test/testsuite/T2_FPMoveAndRename.c
- test/testsuite/T2_FPOpenFork.c.in
MUSL system calls (Alpine) result in files/dirs with no write permissions for the group, unlike glibc (Debian).
> testsuite: Workarounds for MUSL system calls default permissions

- .github/workflows/containers.yml
- contrib/shell_utils/docker-entrypoint.sh
- doc/ja/manpages/man1/afptest.1.xml
- doc/manpages/man1/afptest.1.xml
- test/testsuite/README
- test/testsuite/encoding_test.c
- test/testsuite/meson.build
- test/testsuite/spectest.c
The "western" encoding test has been refactored to use Unicode characters instead of defunct Extended ASCII, and then merged into the spectest as an Encoding testset.
> testsuite: Merge encoding test into spectest

- doc/ja/manpages/man1/afptest.1.xml
- doc/manpages/man1/afptest.1.xml
- test/testsuite/afparg.c
- test/testsuite/afpcli.c
- test/testsuite/afphelper.c
- test/testsuite/logintest.c
- test/testsuite/specs.h
- test/testsuite/spectest.c
- test/testsuite/speedtest.c
- test/testsuite/test.h
Have every test tool default to AFP 3.4 instead of 2.1
> testsuite: Use AFP 3.4 protocol by default in all tools

- meson.build
Fix build fail with `-Dwith-spotlight=false` due to `sparql` being undefined, as suggested by @APCCV, plus logic simplification
> meson: Fix build fail with -Dwith-spotlight=false

- doc/ja/manpages/man1/afptest.1.xml
- doc/manpages/man1/afptest.1.xml
- test/testsuite/FPAddAPPL.c
- test/testsuite/FPGetFileDirParms.c
- test/testsuite/afpcli.c
- test/testsuite/afphelper.c
- test/testsuite/specs.h
- test/testsuite/spectest.c
- test/testsuite/test.h
- Bring back the -x option to use for tests that fail without special environment setup.
- Fix a typo in spectest default AFP version
- Disable test301 again. It's broken when run with a single user.
> testsuite: Use Exclude option for special case tests

- CONTRIBUTORS
Code contributors for the period between the v2.0 and v4.0 releases, roughly 2005-2024. The source of this information is the Netatalk git commit history.
I have tried to be mindful and selective about recording personal information here. While open source projects traditionally have been very, err, _open_ about sharing the names and email addresses of code contributors, today the culture has shifted and many individuals prefer to keep their email addresses private, and sometimes also strictly use pseudonyms online. I believe it is important to respect the will of such individuals.
Criteria for using someone's real name:
- The name is on their public GitHub/GitLab profile
Criteria for recording someone's email address is one of the below:
- The email address is in a copyright blurb in the …
> Update CONTRIBUTORS for versions 2.0~4.0

- doc/manpages/man1/meson.build
The afp_encodingtest tool itself was removed previously.
> docs: Remove afp_encodingtest.1 man page alias

- .github/workflows/build.yml
libgcrypt is an alias for libgcrypt20. Better use the actual name.
> GitHub CI: Use libgcrypt20 packages for Debian/Ubuntu

- doc/generate_compile_docs.py
- doc/ja/manual/compile.xml
- doc/manual/compile.xml
By popular request, this strips out all of the newline escape sequences in shell commands from the generated Compile appendix.
Arguably makes it easier to copy paste and modify.
> docs: Strip out linebreak escapes in Compile appendix

- test/testsuite/FPGetFileDirParms.c
This oversight made it so that even when using the Exclude flag, the excluded tests were not skipped but ran to conclusion.
> testsuite: Make sure to exit test early with the Exclude flag

- contrib/macipgw/main.c
Adapted from patch by Jason King
> macipgw: Fix argument handling in main() for aarch64 compatibility

- test/testsuite/FPSetFileDirParms.c
This is to prevent test flakiness when file operations are slow (IBM s390x)
> testsuite: Longer sleep time after file operation in test358

- etc/atalkd/nbp.c
In Linux 6.9+, NBP Reply packets can appear to come from the loopback interface, which has an address of `0.0`. This address is invalid on Phase 2 AppleTalk networks and should never appear. One minor benefit is less traffic is generated when doing NBP Lookups. Fixes #1731 without breaking anything additional.
> atalkd: Don't send NBP Reply packets from the loopback interface

- contrib/a2boot/a2boot.c
- contrib/a2boot/meson.build
- contrib/macipgw/main.c
- contrib/macipgw/meson.build
- contrib/timelord/meson.build
- contrib/timelord/timelord.c
- doc/ja/manpages/man8/a2boot.8.xml
- doc/ja/manpages/man8/macipgw.8.xml
- doc/ja/manpages/man8/papd.8.xml
- doc/ja/manpages/man8/timelord.8.xml
- doc/manpages/man8/a2boot.8.xml
- doc/manpages/man8/macipgw.8.xml
- doc/manpages/man8/papd.8.xml
- doc/manpages/man8/timelord.8.xml
- etc/atalkd/main.c
- etc/papd/main.c
For atalkd, papd, a2boot, macipgw, timelord: Add a -v/-V flag that prints version number and short description of the daemon. And for the daemons under contrib/ with code that originate outside of Netatalk, print also the COPYRIGHT information.
Note that -v and -V have the same effect for these daemons, with no extra verbose mode implemented. macipgw was using the latter for normal version output, while the former is common for all other daemons in Netatalk. I'm enabling both for backwards compatibility, but only documenting the former.
> Print unified version information for all AppleTalk daemons

- etc/netatalk/afp_avahi.c
- etc/netatalk/afp_mdns.c
- etc/netatalk/afp_zeroconf.c
- etc/uams/uams_passwd.c
- include/atalk/adouble.h
- include/atalk/bstradd.h
- include/atalk/ea.h
- include/atalk/rpc.h
- include/atalk/unix.h
- libatalk/adouble/ad_flush.c
- test/testsuite/compat.h
- test/testsuite/ea.h
- test/testsuite/specs.h
Including C headers by greater than / less than implies an include path relative to standard library location on the system. Our config.h is a local file in our build dir hence the use of quotation marks is appropriate.
> Include config.h by relative path consistently

- meson.build
In case system is assumed to have particular init style, but corresponding service management command (such as `systemctl`, `rc-service`, `rcctl`, etc.) is not found, default to no init scripts. In case `-Dwith-init-style` was explicitly specified, fail the build.
> Default to no init scripts if service management command not found

- libatalk/cnid/mysql/cnid_mysql.c
...revealed when sorting the headers alphabetically...
> Remove duplicate header includes in MySQL CNID backend

- bin/ad/ad_find.c
Sometime after the switch to the INI based configuration in Netatalk 3.0, the `ad find` utility broke. Currently it only works if one enters only lowercase letters and strings of two characters or more. Otherwise it either returns no results or errors out.
> Fix "ad find" utility regression.

- contrib/webmin_module/meson.build
The netatalk-lib.pl file had fallen off the install manifest. If you were overwriting an existing module it worked, but when installing from scratch the module was (obviously) broken.
> webmin: Properly install netatalk-lib.pl that had fallen off recently

- libatalk/cnid/dbd/cnid_dbd.c
This macro once served a purpose, but now the Meson build system controls whether this code is compiled or not.
> Remove unnecessary ifdef macro in cnid_dbd.c

- .github/workflows/static.yml
The outcome should be the netatalk html manual deployed to GitHub Pages for this project.
> GitHub CI: Create html manual deploy job

- doc/meson.build
- meson_options.txt
For when you don't want to have the html pages generated and installed.
> meson: Add manual type man_only which generates only troff pages

- libatalk/bstring/bstrlib.c
When a compiler complains about a missing prototype for a libc function, just inserting one for what you think the interface might be is probably not a good idea.
See also <https://github.com/mvp/uhubctl/issues/586>
> Remove bitrotted inline prototype for a libc function

- .github/workflows/build.yml
This was required in an earlier configuration, but no longer.
> GitHub CI: Remove pkg-config override for NetBSD job

- doc/ja/manual/meson.build
- doc/manual/meson.build
- doc/meson.build
- meson.build
- meson_options.txt
This adds build system functionality for project admins specifically.
First, when building with `-Dwith-manual=www` the python script for refreshing the compile manual XML sources is run
Secondly, with the new `-Dwith-manual-install-path` option you can set a custom install path, e.g. the path to a checked out copy of netatalk-homepage
These automates currently manual parts of the release process.
Note that the build system won't check for required python libraries. Only python3 itself. This is up to the user to prepare.
> meson: Generate appendix doc and allow custom manual install path

- etc/afpd/meson.build
- etc/afpd/quota.c
- meson.build
- test/afpd/meson.build
For the SunRPC / libquota check, look for `quota_open()` instead of the obsolete `getfsquota()`
Don't compile the bundled nfsquota module when using libquota.
> meson: Correct capability check for SunRPC on *BSD

- meson.build
- meson_options.txt
Introduces `-Dwith-perl-path` which takes the path to the containing dir of perl. Passes to absolute path to perl to the build system.
> meson: Option to specify path to perl runtime

- meson.build
The `-Dwith-cups` meson option was declared, but not used in the meson script. This remedies the situation, so that you can explicitly build papd without CUPS support.
> meson: Allow building papd without CUPS

- .github/workflows/build.yml
- meson.build
On macOS when doing `find_library('ldap')` Meson will find LDAP.Framework libraries which are deprecated by Apple.
Ref. https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html
This adds extra logic to the Meson build script to look for openldap libraries as installed by Homebrew, which is the most common use case.
It is still possible to override the logic with the `with-ldap-path` Meson option, if someone has rolled their own openldap installation.
> meson: Favor openldap when building on macOS

- libatalk/util/module.c
Straggler compatibility code for running on the long-obsoleted OSX Server
> Remove obsoleted Mac OS X Server compatibility code in module.c

- test/testsuite/FPSetFileDirParms.c
The test cleanup routine in test358 is unreliable on Debian s390x. The dir is sometimes locked by the system when we try to delete it at the end.
This PR adds assertions to the first two file cleanup steps, and retry logic to the final dir cleanup step.
> testsuite: Retry logic for final cleanup step in test358

- .github/workflows/build.yml
Alpine Linux 3.21 has now moved to localsearch and tinysparql, the new names for tracker libraries.
> GitHub CI: Build on Alpine Linux with localsearch/tinysparql

- INSTALL.md
- doc/ja/manual/install.xml
- doc/manual/install.xml
Also, document CommonMark, a few other clarifications. Then run auto-format with XMLmind.
For more background, see https://github.com/Netatalk/netatalk/issues/318
> docs: Document that DocBook XSL has to be non-namespaced

- meson.build
1. checks for libquota first - should work both on Net- and FreeBSD
2. sets quota_provider accordingly
Patch by @hfath in https://github.com/Netatalk/netatalk/pull/1768
> meson: Improved libquota detection on FreeBSD and NetBSD

- .github/workflows/build.yml
Adding tracker and bison Homebrew packages to the macOS build prerequisites gives us Spotlight support.
> GitHub CI: Build with tracker on macOS to enable Spotlight

- etc/afpd/main.c
- etc/cnid_dbd/cnid_metad.c
- include/atalk/util.h
Earlier versions of macOS such as 10.15 Catalina will throw an error when ulimit is set to too high a number. This PR uses a compliant value when calling `setrlimit()` on macOS specifically.
> Set resource max limit to 10240 on macOS

- .github/workflows/build.yml
- meson.build
- `-Dwith-docbook-path` now overrides all default search paths
- Break when getting a first hit on DocBook stylesheets
- Detect `xsl-stylesheets-nons` with higher priority than `xsl-stylesheets` (Arch Linux compatibility)
- Report xsltproc and docbook-xsl results separately
> meson: Refactor DocBook detection logic to stop when found

- .github/workflows/build.yml
The vmactions project has released v1.1.6 of the FreeBSD image with support for v14.2 of the OS.
> GitHub CI: Use FreeBSD 14.2 vmactions runner

- .github/workflows/build.yml
Remove the hard-coded NetBSD 9.4 release target, and allow the runner to use the latest available version in the vmrunner.
> GitHub CI: Always use latest NetBSD release in runner

- .github/workflows/build.yml
The installed netatalk binaries should be on the PATH, and when not this should be rectified.
For OmniOS and Solaris, use the /opt/local prefix
> GitHub CI: Don't use absolute paths for netatalk binaries

- .github/workflows/build.yml
- etc/afpd/meson.build
- meson.build
- meson_options.txt
- test/afpd/meson.build
Heimdal's krb5 compatibility headers, shared libraries and binaries lives in `/usr/local/heimdal` on (at least) OpenBSD. This introduces a `-Dwith-kerberos-path` that can be used to get Meson to look for dependencies in this location.
Additionally, introduced a break when finding first krb.h header which avoids including broken `krb5/krb5.h` header on NetBSD.
With these changes, the krbV UAM can now be built on NetBSD, OpenBSD, and openSUSE
> meson: Introduce with-kerberos-path option for Heimdal compatibility

- test/testsuite/FPCopyFile.c
- test/testsuite/FPGetFileDirParms.c
- test/testsuite/FPMoveAndRename.c
- test/testsuite/FPResolveID.c
- test/testsuite/T2_FPCopyFile.c
- test/testsuite/T2_FPCreateFile.c
- test/testsuite/T2_FPDelete.c
- test/testsuite/T2_FPGetFileDirParms.c
- test/testsuite/T2_FPGetSrvrParms.c
- test/testsuite/T2_FPMoveAndRename.c
- test/testsuite/T2_FPOpenFork.c.in
- test/testsuite/T2_FPResolveID.c
- test/testsuite/T2_FPSetDirParms.c
- test/testsuite/T2_FPSetFileParms.c
- test/testsuite/afphelper.c
- test/testsuite/specs.h
- Add test322, test417 and test423, which are tier 1 variants of existing tier 2 tests test302, test331 and test420, respectively (meaning that the new tests use AFP commands rather that system calls to set up the test conditions, so that they can be run against a remote host.)
- Disable several assertions that validates CNID doesn't change before and after doing file system level file operations. On macOS, the CNIDs do change. On Linux, they do not. Nothing that I could find in the AFP spec says how the CNID should behave in this case, so I leave these as FIXMEs in the code.
- Remove the old `T_MAC_PATH` exclusion criteria, convert those tests to the `T_PATH` flag, and remove a handful of obsolete "Mac" fallback code. I believe this code originated from an era when you would have …
> testsuite: Cross-platform compatible file ID tests

- .github/workflows/build.yml
vmactions image v1.1.6 ships NetBSD 10.1
> GitHub CI: Bump to NetBSD 10.1 runner

- test/testsuite/Error.c
test102 and test103 in the Error test suite attempt to move and rename test data that the primary test user arguably should not have access to. However, the actual behavior is different between Linux and macOS. This PR disables those operations in the two tests, and leaves FIXME comments to work out in the future what is the correct behavior.
> testsuite: Don't attempt unauthorized file renaming in Error tests

- libatalk/adouble/ad_open.c
The length of `dev_t` on macOS is 4 as opposed to 8 on other platforms. The current code that checks the validity of AppleDouble headers expects the length of a `PRIVDEV` AppleDouble entry to always be fixed at 8. Once this fix is applied, the function `ad_getid()` appear to be working and filesystem information (dev, ino, etc) is now being written to AppleDouble files. Scans with the `dbd` tool should also work now. Previously they were failing with not being able to retrieve data from AppleDouble files.
Right now, Darwin/macOS is the only platform this appears to be an issue on, so we only loosen the check on that platform. If other platforms have this issue, we can later remove the #ifdef macro. May fix #1826
> Loosen AppleDouble checks for macOS

- test/testsuite/T2_FPGetFileDirParms.c
- test/testsuite/T2_FPMoveAndRename.c
- test/testsuite/T2_FPResolveID.c
With https://github.com/Netatalk/netatalk/pull/1829 the checks for unchanged IDs for files and dirs after file system operations are passing on macOS. This restores these assertions.
> testsuite: Restore file ID checks following fix for macOS AD validation

- test/testsuite/encoding_test.c
Straggler test file `:test` needs to be removed after running the Western encoding test.
> testsuite: Clean up test file after execution of encoding test

- .github/workflows/build.yml
Berkeley DB v5 is the last Sleepycat licensed version, and therefore the last GPLv2 compatible one. While I doubt the GitHub CI job can be considered redistribution, it's good to make it a habit to use v5 for all reference builds.
> GitHub CI: Build with berkeley-db v5 on macOS

- distrib/initscripts/macos.netatalk.in
The build system should no longer link with Apple Objective-C frameworks
> initscripts: Disable fork safety workaround for macOS

- .github/workflows/static.yml
No need to re-deploy the static html manual when no manual files have changed.
> Deploy html manual to Pages only when doc files change

- etc/afpd/auth.h
Only report AFP2.2 or newer in FPGetSrvrInfo calls when compiling with AppleTalk disabled. This restores back Netatalk 2.x behavior.
> Fix reported AFP versions when AppleTalk support is disabled.

- bin/afppasswd/afppasswd.c
Fix two outstanding issues with the afppasswd utility.
-Null out the rest of the password input string when one enters a new password of less then eight characters.
-Fix a bug introduced when the switch to libgcrypt was made. When using a key file, the key was being nulled out before it was sent to libcrypt!
> Fix afppasswd utility

- doc/ja/manual/upgrade.xml
- doc/manual/upgrade.xml
- etc/afpd/file.c
- include/atalk/adouble.h
- include/atalk/ea.h
- libatalk/adouble/ad_conv.c
- libatalk/adouble/ad_flush.c
- libatalk/adouble/ad_open.c
- libatalk/vfs/extattr.c
- libatalk/vfs/vfs.c
- meson.build
- test/testsuite/adoublehelper.c
- test/testsuite/ea.h
- test/testsuite/extattr.c
-Store all extended attributes without the `user.` prefix on macOS. This will orphan Netatalk metadata created on past versions, but is needed for native extended attributes to work properly on shares. Unlike Linux, macOS doesn't prefix user created extended attributes with `user.`.
-Store resource forks natively by using the `/..namedfork/rsrc` path instead of creating AppleDouble files. No need for separate files since the file system supports it natively.
-Synchronize native FinderInfo (stored in `com.apple.FinderInfo`) with Netatalk. Any changes made to FinderInfo by Netatalk clients or by the host OS are now visible to each other. Note that the contents of `com.apple.FinderInfo` take priority of that over what is stored in Netatalk's extended attributes.
> Add native metadata storage for macOS hosts.

- .github/workflows/build.yml
Letting pkg_add choose pkgsrc mirror leads to flaky results. This will force it to use the main netbsd.org mirror.
> GitHub CI: Use specific pkgsrc mirror for NetBSD package

- contrib/webmin_module/netatalk-lib.pl
- doc/ja/manpages/man5/afp.conf.5.xml
- doc/ja/manual/upgrade.xml
- doc/manpages/man5/afp.conf.5.xml
- doc/manual/upgrade.xml
- etc/afpd/afprun.c
- etc/afpd/fce_api.c
- etc/afpd/volume.c
- include/atalk/volume.h
- libatalk/util/netatalk_conf.c
This modifies the afprun() function to execute shell commands only as the current user, not as root.
Removing the following runtime options:
- root preexec
- root postexec
- root preexec close
> Remove the ability to run AFP commands with root privileges

- .github/workflows/build.yml
I don't think it will make a difference, but just in case we get less flakiness out of openSUSE Tumbleweed by running zypper update first...
> GitHub CI: Run zypper update before new package on openSUSE

- include/atalk/ea.h
- libatalk/vfs/ea_sys.c
Currently, a client can create new files on the server with the same name as the Netatalk metadata extended attribute (`org.netatalk.Metadata`). If this EA has valid AppleDouble data (ex: from another Netatalk host), the server will treat the EA as read-only and not be able to update the data.
Additionally clients will not be able to update metadata on the file such as comments or FinderInfo. The only way to fix the problem is deleting the extended attribute on the server side, or deleting the file.
> Protect Netatalk metadata EA

- doc/DEVELOPER
- doc/README.AppleTalk
- doc/manpages/man5/afp.conf.5.xml
- doc/manpages/man8/atalkd.8.xml
- doc/manpages/man8/cnid_dbd.8.xml
- doc/manual/appletalk.xml
- doc/manual/configuration.xml
- doc/manual/upgrade.xml
Found while reading the docs and running `hunspell` against the source files.
> docs: Fixes for spelling and grammar

- distrib/initscripts/macos.netatalk.plist.in
An issue with the current implementation of the launchd item is that unloading or stopping the it (e.g by running `sudo brew services stop netatalk`) doesn't actually stop the `netatalk` process. This is because the launchd is running the equivalent of `sudo netatalkd start` (which starts `netatalk` (which itself starts `afpd` and `cnid_metad`)) and immediately exits. 
Since Apple's [docs for processes managed by launchd](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html) specify that they be non-forking, a workaround is to invoke the `netatalk` process directly with its `-d` flag. When the launchd item is stopped, `netatalk` is ended along with `afpd` and `cnid_metad`.
> launchd item: Start netatalk in non-forking mode

- bin/ad/meson.build
- bin/aecho/meson.build
- bin/afppasswd/meson.build
- bin/getzones/meson.build
- bin/misc/meson.build
- bin/nbp/meson.build
- bin/pap/meson.build
- contrib/a2boot/meson.build
- contrib/macipgw/meson.build
- contrib/timelord/meson.build
- etc/afpd/meson.build
- etc/atalkd/meson.build
- etc/cnid_dbd/meson.build
- etc/netatalk/meson.build
- etc/papd/meson.build
- etc/spotlight/meson.build
- meson.build
Addresses a build issue with cross-compiling with iconv as meson cannot run code to determine if INTERNAL iconv support is available.
Addresses linking issues when iconv is supported by libiconv (detected or with path provided) instead of the more common libc6 implementation in Linux (maybe MacOS and others too).
> iconv fixes for OpenWrt

- doc/ja/manpages/man8/afpd.8.xml
- doc/ja/manpages/man8/atalkd.8.xml
- doc/ja/manpages/man8/netatalk.8.xml
- doc/manpages/man8/afpd.8.xml
- doc/manpages/man8/atalkd.8.xml
- doc/manpages/man8/netatalk.8.xml
Create a unified theme for the usage of the -d option across the daemons.
> docs: Clarify the behavior of the -d option for daemons

- etc/papd/meson.build
No need to link with a library that isn't needed, and might not exist.
> meson: Link papd with cups only when cups is enabled

- etc/afpd/file.c
- libatalk/adouble/ad_conv.c
- libatalk/adouble/ad_flush.c
- libatalk/adouble/ad_open.c
Check size of `com.apple.FinderInfo` EA to verify it exists before returning.
> Refactor retreival of native FinderInfo EA on macOS hosts.

- .github/workflows/build.yml
Use the latest upstream vmactions runner images, as well as the unversioned openldap26 package in FreeBSD (they finally seem to have removed that ambiguity from Ports)
> GitHub CI: Bump to the latest BSD vmactions runners

- test/testsuite/FPDisconnectOldSession.c
- test/testsuite/lantest.c
Explicit freeing of alloced memory in a handful of testsuite tests, flagged by Sonar.
> testsuite: Free memory after running tests

- config/macipgw.conf
- config/meson.build
- contrib/macipgw/common.h
- contrib/macipgw/macip.c
- contrib/macipgw/main.c
- contrib/macipgw/meson.build
- contrib/macipgw/tunnel.h
- contrib/macipgw/tunnel_bsd.c
- contrib/macipgw/tunnel_linux.c
- contrib/macipgw/util.c
- contrib/macipgw/util.h
- distrib/initscripts/netbsd.macipgw.in
- distrib/initscripts/openrc.macipgw.in
- distrib/initscripts/systemd.macipgw.service.in
- doc/ja/manpages/man8/atalkd.8.xml
- doc/ja/manpages/man8/macipgw.8.xml
- doc/manpages/man5/macipgw.conf.5
- doc/manpages/man5/meson.build
- doc/manpages/man8/macipgw.8.xml
Makes the macipgw daemon look for a macipgw.conf file in the default netatalk pkgconf path.  Without the config file, macipgw should behave as before.
Point to conf file in custom location with the `-f` terminal option.
Sample macipgw.conf file:
```
[Global]
network = 192.168.151.0
netmask = 255.255.255.0
nameserver = 8.8.8.8
zone = My Zone
unprivileged user = dmark
```
This changeset also fixes a few type safety issues.
> macipgw: Introduce a configuration file

- .github/workflows/containers.yml
- contrib/shell_utils/docker-entrypoint.sh
This will run afp_lantest and afp_speedtest with default parameters. For now, this is mainly to validate that these two don't break. Not really to track performance (yet).
> GitHub CI: Run lantest and speedtest jobs

- .github/workflows/build.yml
Rather than mysql, use the more light-weight mariadb on macOS to build the mysql CNID backend
> GitHub CI: Build with mariadb on macOS

- etc/afpd/catsearch.c
- etc/afpd/enumerate.c
- etc/afpd/fce_api.c
- etc/afpd/file.c
- etc/afpd/volume.c
- etc/uams/uams_dhx_passwd.c
- include/atalk/adouble.h
- libatalk/adouble/ad_conv.c
- libatalk/adouble/ad_open.c
- libatalk/adouble/ad_write.c
- test/testsuite/speedtest.c
Resolves all compiler warnings thrown by Apple clang version 16.0.0 (clang-1600.0.26.6)
> Resolve macOS 15 clang compiler warnings

- config/macipgw.conf
Having a public DNS server configured by default is considered a tracking antipattern, while no default IP address can work in all network configurations.
> config: Disable default options in macipgw.conf

- .github/workflows/build.yml
Resolves GitLab CI warnings, adds cracklib package, runs brew upgrade first, and adds linebreaks to brew install command
> GitHub CI: Cleanup of macOS job

- doc/ja/manpages/man5/afp.conf.5.xml
- doc/ja/manual/configuration.xml
- doc/manpages/man5/afp.conf.5.xml
- doc/manual/configuration.xml
The afp.conf man page contained large sections on CNID backends and encoding that largely duplicated information already in the Configuration chapter.
This PR consolidates information into other parts of the afp.conf man page, or the Configuration chapter, while removing aforementioned redundant sections.
This has the benefit of cutting down the clutter a bit in the already-too-long afp.conf man page.
I also took the opportunity to add a little more explanations of the mysql CNID backend.
Formatted with XMLmind.
> docs: Consolidate redundant CNID and encoding info

- meson.build
While making the builds Homebrew compatible I went overboard with bypassing the granular bdb version prioritization.
This brings back the previous logic, by simply removing an early find_library() call that was added.
> meson: Restore prioritized Berkeley DB detection

- SECURITY.md
Create an official policy of 12 month patch cycle after superseding release.
> Add a security patching end-of-life policy

- .github/workflows/build.yml
The dirty repo state will fail the distcheck later
> GitHub CI: Build on Ubuntu without Unicode data to avoid dirty repo

- contrib/macipgw/main.c
- `atalk_iniparser_load()` returns NULL when unsuccessful
- free the iniparser dictionary object after extracting the data we need
- add a missing newline in fprinted string
> macipgw: Correct iniparser status check; free memory afterwards

- .github/workflows/build.yml
This is the portable way to set the PKG_PATH env variable, to accommodate future NetBSD version bumps.
> GitHub CI: NetBSD version agnostic PKG_PATH definition

- contrib/macipgw/main.c
The -f option for specifying config file was added recently. This adds a note on this to the usage helptext.
> macipgw: Print usage notes for the -f option

- etc/afpd/dircache.c
This might help us pinpoint the cause of a recurring crash in the dircache module
> afpd: Log an error in dirchache when directory has invalid did

- meson.build
NixOS stores find in a different location
> meson: remove hardcoded file command path.

- meson.build
This stops libquota from being detected on NetBSD, and leads to a fallback to legacy SunRPC headers.
> meson: Remove libquota check that causes breakage on NetBSD

- meson.build
- meson_options.txt
In some environments, notable NixOS, lib and include for a library is in different dirs. Since we have a hackish berkeley db detection routine, this new `-Dwith-bdb-include-path` option allows you to define an include path separate from the lib path for bdb.
> meson: Introduce with-bdb-include-path override option

- libatalk/cnid/mysql/cnid_mysql.c
This adds the standard GNU GPL v2 license grant blurb to this one source file. It currently defers to [COPYING](https://github.com/Netatalk/netatalk/blob/main/COPYING) for the license, which is ambiguous.
Approved by original author in a comment below.
> Add GPL v2 license grant to mysql CNID backend code

- meson.build
Some environments keep the Berkeley DB shared libraries in a versioned subdir, like what is common with the Berkeley DB include dir. This change makes it so that checking the subdir is a fallback when looking for libraries.
> meson: Look for shared Berkeley DB library in versioned subdir too

- doc/manual/AppleTalk.md
- doc/manual/Configuration.md
- doc/manual/Installation.md
- doc/manual/Upgrading.md
- doc/manual/_Sidebar.md
- doc/po/AppleTalk.md.ja.po
- doc/po/Configuration.md.ja.po
- doc/po/Installation.md.ja.po
- doc/po/Upgrading.md.ja.po
- doc/po/_Sidebar.md.ja.po
- doc/po4a.cfg
- doc/translated/ja/meson.build
Fixing a grab bag of incorrect hyperlinks in the manual Markdown sources.
Also moving away from localizing file names. In practice, this caused extra overhead when doing translations to little benefit.
> docs: Use correct Markdown hyperlinks in manual

- etc/afpd/uam.c
I didn't immediately find a smaller way to prevent compiler warnings with gcc 11.4.0.  Originally, gcc complained thus.
[131/205] Compiling C object etc/afpd/libafpd.a.p/uam.c.o
../etc/afpd/uam.c: In function ‘uam_getname’:
../etc/afpd/uam.c:214:25: warning: argument 1 null where non-null expected [-Wnonnull]
214 |                 pwent = getpwnam(bdata(princ));
|                         ^~~~~~~~
In file included from ../include/atalk/uam.h:8,
from ../include/atalk/globals.h:23,
from ../include/atalk/dsi.h:17,
from ../etc/afpd/uam.c:30:
/usr/include/pwd.h:116:23: note: in a call to function ‘getpwnam’ declared ‘nonnull’
116 | extern struct passwd *getpwnam (const char *__name) __nonnull ((1));
|                       ^~~~~~~~
> Avoid compiler complaints re: getpwnam() argument being NULL

- bin/misc/uuidtest.c
- doc/manpages/man5/afp.conf.5.md
- doc/po/afp.conf.5.md.ja.po
- libatalk/acl/ldap.c
- libatalk/acl/ldap_config.c
Stub code for LDAP SASL auth was put in place way back when ACL was first implemented. But it's never been implemented. So let's remove it.
> Remove traces of unsupported LDAP SASL auth

- doc/manpages/man5/afp.conf.5.md
- doc/po/afp.conf.5.md.ja.po
Making the afp.conf man page a tad bit more helpful.
> docs: Add config examples to afp.conf man page

- .github/workflows/build.yml
- libatalk/unicode/meson.build
- meson.build
- meson_options.txt
The new `with-unicode-data` Meson build system option will control whether to attempt to rebuild the Unicode case table sources or not. This is disabled by default, which is a change from before.
This makes it so that there are no surprising changes to local source files unless you deliberately ask for it.
> meson: Introduce with-unicode-data option to build case tables

- doc/manual/Compilation.md
- doc/manual/generate_compile_docs.py
- doc/manual/meson.build
- doc/meson.build
- doc/po/Compilation.md.ja.po
The meson logic for building the compilation html manual chapter had fallen off during the Markdown transition. This brings it back, while refactoring this part of the meson script.
Also refreshes the compilation chapter for good measure.
> meson: Restore and clean up the compilation docs generation logic

- config/meson.build
- config/pap.in
- doc/manual/AppleTalk.md
- doc/po/AppleTalk.md.ja.po
Thomas Kaiser's pap backend wrapper shell script, adapted from the version that's distributed on emaculation:
https://www.emaculation.com/pap_tkaiser_v0.1.4.tgz
I've merged the license text into the header of the script. And, removed the changelog, todo note, and other redundant header information. Unlike the original script, the bindir is now substituted through the netatalk build system.
> Bundle Thomas Kaiser's pap backend for CUPS

- meson.build
Enables the build system to find bdb libs in a MacPorts environment.
> [4.1] meson: Look for shared Berkeley DB library in versioned subdir too

- bin/aecho/aecho.c
- bin/getzones/getzones.c
- bin/nbp/nbplkup.c
- contrib/a2boot/a2boot.c
- contrib/timelord/timelord.c
- etc/afpd/afp_asp.c
- etc/afpd/afp_dsi.c
- etc/afpd/afp_options.c
- etc/afpd/nfsquota.c
- etc/afpd/unix.h
- include/atalk/globals.h
- libatalk/asp/asp_tickle.c
- libatalk/dsi/dsi_tcp.c
- libatalk/nbp/nbp_lkup.c
- libatalk/nbp/nbp_rgstr.c
- libatalk/nbp/nbp_unrgstr.c
- libatalk/nbp/nbp_util.c
- libatalk/util/ftw.c
- meson.build
- test/testsuite/afpclient.h
This eliminates redundant header and function checks inherited from Autotools. Speeds up the setup process notably: for instance on my MacBook Pro M1, 8s -> 7s. (Should be even more notable on slower systems.)
> meson: Clean up obsolete header and function checks

- Dockerfile
- Dockerfile.testsuite
- contrib/shell_utils/docker-entrypoint.sh
Remove bash dependency in Dockerfile and refactor the entrypoint script to be POSIX compliant.
> docker: Remove dependence on bash in entry script

- .github/workflows/build.yml
…because tracker is going away
Homebrew has flagged the tracker formula for deletion in early 2026. At the same time, Homebrew does not support tinysparql on macOS (only Linux.)
Without either of those, Spotlight cannot be built, so removing the entire stack.
> GitHub CI: Build without Spotlight support on macOS

- .github/workflows/build.yml
- .github/workflows/containers.yml
- .github/workflows/static.yml
- .github/workflows/test.yml
The Sonarqube github actions have been renamed and updated. Migration is mandatory.
https://github.com/SonarSource/sonarqube-scan-action
> GitHub CI: SonarQube static analysis in own workflow, using v4 action

- libatalk/unicode/charcnv.c
If the errno and the file name that caused the problem are not logged, it is very difficult to diagnose why the conversions fail.
When conversions fail, eventually netatalk may get into a loop of trying to "wipe the slate clean" in the CNID database.  But if it keeps failing, clients will hang while trying to e.g. read a directory.  On macOS, this hang is quite annoying because e.g.: Finder never gives up so this can lead to apparent hangs.
> Improved logging for the case where charset conversion fails

- .github/workflows/build.yml
- meson.build
A few tweaks to the meson build script to enable building with cracklib support on macOS with Homebrew.
> meson: Detect cracklib library and dictionary on macOS / Homebrew

- etc/afpd/uam.c
- libatalk/util/netatalk_conf.c
Addressing a handful of Sonarqube reliability bugs that came up in modified code
> Memory and thread safety in afpd and libatalk

- libatalk/util/netatalk_conf.c
I don't think we need this extra error handling for strdup() operations on variables that were strduped just before. The error handling macros breaks out of the function without freeing the memory.
> libatalk: Plug another two potential memory leaks

- .github/workflows/containers.yml
- contrib/shell_utils/docker-entrypoint.sh
- test/testsuite/FPGetACL.c
- test/testsuite/T2_FPMoveAndRename.c
- test/testsuite/T2_FPOpenFork.c.in
The testsuite needed minor fixes to fully pass when using ad v2 metadata. First, test302 is updated with the correct rename function that also moves the appledouble metadata files, while test431 and test432 are skipped because they concern EA metadata.
Now let's run tests for AppleDouble v2 in the pipeline in addition to the standard filesystem EA. The metadata logic is entirely different and is known to be fragile.
> Make testsuite AppleDouble v2 compatible, and run it in CI

- libatalk/vfs/ea_ad.c
- test/testsuite/FPCopyFile.c
- test/testsuite/FPGetACL.c
Refactoring write_ea operation in the libatalk vfs module to be more concurrency safe.
> libatalk: Use file descriptors and exclusive access to avoid TOCTOU conditions

- doc/manpages/man5/afp.conf.5.md
- doc/manual/Compilation.md
- doc/po/Compilation.md.ja.po
- doc/po/Installation.md.ja.po
- doc/po/afp.conf.5.md.ja.po
- include/atalk/globals.h
- libatalk/util/netatalk_conf.c
This addresses two issues following the move to linking with a regular shared iniparser library.
- Introduce `name =` option to volumes which sets a custom volume name. This works around the fact that section names are forced lowercase in iniparser. And arguably, this is a better pattern, since ini file section names are really only meant as internal identifiers as the original iniparser design.
- Treat section names as all lowercase internally, so that the Homes dir isn't ignored.
- Rewrite the introduction and Homes section in the afp.conf man page
> Config file handling compatible with upstream iniparser

- doc/manual/_Navlinks.md
- doc/manual/meson.build
This brings back rudimentary navigation links for the html manual generated for local consumption.
> docs: Create a more navigation friendly local html manual

- doc/manpages/man5/afp.conf.5.md
The afp.conf man page was still using the description of the old `-hostname` option in netatalk 2.x verbatim, despite the behavior having changed completely as of 3.x.
Thanks to thecloud on 68kmla for reporting this.
> docs: Correct description of hostname option in afp.conf

- contrib/macipgw/main.c
- etc/afpd/afp_config.c
- etc/afpd/spotlight.c
- etc/cnid_dbd/cnid_metad.c
- etc/netatalk/netatalk.c
- include/atalk/globals.h
- libatalk/acl/ldap_config.c
- libatalk/util/netatalk_conf.c
Three new local utility functions in netatalk_conf that wrap iniparser calls, as well as allow for the use of presets:
- getoption_str() which a renamed getoption()
- getoption_strdup() which returns a dynamically allocated string
- getoption_int() which returns an integer
All of these are now consistently applied throughout netatalk_conf.c
For the global usecase, where presets aren't relevant, we now use these two macros consistently:
- INIPARSER_GETSTR
- INIPARSER_GETSTRDUP
This also allows us to get back to using the INISEC_GLOBAL and INISEC_HOMES macros for section names, rather than hard coded strings.
> libatalk: Introduce standardized interface for iniparser

- doc/manpages/man5/afp.conf.5.md
- doc/po/afp.conf.5.md.ja.po
`cnid listen` is used by cnid_metad to listen to db connections from afpd, while `cnid server` is used by afpd to tell it which cnid_metad to attempt to make db connections to. This documentation tweak should hopefully make that more clear.
> docs: Elaborate on the relationship between cnid server and cnid listen

- etc/afpd/afp_config.c
Missing part of https://github.com/Netatalk/netatalk/pull/1974 where the new servername option was introduced.
> afpd: Use servername for ASP connections with hostname fallback

- contrib/shell_utils/docker-entrypoint.sh
Set `DEBUG_ENTRY_SCRIPT` to non-zero to echo back all shell commands to the terminal.
> docker: Introduce env variable flag for enabling debug mode in entry script

- DOCKER.md
- contrib/shell_utils/docker-entrypoint.sh
When enabled, the secondary user is set to `nobody` and the secondary shared volume to be r/w by the guest user (while the primary volume is read-only by the guest user).
When setting $AFP_DROPBOX to non-zero, this will enable dropbox permissions, turn on insecure auth, disable time machine, and set the name of the secondary volume to Dropbox.
> docker: Introduce dropbox mode option for guest access

- contrib/shell_utils/docker-entrypoint.sh
- doc/manpages/man1/dbd.1.md
- doc/manpages/man5/afp.conf.5.md
- doc/manual/Upgrading.md
- libatalk/util/netatalk_conf.c
- test/afpd/test.sh
- test/testsuite/README
- test/testsuite/afphelper.c
- test/testsuite/spectest.c
- test/testsuite/spectest.sh
- Always use ad v2 metadata with ad, and ea metadata with sys
- Remove the distinct 'appledouble' option
- Remove references to the 'ea = auto' option since it is undefined
- Use ad v2 fallback for ea metadata rather than none
> Control metadata settings with 'ea' solely, removing 'appledouble' option

- meson.build
Things break in insidious ways when build with quota on NetBSD using the deprecated API
> meson: Disable quota on NetBSD while addressing GitHub #1225

- libatalk/bstring/bstrlib.c
A handful of memory safety fixes, flagged by Sonarqube.
> bstrlib: Protect against buffer overflow, null pointer dereference

- bin/ad/ad_find.c
- bin/ad/ad_mv.c
- bin/misc/fce.c
- bin/misc/netacnv.c
- etc/afpd/appl.c
- etc/afpd/enumerate.c
- etc/afpd/fce_api.c
- etc/cnid_dbd/cnid_metad.c
- etc/cnid_dbd/main.c
- libatalk/bstring/bstrlib.c
- libatalk/util/netatalk_conf.c
- libatalk/vfs/ea_sys.c
- libatalk/vfs/vfs.c
Addresses critical level reliability bugs flagged by SonarQube.
One notable change is in our vendored bstrlib, where the `bdestroy()` function has been rewritten a bit to be more aggressive about freeing memory even when individual members of the bstring object are malformed. This addresses potential memory leak issues.
In afpd, this changeset partially reverts earlier refactoring that attempted to address the same memory leaks, with simpler and less intrusive solutions.
While refactoring, I noticed that the loop for skipped dirs was nested in the loop for skipped files in the FCE API module, so I split them apart. I think this was a bug.
> Protect against memory leaks and out of bounds array access

- doc/manpages/man5/meson.build
This man page alias should only be installed when building with appletalk
> docs: Install macipgw.conf.5 man page only with appletalk

- etc/atalkd/rtmp.c
The previous solution led to memory corruption over time, so bringing back a variation of the previous one.
Partially reverts https://github.com/Netatalk/netatalk/commit/80509342c1e39c9d460428a15bc96fd61913685b
> atalkd: Bring back freeing of allocated memory into rtmp_delzonemap loop

- bin/ad/ad_mv.c
- bin/misc/netacnv.c
- etc/cnid_dbd/main.c
- libatalk/vfs/vfs.c
Protect against double allocation of optarg data, and properly release memory when exiting due to error.
The AppleDouble file copy routine in the vfs module has been rewritten with more efficient stack buffers.
> Plug a number of potential memory leaks in optarg and error handling

- etc/afpd/appl.c
- etc/afpd/enumerate.c
- etc/afpd/fce_api.c
- libatalk/util/ftw.c
In afpd, this shores up protections in the appl, enumerate and the fce API modules. This reverts previous attempts at plugging the same holes that didn't quite address all potential entry points.
It also has adds protections in our fork of the glibc ftw library.
> Safer memory handling and afpd and the ftw library

- contrib/shell_utils/asip-status.in
With approval from the original author, this adds the standard GPL v2 license grant, and updates the copyright year as per the (now defunct) home page for this script.
Also removing outdated information from the header.
> Update asip-status.in license grant and copyright year

- doc/manpages/man5/afp.conf.5.md
- etc/afpd/fce_api.c
- Iterate over skipped files in a single function and single loop
to reduce code duplication and avoid memory leaks
- Use comma as the delimiter for 'fce ignore names'
which makes it the same as 'fce ignore directories'
- Stop appending slash to the end of dirs to skip
- Add null checks to avoid segfaulting
> afpd: Refactor FCE file skip logic, make comma the standard delineator

- libatalk/util/ftw.c
Checking for both non-null and actsize before freeing memory. Also, revert a previous fix for memory safety that didn't have the indented effect.
> libatalk: Double check before freeing memory, reverting previous fix for ftw

- etc/afpd/enumerate.c
The NAME_MAX macro wasn't full cross-platform compatible (Solaris.)
> afpd: Use MAXPATHLEN macro to manage limits in enumerate_loop

- libatalk/util/ftw.c
Doing an early check on actsize and bail out if 0, to avoid memory management failure later.
> libatalk: Bail out early when actsize is 0 in ftw library

- etc/uams/uams_guest.c
- etc/uams/uams_pam.c
- etc/uams/uams_passwd.c
- include/atalk/unicode.h
- include/atalk/util.h
- libatalk/asp/asp_getsess.c
- libatalk/dsi/dsi_attn.c
- libatalk/netddp/netddp_recvfrom.c
- libatalk/unicode/iconv.c
- libatalk/util/ftw.c
Clean up local definitions of the MIN and MAX macros since they're defined properly in include/atalk/util.h
Bizarrely, util.h actually contained duplicate definitions of the same two macros. Probably an artifact of disparate feature branches being merged.
> Remove MIN/MAX macros that are already defined centrally

- libatalk/util/ftw.c
We shouldn't need to handle longer entries than what our implementation supports right now.
> libatalk: Use standard early OSX UTF8 filename length limit in ftw

- etc/uams/uams_guest.c
Grounds for this change:
The 2001 copyright date, without an author name, was added in commit 5268a18 in February 2001 by rufustfirefly, which contained no other change to this source file that would justify claiming copyright. The same author had no previous contributions to this source file according to the commit log.
In the commit just before that from July 2000, Andrew Morgan added substantial new code, but he claimed no explicit copyright at that time.
The commit before that was the original revision when the project was first brought under revision control.
The code of uams_guest.c at the time of this original revision is a nearly exact match with the noauth_login() function in etc/afpd/auth.c of the 1.4b2 release version source code. This source code had the standard Regents of …
> Update uams_guest.c with accurate copyright header

- bin/pap/papstatus.c
- etc/afpd/directory.c
- etc/afpd/enumerate.c
- etc/afpd/fce_api.c
- etc/atalkd/main.c
- etc/atalkd/rtmp.c
- test/testsuite/adoublehelper.c
- test/testsuite/lantest.c
This addresses all current high severity Sonarqube code bugs.
> Protect against null pointer dereference; use correct return values; division by zero

- etc/afpd/file.c
- libatalk/unicode/charcnv.c
Historically, this project has used a minor optimization technique, leaving certain key variables uninitialized at the top of the function. This has led to undefined behavior when code paths subsequently changed.
> Initialize the last few variables that were once flagged as: uninitialized ok

- etc/afpd/uam.c
- etc/papd/uam.c
This is a long since removed flag, and not a common C convention to my best knowledge.
> Eliminate obsoleted NO_REAL_USER_NAME capability flag macro

- doc/manpages/man5/afp.conf.5.md
- doc/manpages/man5/atalkd.conf.5.md
- doc/manpages/man8/cnid_dbd.8.md
- doc/manual/AppleTalk.md
- doc/manual/Configuration.md
- doc/manual/Installation.md
- doc/manual/License.md
- doc/manual/Upgrading.md
- doc/po/AppleTalk.md.ja.po
- doc/po/Configuration.md.ja.po
- doc/po/Installation.md.ja.po
- doc/po/Upgrading.md.ja.po
- doc/po/afp.conf.5.md.ja.po
- doc/po/atalkd.conf.5.md.ja.po
- doc/po/cnid_dbd.8.md.ja.po
This should give us the correct layout when using the Python markdown library to generate html
> docs: Clean up markdown indentation in manual and man pages

- doc/manpages/man5/afp.conf.5.md
- doc/po/afp.conf.5.md.ja.po
This introduces additional subsections and moves options around for better groupings.
In particular, it reduces the size of the Miscellaneous section.
> docs: Rearrange sections on the afp.conf man page for better organization

- etc/afpd/afp_util.c
This source file was committed by Joe Marcus Clarke in 2002, so adding him as a named copyright holder instead of the generic "netatalk".
The standard project copyright still applies.
> Update afp_util.c with named copyright holder

- etc/afpd/file.c
This registers a FCE_FILE_CREATE event when exiting afp_copyfile()
without error. Without this, events when copying files within the
dir structure, or duplicate files in place in Finder, were missing.
> afpd: Register FCE file creation event when copying files

- libatalk/cnid/mysql/cnid_mysql.c
Additionally, move the macro to before the first header include, as per GNU docs.
> libatalk: Undefine _FORTIFY_SOURCE macro only when defined

- .github/workflows/build.yml
The krb5-devel package has gone missing from DragonflyBSD's ports repo. It is probably just a temporary glitch. But let's remove this dependency to unblock the pipeline.
> GitHub CI: Build on DragonflyBSD without krb5

- include/atalk/globals.h
- libatalk/util/netatalk_conf.c
The 'include' directive in afp.conf is no longer supported, following the move to linking with the system iniparser library. This removes remaining logic that managed the path and state of the included ini file.
> Remove remnants of nested afp.conf ini file inclusion

- etc/afpd/afp_dsi.c
- etc/afpd/afprun.c
- etc/afpd/dircache.c
- etc/atalkd/main.c
- etc/atalkd/main.h
- include/atalk/util.h
- libatalk/util/unix.c
This takes the tmpdir() method previously used locally in the afprun module and turns it into a global member of libatalk. Then, apply it instead of local hard coding of /tmp across the codebase.
> Move global temp dir handling to libatalk util module

- etc/afpd/filedir.c
- etc/afpd/fork.h
- etc/afpd/ofork.c
- libatalk/util/meson.build
- libatalk/util/unix.c
- libatalk/vfs/unix.c
- meson.build
- meson_config.h
The so-called at functions were introduced in the standard C libraries everywhere in the mid 2000s. We shouldn't need these fallbacks anymore.
> Always use at functions of the standard C library

- meson.build
- meson_options.txt
These changes make non-PAM auth work on FreeBSD, while we correctly alert that only PAM auth is available on macOS.
- Split up the crypt and crypt.h checks. On *BSD the crypt library is in unistd.h
- Remove the with-shadow option, and always build with shadow support if possible
- Only throw warning with neither crypt nor shadow is available
> meson: Cross-platform crypt library detection; always use shadow when available

- .github/workflows/build.yml
PAM on OpenBSD has been broken since ancient times. Let's build without it in CI.
> GitHub CI: Don't build with PAM on OpenBSD

- etc/afpd/uam.c
- meson.build
- meson_config.h
This unblocks basic authentication on OpenBSD
Inspired by patches by Nils Frohberg, Stuart Henderson, and Antoine Jacoutot
From the OpenBSD project
> afpd: Use getpwnam_shadow() for basic auth on OpenBSD

- libatalk/dsi/dsi_tcp.c
The fix for SourceForge bug 602 - 0b7f7fe6e - made afpd listen on IPv6 wildcard sockets on all plaforms.
An IPv4 socket is a more apt default for OpenBSD.
Originally reported and tested by Johan Huldtgren
Patch by Stuart Henderson, modified by Antoine Jacoutot From the OpenBSD project
> libatalk: IPv6 sockets only accept IPv6 connections on OpenBSD

- etc/uams/uams_passwd.c
When the shadow password was expired in the ClearTxt UAM, a return code was set but hardly used. This returns immediately instead, which is in line with the behavior elsewhere in this module.
> uams: Return properly when ClearTxt shadow password has expired

- libatalk/dsi/dsi_tcp.c
OpenBSD lacks dual IPv4/IPv6 stack. The following makes for a better default.
Patch by Antoine Jacoutot from the OpenBSD project
> libatalk: Use unspecified network stack by default on OpenBSD

- etc/uams/meson.build
- etc/uams/uams_dhx2_passwd.c
- etc/uams/uams_dhx_passwd.c
- etc/uams/uams_passwd.c
- meson.build
- meson_config.h
The crypt() function is flagged as deprecated for OpenBSD,
so using the slightly more elegant crypt_checkpass() when available.
Also refactors the crypt/shadow checks in Meson to give a
more accurate summary output.
> uams: Support for OpenBSD flavor crypt_checkpass() for password validation

- bin/ad/ad_ls.c
- bin/ad/ad_mv.c
- bin/afppasswd/afppasswd.c
- bin/afppasswd/meson.build
- bin/nbp/nbplkup.c
- etc/afpd/auth.c
- etc/atalkd/config.c
- etc/atalkd/main.c
- etc/cnid_dbd/cmd_dbd_scanvol.c
- etc/cnid_dbd/cnid_metad.c
- etc/cnid_dbd/db_param.c
This addresses a number of OpenBSD compiler warnings
This continues a process of adopting these BSD extension that started at least 16 years ago with commits like https://github.com/Netatalk/netatalk/commit/4a671e56e9e8448e8f11b1dd4654780cdad0ad4f
> Use BSD extension strlcpy/strlcat/snprintf to manage buffer size

- bin/getzones/getzones.c
Having said I didn't have time to investigate issue #2050, I decided to investigate it rather than sleep.  This PR appears to fix it.
From reading the definition of atp_open(), it looks like passing NULL to this is the intended idiomatic "bind to any address" syntax.
> getzones: do not attempt to bind to the address we're also going to send packets to

- etc/afpd/main.c
- etc/cnid_dbd/cmd_dbd_scanvol.c
- etc/cnid_dbd/cnid_metad.c
- etc/cnid_dbd/main.c
- etc/netatalk/netatalk.c
- include/atalk/util.h
- libatalk/util/cnid.c
- libatalk/util/unix.c
Depending on context, either bail out or continue when the chdir call fails.
Also removing branches within daemonize() that bypass chdir and closing of file descriptors, which weren't used anywhere.
> Handle errors in f|chdir() and remove unused daemonize() params

- libatalk/util/getiface.c
Fix headers’ order to avoid build error on some macOS versions.
> getiface.c: fix headers order for Apple

- libatalk/vfs/ea_sys.c
Do copy the Netatalk private EA during FPCopyFile calls. This was preventing the `ad cp` tool from copying vital information like FinderInfo. There is code elsewhere to update the CNID information in the newly created file. Fixes #2025.
> Fix ad cp loss of FinderInfo

- libatalk/vfs/ea_sys.c
Right now a client can still delete the `org.netatalk.Metadata` extended attribute using `xattr -d`. Clients should have no access to this data at all as it is used exclusively by the Netatalk server for storing its metadata.
In addition, adjust `sys_set_ea()` to silently fail if a client attempts to copy a file with a `org.netatalk.Metadata` EA attached to it from a local machine to the server. Right now it will abort file copies if this EA is present and macOS does not provide a descriptive error as to why. This should fix the problems discussed in #2000.
> Apply additional hardening to the Netatalk Metadata EA handling

- bin/ad/ad_mv.c
- bin/ad/ad_util.c
Adds back the missing slash in the path so lstat check doesn't fail and throw error. Fixes #2049
> Fix for CNID error with ad mv utility

- .github/workflows/build.yml
The vmactions project has a 1.1.9 release available now
> GitHub CI: Bump vmactions runner to FreeBSD 13.5

- bin/misc/fce.c
- bin/misc/meson.build
- doc/manpages/man1/afptest.1.md
- doc/manpages/man1/meson.build
Among other things, this addresses the buffer overflow reported and demonstrated by hzshang in [SourceForge bug 671](https://sourceforge.net/p/netatalk/bugs/671/)
- Add -p option for setting custom port
- Strengthen validation of input data to avoid buffer overflows when recieved malformed datagrams
- Rename binary to fce_listen and install it
- Cover documentation in the afptest man page
- Consolidate misc binary dependencies
> Improve and harden the FCE listener app

- SECURITY.md
Since minor feature versions should have a more or less clear cut migration path, I propose that we support only the two latest minor release versions with security patches: The second to last which is considered very stable, and the latest which should be stable but may have some kinks that's blocking some people from upgrading.
This prevents a long tail of arguably redundant support for old minor release versions.
> Update SECURITY.md with minor version policy

- config/afp.conf.in
The commented-out volume section examples now use the volume name option for case-sensitive names, while simplifying the section names for illustration.
> Update afp.conf examples with new volume name scheme

- config/meson.build
- meson_options.txt
New option -Dwith-statedir-creation which is true by default. Set this to false if you don't want the built system to create the @localstatedir@/netatalk/CNID dir structure. This obviously also skips the installation of the
CNID README file.
This important for f.e. NixOS packaging where the package script itself will prepare the file system, including the localstatedir for CNID databases and server signature files.
> meson: Introduce option for controlling state dir creation

- config/meson.build
- meson_options.txt
The new -Dwith-cups-pap-backend boolean option, default true, controls whether to install the pap backend for CUPS or not. This is handy when you can't or won't install configuration files for other libraries on the system.
In addition, the new -Dwith-cups-libdir-path which takes a path defines the root path where CUPS library files are kept, used to install the pap backend into a cups/backend subdir.
> meson: Option for controlling CUPS libdir path prefix and pap backend

- libatalk/unicode/meson.build
The build system will attempt to build the unicode static library before generating some of the source code files used for the target. This is normally not a problem since we bundle pre-built sources. But in some packaging environments (notably Debian) we strip out the pre-built sources and rely on the source generation logic.
This fix reverses the sequence of those two actions.
> meson: Generate Unicode lookup table sources before using them

- contrib/webmin_module/index.cgi
Avoid having the list items jump around on every reload, due to Perl hashes being unsorted.
> webmin: Sort lists of index page items in alphabetical order

- contrib/shell_utils/docker-entrypoint.sh
Brings back the notice that atalkd takes a good while to start up that fell off when rewriting the script to sh
> docker: Tweak startup messages for DDP services

- include/atalk/bstrlib.h
- libatalk/bstring/bstrlib.c
This brings API consistency with bgets which was renamed to bgetstring long time ago in our fork of bstrlib
No netatalk module currently calls bgetsa so this is just a preemptive maintainability fix
> bstring: Rename bgetsa function to bgetstreama

- doc/manpages/man5/afp_signature.conf.5.md
- doc/manpages/man5/afp_voluuid.conf.5.md
- doc/po/afp_signature.conf.5.md.ja.po
- doc/po/afp_voluuid.conf.5.md.ja.po
This makes both the afp_signature.conf and afp_voluuid.conf man pages read and look better
These particular man pages had consistently awkward grammar and syntax
> docs: Improve grammar and layout in signature and UUID man pages

- .github/workflows/build.yml
Bumping the workflow job to the latest vmactions release and replacing tracker3 dependency with localsearch
> GitHub CI: FreeBSD has migrated from tracker to localsearch

- test/testsuite/FPGetACL.c
One of the (only?) changes to AFP3.4 was changing the error sent when an extended attribute could not be found to AFPERR_NOITEM from AFPERR_MISC. This updates the testsuite to reflect that change.
> testsuite: Fix test399() to work with AFP3.4

- test/testsuite/specs.h
Refactor and add error logging to EXPECT_FAIL macro to make debugging failures easier
> testsuite: Refactor and add verbose error output to EXPECT_FAIL macro

- .github/workflows/build.yml
The vmactions project has been better at not breaking things lately, so let's try locking to the latest v1 runners for a while and see how it goes
> GitHub CI: Always use latest vmactions runners

- test/testsuite/FPGetACL.c
- test/testsuite/specs.h
This removes the EXPECT_FAIL macro only used in this single test and harmonizes the way all tests in the suite checks AFP return code
> testsuite: Use common pattern for validating error code in test432

- .github/workflows/containers.yml
- testsuite_deb.Dockerfile
The Debian testsuite container was still using the Alpine dockerfile. This was a copy paste mistake when originally configuring this workflow
This changeset also touches up the Debian testsuite container, and uses stronger and longer test user passwords.
> GitHub CI: Actually use Debian Dockerfile for Debian test container

- test/testsuite/afparg.c
- test/testsuite/afphelper.c
- test/testsuite/lantest.c
- test/testsuite/logintest.c
- test/testsuite/spectest.c
- test/testsuite/speedtest.c
- test/testsuite/test.h
In addition to failed and untested tests, print a list of skipped tests
At the same time, tweak test report labels to clarify the meaning of each test status
> testsuite: Print a summary of skipped tests at end of spectest run

- test/testsuite/FPGetSessionToken.c
Both the condition and skip reason were set incorrectly, which made it being skipped on AFP 3.1
> testsuite: Run test221 with AFP 3.1 or later

- test/testsuite/afpcli.c
- test/testsuite/afpclient.h
- test/testsuite/afpcmd.c
- test/testsuite/test.h
Use consistent data type for DSI status codes, namely unsigned int
Also removes a handful of unused function declarations
> testsuite: Use matching return value types for DSI status codes

- .github/workflows/build.yml
- meson_options.txt
The pap backend for CUPS modifies a 3rd party library which is not netatalk or the core system.
Certain OSes and package managers have policies against one package modifying the configuration of another package.
Notably NixOS.
This change makes it so that the pap CUPS backend has to be enabled explicitly at compile time to be installed.
> meson: Do not install the pap CUPS backend by default

- doc/manpages/man5/afp.conf.5.md
- doc/po/afp.conf.5.md.ja.po
- libatalk/util/netatalk_conf.c
This brings back the behavior of netatalk 4.1 and earlier
Updating documentation to reflect the changed behavior
> Fall back to no EA rather than AD when the EA support check fails

- .github/workflows/build.yml
The testsuite has seen improved functionality and portability recently so it makes more sense now to build it everywhere
> GitHub CI: Build the testsuite on all OSes

- INSTALL.md
- doc/manual/Installation.md
- doc/po/Installation.md.ja.po
The INSTALL.md file has gotten much better at covering the basics of using git, meson, and understand dependencies. Therefore I now remove some redundant information on this topic from the Installation chapter in the html manual.
Conceptually, the Installation chapter is now meant to give the high level overview, plus an in-depth discussion on the purpose of each dependent library.
Conversely, INSTALL.md can focus on the mechanics of working with the source code.
> docs: Reduce overlap between install chapter and install readme

- .github/workflows/build.yml
The MySQL client library has gotten a version bump from 8.4 to 9.1 in the FreeBSD ports repo
> GitHub CI: Build on FreeBSD with the latest mysql91-client

- test/testsuite/afparg.c
- test/testsuite/lantest.c
- test/testsuite/logintest.c
- test/testsuite/spectest.c
- test/testsuite/speedtest.c
Rather than outputting obscure errors, print the helpful summary of available parameters
> testsuite: Print usage helptext when running test binaries without params

- libatalk/util/netatalk_conf.c
When migrating to the shared iniparser library, this one afp.conf option wasn't carried over to the new API calls. This made the mysql CNID backend non-functional.
> libatalk: Restore cnid mysql pw option that had fallen off

- .github/workflows/containers.yml
While the AFP test password is for a throwaway test container, using the GitHub secret context makes me sleep better at night
> GitHub CI: Use secret context for secure AFP test password handling

- doc/manpages/man5/afp.conf.5.md
- doc/po/afp.conf.5.md.ja.po
We no longer do variable substitution in the Markup docs
Also, make backend descriptions more crisp
> docs: Touch up afp.conf man page description of cnid schemes

- test/testsuite/FPAddAPPL.c
- test/testsuite/FPAddIcon.c
- test/testsuite/FPCopyFile.c
- test/testsuite/FPGetAPPL.c
- test/testsuite/FPGetIcon.c
- test/testsuite/FPGetIconInfo.c
- test/testsuite/FPRemoveAPPL.c
- test/testsuite/FPSetDirParms.c
This adds tests failing with the mysql CNID backend to the Exclude bucket
The reasons for failure has not yet been indentified, so this is just an acitivity for unblocking running these tests with mysql in CI
The Exclude bucket is activated when tests are run with the `-x` parameter
> testsuite: Skip tests not compatible with the mysql backend

- .github/workflows/containers.yml
- DOCKER.md
- Dockerfile
- contrib/shell_utils/docker-entrypoint.sh
- testsuite_alp.Dockerfile
Added the ability to choose an arbitrary CNID backend in the
Docker entry script, with special case handling for the mysql backend
Updated the container CI workflow to run the tier 1 spectests
in with the mysql backend and a MariaDB database container
Usage instructions added to DOCKER.md
> docker: Support for the mysql CNID backend in container

- .github/workflows/containers.yml
- DOCKER.md
- contrib/shell_utils/docker-entrypoint.sh
Rather than a simple dry run, execute the tier 1 spectest against the netatalk production container
Also turns the Alpine mysql job into a test against the production container
> GitHub CI: Run the spectest against the production netatalk container

- .github/workflows/containers.yml
- DOCKER.md
- config/extmap.conf
- contrib/shell_utils/docker-entrypoint.sh
- test/testsuite/FPGetFileDirParms.c
Use full extension mapping consistently for all CI jobs
Remove the extmap tests from the Exclude bucket
Flesh out the description of extmap.conf
> docker: Introduce an AFP_EXTMAP option to enable extension mapping

- .github/workflows/containers.yml
- contrib/shell_utils/docker-entrypoint.sh
What was previously hard coded, this allows you to more dynamically specify when to skip the Exclude bucket in the testsuite through the CI job definitions
> docker: Introduce AFP_EXCLUDE_TESTS flag for triggering test exclusion

- contrib/webmin_module/edit_vol_section.cgi
- contrib/webmin_module/index.cgi
- contrib/webmin_module/lang/en
- contrib/webmin_module/netatalk-lib.pl
Make it possible to actually edit volume preset names, rather than adding a useless preset name option to afp.conf (regression bug in 4.2.0)
When listing up volumes on the index page, only list volume names and not section names
> webmin: Correct handling of volume and volume preset names

- contrib/webmin_module/edit_global_section.cgi
Need to filter out uams_randnum.so in the standard UAMs regex not to treat it simultaneously as a standard and non-standard UAM
> webmin: Treat uams_randnum.so as a standard UAM

- .github/workflows/containers.yml
- DOCKER.md
- Dockerfile
- contrib/shell_utils/config_watch.sh
- contrib/shell_utils/netatalk_container_entrypoint.sh
- contrib/shell_utils/webmin_container_entrypoint.sh
- testsuite_alp.Dockerfile
- testsuite_deb.Dockerfile
- webmin_module.Dockerfile
Introduce a new netatalk_webmin_module container which runs an isolated instance of webmin with the netatalk module
In the main netatalk container, newly introduced config file polling will pick up on any changes, since we cannot control the daemons directly from the webmin container
This changes the config file dir in the container to /etc/netatalk (from /usr/local/etc )
> docker: Containerized netatalk webmin module

- DOCKER.md
- contrib/shell_utils/netatalk_container_entrypoint.sh
Setting the new DISABLE_SPOTLIGHT env variable to non-zero will set spotlight = no in afp.conf
Additionally, we explicitly set appletalk = no when no atalkd interface is defined
> docker: Introduce DISABLE_SPOTLIGHT flag for turning off indexing

- contrib/webmin_module/config.in
- contrib/webmin_module/config.info
- contrib/webmin_module/index.cgi
- webmin_module.Dockerfile
This is mainly for the purposes of removing the
start/stop/restart controls from view when webmin
is running inside of a container
We enable this option on the fly when building
the webmin container for netatalk
> webmin: Option for hiding service controls

- INSTALL.md
- doc/manpages/meson.build
- doc/manual/Configuration.md
- doc/manual/Installation.md
- doc/manual/Upgrading.md
- doc/manual/meson.build
- doc/meson.build
- doc/po/Configuration.md.ja.po
- doc/po/Installation.md.ja.po
- doc/po/Upgrading.md.ja.po
- meson.build
When using cmark, filter the output to enclose table markdown in pre tags to get an acceptable html layout
The resulting tables aren't ideal for readability, but I would argue that they are perfectly serviceable
> meson: Make it possible to generate the html manual with plain cmark

- doc/manual/_Navlinks_atalk.md
- doc/manual/meson.build
- doc/meson.build
- doc/po/_Navlinks.md.ja.po
- doc/po/_Navlinks_atalk.md.ja.po
- doc/po/_Sidebar.md.ja.po
- doc/po4a.cfg
- doc/translated/ja/meson.build
The localized html manual was missing the embedded navlinks, as well at the index and license pages
Additionally, port over the support for building html pages with pandoc and cmark
For good measure, allow for hiding the AppleTalk link in the navlinks when netatalk is built without AppleTalk support
> meson: Properly build the localized html manual

- libatalk/adouble/ad_conv.c
Store the return value of bdata() in a temporary variable to make the NULL check more predictable to the static analyzer
This bypasses a persistent compiler warning on Ubuntu 24.04
> libatalk: Tweak NULL check logic to appease gcc 13.3 on Ubuntu

- .github/workflows/build.yml
In order to test generation of the documentation on Solaris, we curl the latest release cmark tarball, then build and install it
Note that I also played around with cmark-gfm on Solaris, however problem number one is that it takes many times longer to build (cmark takes a few seconds, while cmark-gfm takes closer to a minute) which makes it less suitable for a CI job. Secondly, I couldn't get it to find the shared library libcmark-gfm-extensions.so after installing, which could be an easy fix but I didn't want to mess with the Solaris dynamic linker any more.
> GitHub CI: Build cmark from source on Solaris

- .github/workflows/build.yml
- test/testsuite/FPGetForkParms.c
- test/testsuite/encoding_test.c
- test/testsuite/logintest.c
The STATIC macro can be used as a global compile time flag to compile all test functions as static if needed; this is disabled by default, because dynamic functions allow us to cherry pick functions for execution
Also updates the GitHub build jobs to unblock the pipeline
> testsuite: Consistently use STATIC macro on test funcions

- libatalk/cnid/mysql/cnid_mysql.c
Previously, the MySQL query errors were all logged at info level, which led to very noisy logs because this module uses duplicate entry error handling as a common pattern
Also, additional debug level logging for volume entry duplication
> libatalk: MySQL query error log level is dropped to debug

- distrib/initscripts/openrc.netatalk.in
In addition to a netatalk reload command that sends a SIGHUP signal to netatalk, we now have a soft dependence on firewall
These improvements are borrowed from the Alpine Linux OpenRC script created by @jirutka
https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/netatalk/netatalk.initd
Additionally, we make atalkd and avahi-client soft dependencies to make it easier to run netatalk standalone when AppleTalk or Avahi are not required
> initscripts: Improvements to the OpenRC netatalk init script

- .github/workflows/build.yml
- contrib/a2boot/a2boot.c
- contrib/macipgw/main.c
- contrib/timelord/timelord.c
- etc/atalkd/main.c
- etc/cnid_dbd/cnid_metad.c
- etc/papd/main.c
The various netatalk daemons inconsistently returned 0 (success) and non-0 exit codes; this standardizes on running the daemon with -V as a non-failure
> Consistently return exit code 0 after showing version info

- bin/misc/meson.build
- meson.build
OpenWrt build for 4.2.2 (and 4.2.1) fails if iconv is enabled as the dependency is not present for some of the bin/misc artefacts.
Also picked up change suggested here: https://github.com/Netatalk/netatalk/issues/1921
> netatalk: fix iconv dependency build issue

- etc/afpd/afp_options.c
The `optind` variable is global and needs to be reset to `1` with each call to `getopt()`. Fixes #2150.
> Ensure that `optind` is reset on each call to afp_options_parse_cmdline()

- doc/manpages/man5/afp.conf.5.md
- doc/po/afp.conf.5.md.ja.po
- libatalk/util/netatalk_conf.c
This puts the appletalk afp.conf read behind the NO_DDP flag and updates documentation
> Read the appletalk option only when netatalk built with DDP

- .github/workflows/build.yml
This reverts commit a29fbb63d93d342a0d4014ec905bd359b99960a3.
We had this temporarily disabled because the official Arch container image had a broken dependency tree for a few weeks.
> Revert "GitHub CI: Temporarily build on Arch Linux without Spotlight"

- doc/manpages/man8/afpd.8.md
- doc/manpages/man8/macipgw.8.md
- doc/po/afpd.8.md.ja.po
- doc/po/macipgw.8.md.ja.po
Overhaul grammar and syntax in afpd man page, and remove reference to /usr/etc in macipgw man page
Addresses issues flagged by Debian's linter
> docs: Improve afpd and macipgw man pages

- bin/nbp/nbplkup.c
- doc/manpages/man1/nbp.1.md
This PR modifies nbplkup to provide output in a format that's fixed enough for a script to easily parse.  On its way to doing this, it normalises whitespace and factors out some of the side-effect-y if() conditions - the latter of which is admittedly a purely personal preference.
Tested locally but only on NetBSD; not that anything in here should be OS-specific.
Side note: does netatalk target any specific revision of the C standard?  I've introduced a reference to stdbool.h here, in the interests of striking out for sanity.
> nbplkup: provide for script-friendly output (and some code cleanup)

- bin/nbp/nbplkup.c
- doc/manpages/man1/nbp.1.md
- include/atalk/nbp.h
- libatalk/nbp/nbp_lkup.c
The intent of this PR is to allow nbplkup to probe NBP speakers that are not the local host.
To do this, it adds two features:
- A -D option, which specifies the address of the remote NBP speaker to direct queries to
- -f and -l options, which override the default BrRq request type and enable either LkUp or FwdReqs to be generated.
While I was passing I also ran astyle on libatalk/nbp/nbp_lkup.c - hope this doesn't interfere with your coding style work.
Tested only on NetBSD, but again, I can't see any reason this wouldn't be portable.
> nbplkup: allow specification of NBP operation and of destination address

- bin/getzones/getzones.c
- bin/nbp/nbplkup.c
- bin/pap/pap.c
Just a couple of small fixups not really connected to anything else but which were trivial to fix while I was passing
1. A slight tidying of includes and formatting.
2. While `#define FUCKED` gave me a real surge of empathy for whoever wrote that code, it is in fact redundant, since it looks like it's been permanently defined for the last 25 years; I think we can get rid of the ifdefs now.
> Small code quality fixups

- contrib/a2boot/a2boot.c
- contrib/timelord/timelord.c
- etc/afpd/auth.c
- etc/afpd/catsearch.c
- etc/afpd/desktop.c
- etc/afpd/directory.c
- etc/afpd/enumerate.c
- etc/afpd/file.c
- etc/papd/lp.c
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_dhx_passwd.c
- etc/uams/uams_randnum.c
- include/atalk/directory.h
- include/atalk/ea.h
- include/atalk/spotlight.h
- libatalk/cnid/last/cnid_last.c
- libatalk/dsi/dsi_getstat.c
- libatalk/dsi/dsi_opensess.c
- libatalk/util/netatalk_conf.c
- test/testsuite/FPByteRangeLock.c
- test/testsuite/FPDisconnectOldSession.c
- test/testsuite/FPGetACL.c
- test/testsuite/FPResolveID.c
- test/testsuite/T2_FPByteRangeLock.c
- test/testsuite/afpcli.c
Rather than keeping disabled code in comments, put them inside `#if 0` preprocessor blocks so that they can be easily found and eliminated at a later time
In the case of debug logging, put this code behind the EBUG compiler flag instead
This also includes some other minor fixes, such as clean up of trailing code comments, and modernization of syntax
> Revive commented out code, or put them in #if 0 blocks

- bin/getzones/getzones.c
- doc/manpages/man1/getzones.1.md
- doc/manpages/man1/nbp.1.md
- include/atalk/zip.h
The intent of this PR is to get getzones to the point it can meaningfully be used to probe ZIP with more query types than just the ATP ones.  I only ran astyle at the end, because my brain was addled, so apologies for any stylistic infelicities in earlier commits.
Most of the commit messages hopefully speak for themselves, but perhaps the strdup fix could do with a little discussion even though the code is tiny and trivial.  Essentially, the code as it is cannot work, because strdup will run off the end of the pascal string and just chunter off into memory for who knows how long.  Hooray.  However, this only ever is triggered when string conversion fails, and I'm not sure it realistically does fail except in circumstances where the fallback would also fail.  So in this PR I haven't …
> getzones: allow all ZIP query types to be generated (and sundry other enhancements)

- bin/getzones/getzones.c
This is to appease Apple clang 17.0.0 on macOS
> getzones: Consistently use uint8_t buffer data type

- test/testsuite/afparg.c
The chevrons aren't standard C syntax, and their inclusion outside of quotation marks confuse astyle in certain circumstances
> Remove chevrons from placeholder tokens in macro

- bin/meson.build
- bin/rtmpqry/meson.build
- bin/rtmpqry/rtmpqry.c
- doc/manpages/man1/meson.build
- doc/manpages/man1/rtmpqry.1.md
- include/atalk/rtmp.h
This PR introduces rtmpqry, a utility to allow querying of what neighbouring routers are advertising using RTMP.  The man page and the commit messages should hopefully be enough to give you an idea of what's going on here; essentially, we can solicit an RTMP data dump using an RTMP Route Data Request, or we can ask for network metadata through an RTMP Query.  These are very confusingly named, and I've done my best to add clarity to the distinction where possible, but there's only so much can be done.
> Add rtmpqry utility to allow querying of routing information from neighbour routers

- doc/po4a.cfg
The newly added rtmpqry.1.md documentation file needs to be added to po4a.cfg to be picked up for translation
> Flag rtmpqry man page for localization in po4a.cfg

- bin/rtmpqry/rtmpqry.c
The void return type for main() causes a hard compilation failure on Apple clang 17.0.0
> rtmpqry: Apple clang requires an int return type for main()

- .github/workflows/build.yml
The Oracle Solaris 11.4.81 CBE release now ships a recent enough meson package to be able to build netatalk
release notes:
https://blogs.oracle.com/solaris/post/whats-new-in-the-oracle-solaris-11481-cbe-release
This changeset also disables PAM for Solaris for the time being since it won’t build on this CBE. Will be followed up in an issue ticket.
> GitHub CI: Use native meson to build on Solaris

- bin/rtmpqry/rtmpqry.c
Should address your note on #2181.  Not sure it really *matters* here hugely, since it's a command line tool with a very finite runtime, but we should be neat and not put snares in future maintainers' paths.  (I think this same laxness is perpetrated in some of the other CLI tools; I'll check as I have the energy)
> Fix missing 'free' of remote_addr in rtmpqry

- doc/manual/_Sidebar.md
Newly added man pages needs to be put in the proper spot on this index sidebar
> docs: List the rtmpqry.1 man page in the html manual index

- .github/workflows/build.yml
- meson.build
- meson_options.txt
Before, the build system would always attempt to detect an appropriate brew_prefix and then add Homebrew include and lib search paths
This causes issues when using Homebrew on Linux and attempt to build Netatalk on the side, or when building MacPorts packages on macOS
Therefore, Homebrew builds are now opt-in with the new -Dwith-homebrew boolean meson option
> meson: Build and link with Homebrew libraries is now opt-in

- .github/workflows/build.yml
- etc/uams/uams_dhx2_pam.c
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_pam.c
- meson.build
- meson_config.h
The PAM implementations of Solaris vs. other OSes differ slightly which we need to accommodate for
Namely, the `struct pam_message` member of pam_conv isn't declared with const on Solaris
This also updates the GitHub CI configuration to use native Solaris native meson for building
> [4.2] uams: Check for const pam_message member of pam_conv

- .github/workflows/build.yml
- meson.build
- meson_options.txt
Before, the build system would always attempt to detect an appropriate brew_prefix and then add Homebrew include and lib search paths
This causes issues when using Homebrew on Linux and attempt to build Netatalk on the side, or when building MacPorts packages on macOS
Therefore, Homebrew builds are now opt-in with the new -Dwith-homebrew boolean meson option
> [4.2] meson: Build and link with Homebrew libraries is now opt-in

- .github/workflows/build.yml
- etc/uams/uams_dhx2_pam.c
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_pam.c
- meson.build
- meson_config.h
The PAM implementations of Solaris vs. other OSes differ slightly which we need to accommodate for
Namely, the `struct pam_message` member of pam_conv isn't declared with const on Solaris
> uams: Check for const pam_message member of pam_conv

- etc/spotlight/sparql_parser.y
Rather than casting NULL as a pointer, use the idiomatic implicit comparison in the control structure
Before, compiling on Solaris with gcc 14.2.0 led to:
```
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /root/netatalk/build
ninja: Entering directory `/root/netatalk/build'
[93/366] Compiling C object etc/spotlight/liblibspotlight.a.p/sparql_parser.c.o
sparql_parser.y: In function ‘isodate2unix’:
sparql_parser.y:156:48: warning: comparison between pointer and integer
[134/366] Compiling C object etc/spotlight/srp.p/sparql_parser.c.o
sparql_parser.y: In function ‘isodate2unix’:
sparql_parser.y:156:48: warning: comparison between pointer and integer
[366/366] Linking target test/afpd/afpdtest
```
> spotlight: Use idiomatic NULL check to avoid compiler warning on Solaris

- DOCKER.md
- docker-compose.yml
Named volumes is arguably more consistent than anonymous volumes for a file sharing application
Credits to phlagios for the report / suggestion
Also changing to using a remote registry by default in the docker compose example
> docker: Use named volumes in docker compose examples

- meson.build
When brew_prefix is undefined, the bison program check would lead to invalid syntax on macOS
> meson: Gracefully fall back in bison program check on macOS

- .editorconfig
- .github/workflows/test.yml
- contrib/scripts/codefmt.sh
- contrib/scripts/fce_ev_script.sh
- contrib/scripts/netatalk_container_entrypoint.sh
- contrib/scripts/webmin_container_entrypoint.sh
- doc/manpages/make_man.sh
- test/afpd/test.sh
Create an .editorconfig code styling config file with shfmt compatible directives, while adding support for shell formatting in the codefmt.sh shell script
The codefmt.sh script has been refactored to be POSIX compatible, which enables us to enforce POSIX standards on all shell scripts in this repo
Finally, run shfmt with the new rules against all shell scripts in the repo to beautify them
These formatting rules are now enforced in the Tests CI workflow
> Beautify shell scripts with shfmt

- .github/workflows/build.yml
This is to turn on the Arch build job again once they've recovered their dependency tree
> GitHub CI: Enable Arch Linux job again

- DEVELOPER.md
- INSTALL.md
- doc/manual/AppleTalk.md
- Move info on AppleTalk protocols from the DEVELOPER readme to the html manual
- Opening paragraphs in the DEVELOPER readme get a clearer intention
- Sample C code in DEVELOPER readme should follow our own style guide
- Call out which C compilers are recommended in INSTALL readme
> docs: Improve AppleTalk manual and developer readmes

- DEVELOPER.md
Restore correct indentation which was lost when forward porting AppleTalk stuff to the main branch
> [4.2] Correct ASCII art network stack diagram

- COPYRIGHT
In the netatalk v1.3.3 distribution, the COPYRIGHT header had the University of Michigan address immediately following the original copyright blurb
In subsequent releases, it got pushed further and further down by other copyright holders, which arguably breaks the context of the address
Also, all code copyrighted by Sun Microsystems was removed with netatalk v3.0 (everything under sys/solaris) so the Sun copyright blurb is no longer relevant
> Restore order of original copyright paragraphs, and remove Sun blurb

- NEWS.md
The very earliest version history records refer to the previous version in the headings for the paragraph with the changelogs
This changes them so that they refer to the version at hand instead, to make it easier to read the historical version history
> Refer to version at hand in version history

- test/testsuite/meson.build
The dynamic linker on macOS couldn't find libatalk under certain circumstances when rpaths weren't explicitly set
> [4.2] meson: Define library rpath for testsuite executables

- .github/workflows/containers.yml
Align with the naming in the entrypoint script
FTR, in the main branch I make the inverse change and rename the variable to SHARE_NAME2 instead to match the naming convention elsewhere, however I don't want to make a breaking change in the stable branch
> [4.2] GitHub CI: Use correct 2nd volume name env variable

- .github/workflows/build.yml
- .github/workflows/containers.yml
- .github/workflows/scorecard.yml
- .github/workflows/static.yml
- .github/workflows/test.yml
By default, we should only allow read-only access to the jobs
This also cleans up the yaml structure a bit and removes redundant comments
> GitHub CI: Use read-only workflow permissions to the greatest degree

- .github/workflows/scorecard.yml
Straggler github action that needs to be locked to a hash
> GitHub CI: Use digest hash for github/codeql-action/upload-sarif action

- .github/workflows/containers.yml
Refactored all of the container jobs to pull the current Actions sha tag rather than the latest tag, for increased resiliance of the jobs
This involved rewriting the jobs as regular 'run' expressions rather than the 'uses' shorthand
We switch to full hashes instead of the shortened 8 char ones for image tags pushed to the GitHub registry
> GitHub CI: Use a specific sha to pull test containers

- .github/workflows/test.yml
Running the Tests jobs is fairly cheap, and may reveal issues with any kind of file
> GitHub CI: Always run the Tests workflow on all file changes

- .github/workflows/build.yml
- .github/workflows/containers.yml
- Dockerfile
- INSTALL.md
- contrib/webmin_module/edit_vol_section.cgi
- doc/manpages/man5/afp.conf.5.md
- doc/manual/Configuration.md
- doc/manual/Installation.md
- etc/afpd/afp_options.c
- etc/cnid_dbd/cmd_dbd.c
- etc/cnid_dbd/meson.build
- include/atalk/cnid_sqlite_private.h
- libatalk/cnid/cnid.c
- libatalk/cnid/cnid_init.c
- libatalk/cnid/meson.build
- libatalk/cnid/sqlite/cnid_sqlite.c
- libatalk/cnid/sqlite/meson.build
- meson.build
- meson_config.h
- meson_options.txt
- testsuite_alp.Dockerfile
- testsuite_deb.Dockerfile
Based on the MySQL CNID backend by Ralph Boehme, and proof-of-concept code by Christopher Kobayashi originally from the now-defunct netatalk-classic project
The meson build system will build the sqlite backend when the sqlite3 dependency is found, but this can also be controlled with the -Dwith-cnid-backends option
Put 'cnid scheme = sqlite' in the afp.conf volume section where you want to use the new backend
Similarly to dbd (BerkeleyDB) this backend is zero-configuration that stores its database in a file under /var/netatalk/CNID/[volumedir]
Please note that this is considered EXPERIMENTAL code at this point, so please proceed with caution and keep backups of any sensitive data on your volumes
Worth noting is a fundamental limitation of SQLite is that is supports a single database write …
> SQLite CNID backend

- .github/workflows/containers.yml
We were mistakenly depending on the Debian testsuite container while we actually used the Alpine one
> GitHub CI: Select the correct testsuite container for the job

- libatalk/cnid/sqlite/cnid_sqlite.c
As per the SQLite docs, NORMAL synchronous pragma is a recommended companion for WAL journaling mode
Also lowers the global SQLite busy timeout from 5s to 2s. It was set high while debugging a write locking issue and I forgot to adjust it again.
> cnid: Turn on normal synchronous pragma for the sqlite backend

- etc/papd/comment.h
- etc/papd/headers.c
- etc/papd/queries.c
- Update all handler function pointers in struct papd_comment and struct genquery to use full prototypes.
- Replace K&R-style and implicit function declarations with modern C prototypes.
- Flag parameter in cq_end() with unused macro
> papd: Make handler function pointers and definitions C11/C23-compliant

- test/testsuite/FPRead.c
- test/testsuite/afparg.c
- test/testsuite/lantest.c
- test/testsuite/logintest.c
- test/testsuite/spectest.c
- test/testsuite/speedtest.c
The testsuite supports only DSI protocol, so remove the global variables and empty conditionals for the global Proto variable
This code was likely meant as a stub for DDP protocol support in the testsuite
> testsuite: Remove obsolete protocol option stubs

- doc/manual/AppleTalk.md
Remove some redundant information to make the first section read a bit better
> docs: Touch up the descriptions of AppleTalk protocols

- INSTALL.md
- bin/afppasswd/meson.build
- bin/meson.build
- doc/manpages/man5/afp.conf.5.md
- doc/manpages/man8/cnid_dbd.8.md
- doc/manpages/man8/cnid_metad.8.md
- doc/manpages/man8/meson.build
- doc/manual/Configuration.md
- doc/manual/Installation.md
- etc/afpd/afp_options.c
- etc/netatalk/netatalk.c
- etc/uams/meson.build
- libatalk/cnid/meson.build
- meson.build
- meson_options.txt
- test/meson.build
This changeset modifies both the build system and the netatalk executable to remove the hard dependency on Berkeley DB.
Regarding the build system piece: in the absence of a Berkeley DB library, it is now possible to build and use another CNID backend as the default. When the dbd backend is not built, we don't install the cnid_metad / cnid_dbd daemons or man pages.
In the netatalk controller daemon, when built without dbd support it will no longer attempt to launch the cnid_metad.
It introduces new logic for picking the default CNID backend which is more flexible, as well as printing the default backend in both the meson summary and in the output of afpd -V.
There is also surrounding refactoring of the build system for libgcrypt and the CNID backend libraries.
> Build and run netatalk without Berkeley DB

- libatalk/cnid/mysql/cnid_mysql.c
Addresses a range of code quality and convention issues, in part aligning with improvements in the sqlite backend
- Use preformatted SQL strings in execute function rather than dynamic formatting
- The mysql CNID module uses functions declared in unix.h, notable become_root() so let's include it explicitly
- Use standard while loop instead of goto statement
- Explicit type casting, remove unused variable, merge if statements, etc.
> cnid: Make the mysql CNID backend a bit more resilient

- .github/workflows/build.yml
- .github/workflows/code_analysis.yml
- .github/workflows/container_runs.yml
- .github/workflows/containers.yml
A few tweaks to the workflows so that only non-privileged jobs are triggered directly by the PR, with the rest triggering indirectly to grant them access to secrets
Run the container test runs only on container build success: Only a successful container build workflow will result in usable containers
Containers workflow triggered off of the Tests workflow: Also loosens up the trigger criteria for other workflows
> GitHub CI: Arrange for all privileged jobs to run as workflow triggers

- .github/workflows/build.yml
- INSTALL.md
- doc/manual/Installation.md
- etc/afpd/spotlight.c
- etc/netatalk/netatalk.c
- include/atalk/spotlight.h
- meson.build
- meson_config.h
- meson_options.txt
- testsuite_deb.Dockerfile
Tighten up dependency checks for LocalSearch and TinySPARQL in meson
When detected, use TinySPARQL header and LocalSearch API, rather than the deprecated Tracker backward compatibility fallbacks
This fixes a bug where LocalSearch failed to register a D-Bus service using a too old D-Bus name (pre-Tracker3)
At the same time, remove compatibility checks and code for Tracker older than v3, which have been deprecated since 2020
The obsoleted meson options -Dwith-tracker-install-prefix and -Dwith-tracker-prefix have been removed as well
> Properly support LocalSearch and remove Tracker < v3 support

- .github/workflows/container_runs.yml
This was a missing update after rearranging the workflow triggers earlier (cumbersome that you cannot test workflow triggers in a PR)
> GitHub CI: Trigger the Container Test Runs workflow off the correct workflow

- .github/workflows/code_analysis.yml
When using the indirect workflow trigger, the SonarQube static analysis wrapper doesn't seem to work properly, not picking up the latest code and therefore not doing any static analysis since the cache is used 100%
So this brings back the previous behavior of triggering this workflow directly, but only for PRs originating from the project and not forks
> GitHub CI: Directly trigger SonarQube workflow again

- include/atalk/logger.h
- libatalk/util/logger.c
Use sequences of equals signs to separate code sections only at the top and reduce the bottom to closing the comment
This aligns the logger module code comment style with the rest of the codebase
But frankly, the triggering reason for this change is a bug in astyle 3.6.10 that triggers indentation style malfunction
https://gitlab.com/saalen/astyle/-/issues/92
> Reduce excessive code comment separators in logger module

- .github/workflows/build.yml
The previous bootstrap release 20240116 introduced conflicting libiconv headers into OmniOS leading to compilation errors in netatalk
> GitHub CI: Bump to SmartOS bootstrap 2024Q4 for OmniOS build

- etc/afpd/volume.c
- etc/netatalk/netatalk.c
- libatalk/adouble/ad_conv.c
- libatalk/adouble/ad_open.c
- libatalk/cnid/sqlite/cnid_sqlite.c
- libatalk/util/ftw.c
- libatalk/util/logger.c
- libatalk/util/unix.c
- meson.build
- test/testsuite/lantest.c
Consistently handle return values from non-void functions, and exit the function/program early with logging on failure
This appeases the -Wunused-result compiler flag
Also includes a small meson change to always link with glib when building POSIX ACLs, not just on Linux.
> Handle return codes from function calls consistently

- .github/workflows/code_analysis.yml
- .github/workflows/containers.yml
The previous attempt did not work in real life, so using a plain logic comparison this time
> GitHub CI: Use different strategy to skip jobs for dependabot

- Dockerfile
ACLs have proven flaky when in a container context, so since there arguably is little utility for ACLs within a docker deployment let's disable it for now
> docker: Build production container without ACL support

- .github/workflows/code_analysis.yml
Explicitly check for the type of event, plus both fork and dependabot checks twice
Hopefully it will work this time when merged to main
> GitHub CI: Use an even more explicit conditional for SonarQube job

- .github/ISSUE_TEMPLATE/bug_report.md
Update the GitHub bug report template to request afp.conf and other config file contents with their report
> We want configuration file data in our bug reports

- bin/ad/ad.h
- bin/ad/ad_cp.c
- bin/ad/ad_mv.c
- bin/ad/ad_rm.c
- bin/ad/ftw.c
- bin/ad/ftw.h
- bin/ad/meson.build
- etc/afpd/volume.c
- libatalk/util/meson.build
The file tree walker functions are only used narrowly in the ad binary, so let's move it out of the shared libatalk library to reduce bloat
Removes the ftw.h header file from a few source files where the symbols aren't used
At the same time, fix a handful of code smells and security hotspots reported by SonarQube
> Move ftw code from libatalk into the ad binary

- .github/workflows/build.yml
- .github/workflows/containers.yml
- meson.build
- testsuite_alp.Dockerfile
- testsuite_deb.Dockerfile
This PR contains a handful of minor tweaks to the container test environment:
- Have both a production and a test container run for the cnid:sqlite pattern on Alpine
- Build both Alpine and Debian test containers with the Spotlight stack (but not the production container)
- Remove red herring glib linking workaround for ACLs
- Remove trailing forward slash in NetBSD pkgsrc path
> Build test containers with Spotlight, and run sqlite tests with Alpine test container

- etc/spotlight/meson.build
Consolidating a single list of spotlight dependencies, while making the mysqlclient library conditional on building with mysql CNID backend support
> meson: Refactor spotlight dependencies

- test/testsuite/T2_FPGetFileDirParms.c
Use snprintf to write to buffer with enforced max length, and bail out if the operation isn't successful,
which should make gcc 13.3.0 on Ubuntu 24.04 happy
> testsuite: Prevent potential buffer overflow in FPGetFileDirParms test

- .dockerignore
- contrib/scripts/netatalk_container_entrypoint.sh
- doc/manpages/man1/afp_lantest.1.md
- doc/manpages/man1/afptest.1.md
- doc/manpages/man1/meson.build
- doc/manual/_Sidebar.md
- doc/po/afp_lantest.1.md.ja.po
- doc/po4a.cfg
- doc/translated/ja/meson.build
- test/testsuite/afphelper.c
- test/testsuite/lantest.c
- testsuite_alp.Dockerfile
Add dircache-focused performance tests and enhance statistical analysis with robustness improvements to afp_lantest
- Added 4 new cache performance tests (Tests 8-11): - TEST_CACHE_HITS: Directory cache efficiency testing - TEST_MIXED_CACHE_OPS: Cache lifecycle operations testing - TEST_DEEP_TRAVERSAL: Deep directory structure navigation - TEST_CACHE_VALIDATION: Cache validation efficiency testing
- New -C command-line flag: Run cache-focused tests only
- Enhanced analysis: Added standard deviation calculations with ± display format
- Robustness improvements: Enhanced memory allocation, pthread handling, buffer safety
- Bug fixes: Fixed array indexing, improved iteration tracking (off by one), enhanced error reporting (without debug mode)
- Code quality: Added math.h header, improved …
> testsuite: Add dircache-focused performance tests to afp_lantest

- contrib/scripts/netatalk_container_entrypoint.sh
- test/testsuite/speedtest.c
The -n option that defines how many times the speedtest shall run hasn't been functioning because of a typo in the optarg string
> testsuite: Fix the iterations option for afp_speedtest

- contrib/scripts/netatalk_container_entrypoint.sh
- test/testsuite/speedtest.c
This refactors the speedtest runner routine to use a table of function pointers to iterate over named tests
The -f parameter takes a comma separated list of tests
Numerous minor bugs and dead code are addressed as well
The test container will now run all speedtest tests 5 times
> testsuite: afp_speedtest takes comma separated list of tests

- test/testsuite/afphelper.c
- test/testsuite/logintest.c
- test/testsuite/specs.h
The afp_logintest has DSI session and Guest auth tests that are perfectly valid to test without username and password
Adds checks to the tests that require credentials that makes the runner skip them if none are available
> testsuite: Don't require username and password for afp_logintest

- contrib/scripts/netatalk_container_entrypoint.sh
In a previous refactoring, running the afppasswd tool got put behind the INSECURE_AUTH flag; this brings it back to the default configuration again to unblock Classic Mac OS usecases
> docker: Bring back the RandNum password creation by default

- .github/workflows/release.yml
Rather than relying on the Meson checksum generation, create both sha256 and sha512 checksums for the release tarball
> GitHub CI: Support sha256 and sha512 checksums in release workflow

- .github/workflows/release.yml
The webmin module has to be built separately, so creating a new step for this
> GitHub CI: Build and distribute webmin module tarball in release workflow

- .github/workflows/release.yml
Rather than attempting to read from the tag reference, use the workflow dispatch version string directly
> GitHub CI: Use tag from the workflow dispatch when determining version

- .github/workflows/containers.yml
- .github/workflows/release.yml
With this change, containers built in CI workflows are only tagged with the commit hash
This allows us to use ghcr.io for publishing of stable release containers
> GitHub CI: Tag only release containers with latest in ghcr.io

- .github/workflows/build.yml
- .github/workflows/code_analysis.yml
- .github/workflows/containers.yml
- .github/workflows/release.yml
- .github/workflows/scorecard.yml
- .github/workflows/static.yml
- .github/workflows/test.yml
- .yamlfmt.yaml
- contrib/scripts/codefmt.sh
Apply yaml formatting rules based on the [yamlfmt style guide](https://github.com/google/yamlfmt/blob/main/docs/config-file.md) with the following configuration:
```
formatter:
type: basic
eof_newline: true
include_document_start: false
include_document_end: false
indent: 2
indentless_arrays: false
line_ending: lf
max_line_length: 120
pad_line_comments: 1
retain_line_breaks_single: true
```
- Introduce a configuration file for yamlfmt
- Add support for formatting yaml files to codefmt.sh
- GitHub CI: Check for yaml coding style compliance in test workflow
- GitHub CI: Remove redundant steps when building release webmin container
- GitHub CI: Consistently leave records of version tags for each action
> Introduce yaml code style guide and automatic formatting

- .github/workflows/build.yml
Unlike Bookworm, the latest Debian release doesn't have certain other development packages depend on gcc, so we need to pull it in explicitly
> GitHub CI: Debian Trixie needs the gcc package

- webmin_module.Dockerfile
Since Debian Trixie has now been officially released, the Webmin Project has set up distribution repositories for this version now
> docker: Bump webmin module container to Debian Trixie from Bookworm

- .github/workflows/build.yml
- test/afpd/afpfunc_helpers.c
Addressing uninitialized memory usage flagged by valgrind
With this fix, you can run the tests successfully in a valgrind wrapper, e.g. through meson:
```
meson setup build -Dwith-tests=true
meson compile -C build
meson test --wrapper='valgrind --leak-check=full --track-origins=yes' -C build
```
when run on Linux with valgrind installed this should give you:
```
ninja: Entering directory `/home/dmark/netatalk/build'
ninja: no work to do.
1/2 afpd integration tests - setup        OK              0.32s
2/2 afpd integration tests - run          OK              6.66s
Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
Full log written to /home/dmark/netatalk/build/meson-logs/testlog-valgrind.txt …
```
> test: Consistently initialize buffers before use in afpd component tests

- include/atalk/netddp.h
At present, netddp_close, netddp_recvfrom and netddp_sendto are just macros which fob off responsibility for their prototypes to the prototypes of their underlying functions defined in unistd.h.  In the interests of better typechecking and removing a barrier to using netddp as an actually useful abstraction boundary again, this PR replaces the macros with stub inline functions (which boils down to the same thing).  The prototypes chosen are those mandated by POSIX for the underlying socket calls, which seems the sensible option, except that I've removed 'restrict' at the insistance of sonarqube.
> netddp: remove macros, define interface for netddp_{close, recvfrom, sendto}

- bin/rtmpqry/rtmpqry.c
- etc/papd/file.c
- etc/papd/print_cups.c
- include/atalk/ldapconfig.h
- libatalk/cnid/last/cnid_last.c
- libatalk/unicode/util_unistr.c
- test/testsuite/afpclient.h
rtmqry: touch up a few variables to avoid implicit data type conversion
overall: rephrase and clean up code comments that SonarQube interpreted as commented-out C code
> Fix code quality issues in rtmpqry and disambiguate comments

- bin/rtmpqry/rtmpqry.c
A straggler fix to address an implicit type conversion SonarQube bug
> rtmpqry: Declare variable to match the return value of called function

- doc/manpages/man1/afp_lantest.1.md
- test/testsuite/lantest.c
- test/testsuite/lantest_io_monitor.c
- test/testsuite/lantest_io_monitor.h
No changes to afp_lantest other than resolving SonarQube issues and C99 standards
Testing ok
```
+ afp_lantest -n 2 -7 -h 127.0.0.1 -p 548 -u test -w test -s 'File Sharing'
Connecting to host 127.0.0.1:548
IO monitoring: /proc_io is available
Looking for cnid_dbd processes with -u test in command line
Found cnid_dbd process: PID 40
Looking for afpd processes owned by user 'test' (UID: 1000)
Found privilege-dropped afpd process: PID 36
IO monitoring enabled (afpd: 36, cnid_dbd: 40)
Run 1 => Open, stat and read 512 bytes from 1000 files [8,000 AFP ops]        2509 ms
IO Operations; afpd: 6000 READs, 7004 WRITEs | cnid_dbd: 0 READs, 4 WRITEs
Run 1 => Writing one large file [103 AFP ops]                                  232 ms for 100 MB (avg. 451 MB/s)
IO Operations; afpd: 0 READs, 299 …
```
> testsuite: afp_lantest - Fixed SonarQube issues

- test/testsuite/lantest.c
- test/testsuite/lantest_io_monitor.c
- Remove a handful of declared but unused variables in lantest
- Use the NOSONAR syntax that SonarQube expects to skip analysis
- Extra protection against buffer overflow in check_process_name_match()
> testsuite: Resolve the last handful of code quality issues in lantest

- .github/workflows/build.yml
- .github/workflows/test.yml
Pin all builds to the latest stable Linux distro image version tag, for extra protection against supply chain attacks
Transition the Ubuntu Build job to use the latest stable Ubuntu image rather than the raw GitHub runner, and split out the dist check step
> GitHub CI: Pin CI build base images, and split out distribution tests

- doc/manpages/man1/nbplkup.1.md
Filling a gap in the documentation for an option that's been there forever
> docs: Document the -r option in the nbplkup.1 man page

- NEWS.md
- meson.build
NEWS is updated with the latest notable changes, and project version string bumped to *4.3.1*
> Bump to release version 4.3.1 and update changelog

- .github/workflows/code_analysis.yml
Addressing a new mandatory syntax introduced with v5.3.1 of the SonarQube scan action
> GitHub CI: Refactor the SonarQube scan action with supported GitHub expressions

- .github/workflows/release.yml
Meson outputs a sha256sum checksum file with the file ending .sha256sum so let's to the same in the Release workflow
> GitHub CI: Change file endings of checksum files to match meson

- .github/workflows/build.yml
Debian Trixie needs the gcc package, and bump OmniOS bootstrap
Use specific release hashes for docker images and vmactions actions
> [4.2] GitHub CI: Bring build jobs up to date and secure them

- meson.build
- meson_config.h
- subprojects/bstring.wrap
The upstream project has released a new version with release notes:
- The build system, including parity between autotools & meson
- Quality indicators and cleanups (expanded CI, SonarCube)
https://github.com/msteinert/bstring/releases/tag/v1.0.2
> Bump to bstring 1.0.2 subproject

- .github/workflows/build.yml
The bstring library has started getting distributed as shared library package in Homebrew
> GitHub CI: Install shared bstring library on macOS build job

- etc/afpd/uam.c
Since afpd isn't a threading application, there is no pressing need to use the reentrant-safe way to fetch the passwd entry in uam_getname()
The reverted solution had flaws that led to a critical failure when attempting to authenticate in a complex ActiveDirectory environment
> afpd: Revert to non-reentrant getpwnam() in the uam module

- bin/getzones/getzones.c
Should prevent a theoretical memory leak condition flagged by SonarQube
> getzones: defensively release memory in optarg function

- .github/workflows/build.yml
In the macOS runner's Homebrew environment there's already a sqlite library available so we keep getting a warning in every actions run
Also, run brew upgrade in macOS job to avoid intermittent fail state
> GitHub CI: remove redundant sqlite dependency on macOS build

- etc/afpd/desktop.c
Null pointer checks before accessing vol structure, use safer string concatenation function to prevent buffer overflow
Addresses potential null pointer dereference bug reported by SonarQube
> afpd: protect against bad parameters and buffer overflow in dtfile()

- doc/manpages/man1/afp_spectest.1.md
- test/testsuite/FPRead.c
- test/testsuite/afparg.c
- test/testsuite/afphelper.c
- test/testsuite/afphelper.h
- test/testsuite/lantest.c
- test/testsuite/logintest.c
- test/testsuite/spectest.c
- test/testsuite/speedtest.c
- test/testsuite/test.h
- test/testsuite/testhelper.c
Enumerate and delete all files and directories in Vol and Vol2 through a new utility function called clear_volume() in afphelper
A new `-E` option to afp_spectest enables this mode (default: off) while the other test suites don't use it
Lingering files between test executions may lead to unexpected test results, so using this option can give you more consistent results, or give you a shortcut for cleaning up a test volume before running tests
Refactor the testsuite to use is_there() from afphelper globally
> testsuite: Clean test volumes between each spectest test execution

- contrib/webmin_module/edit_global_section.cgi
- contrib/webmin_module/lang/en
- contrib/webmin_module/netatalk-lib.pl
- doc/manpages/man5/afp.conf.5.md
- etc/afpd/afp_options.c
- etc/afpd/uam.c
- etc/papd/uam.c
- etc/uams/uams_dhx_passwd.c
- etc/uams/uams_gss.c
- etc/uams/uams_pam.c
- etc/uams/uams_passwd.c
- etc/uams/uams_randnum.c
- include/atalk/globals.h
- include/atalk/uam.h
- libatalk/util/netatalk_conf.c
- meson.build
- meson_config.h
Remove the compile time disable valid shellcheck option in favor for a runtime option configurable in afp.conf
A known issue is that papd doesn't have the capability to configure valid shellcheck or even propagates the global papd settings to the UAM library;
for now we always keep valid shellcheck enabled for papd and leave a FIXME in the code
Also, fixes a bug where valid shellcheck was never done in the ClearTxt PAM UAM for afpd (but was doing it for papd auth)
> afpd: introduce runtime option for valid shellcheck

- SECURITY.md
Since a full 12 months have passed since the release of netatalk 4.0, the 3.x and 2.x release series are considered EOL and will no longer get security patches
> Release versions 3.2 and 2.4 are now End Of Life

- etc/afpd/dircache.c
The validation of AFPobj->username in this ternary statement always evaluates as true because the username struct member is defined as a char array with fixed width, and therefore always has a valid pointer
Instead, we check that the first char in the array is non-null to validate that it is actually a string
> afpd: check that username is a string before assigning in log_dircache_stat()

- bin/getzones/getzones.c
Depending on the optarg input string, the loop may exit after the requested_zone variable has been dynamically allocated, so let's free the memory every time
> getzones: protect against potential memory leak when exiting in optarg

- INSTALL.md
- doc/manual/Installation.md
- meson.build
Since the last backend is read-only, we want to error out rather than automatically selecting it as the default CNID backend in the absence of any other backend
You can still force the last backend as default with -Dwith-cnid-default-backend if you absolutely want to (but I cannot see when this would be useful)
This effectively introduces a hard build dependency on at least one of the three database libraries: bdb, mysql, or sqlite
> meson: error out if no writable CNID backend selected for compilation

- distrib/selinux/README.md
- distrib/selinux/netatalk.fc
- distrib/selinux/netatalk.if
- distrib/selinux/netatalk.sh
- distrib/selinux/netatalk.te
- distrib/selinux/netatalk_selinux.spec
This is an attempt at creating an SELinux policy for the netatalk -> afpd -> cnid_metad -> cnid_dbd daemon set using the Red Hat guide.
https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/using_selinux/writing-a-custom-selinux-policy_using-selinux
> Create SELinux policy for netatalk daemons

- doc/manpages/man5/afp.conf.5.md
- etc/afpd/acls.c
- etc/afpd/afp_config.c
- etc/afpd/afp_dsi.c
- etc/afpd/dircache.c
- etc/afpd/dircache.h
- etc/afpd/directory.c
- etc/afpd/file.c
- etc/afpd/filedir.c
- etc/afpd/meson.build
- include/atalk/directory.h
- include/atalk/globals.h
- include/atalk/util.h
- libatalk/acl/cache.c
- libatalk/acl/uuid.c
- libatalk/dalloc/dalloc.c
- test/afpd/meson.build
- test/testsuite/lantest.c
Implement "ask forgiveness" model for directory cache validation that reduces filesystem stat() and lstat() calls by up to 99% while maintaining safety through automatic recovery and monitoring.
Relates to plan https://github.com/Netatalk/netatalk/discussions/2422. And resolves "Cache Validation Overhead" issue. This unblocks the work to generally modernise the dircache structure, and eventually implement Adaptive Replacement Cache (ARC).
User story to accompany this change; https://github.com/Netatalk/netatalk/wiki/DirCache-redundant-stat-ops
Key improvements:
- Configurable validation frequency (1-100) via afp.conf
- Smart detection distinguishes metadata from content changes
- Self-healing: Invalid entries automatically re-queried from CNID
- New metrics track effectiveness (expunged …
> dircache: Add probabilistic validation for dramatic I/O reduction

- .github/workflows/containers.yml
- Dockerfile
Since the sqlite CNID backend is now considered stable, let's build and make it available in the production netatalk container
> docker: build the sqlite CNID backend in the Alpine production container
