- doc/manpages/man1/apple_dump.1.xml
> fix manpage of apple_dump

- etc/afpd/quota.c
Hi! I would like to use Netatalk with mounted fuse filesystem. By default, afpd detects it as a NFS share , if mount point has a colon in the name. But my partition is not an NFS share. So, I think it must be corrected.
> Fix nfs detection, allow to use on remote fuse systems

- etc/afpd/directory.h
- etc/afpd/volume.h
gcc 10 on Linux throws "multiple definition" errors; declares two variables as external to avoid this.
> [2.2] Fix 'multiple definition' compile time errors

- etc/afpd/directory.c
- libatalk/bstring/bstrlib.c
* Remove bitrotted inline prototype for a libc function  [Downstream patch from NetBSD](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/net/netatalk22/patches/patch-libatalk_bstring_bstrlib.c?rev=1.1&content-type=text/x-cvsweb-markup&sortby=date). Fixing a compilation error on that platform.
* Remove the remnants of someone's local dev environment. Downstream patch from netatalk-classic https://github.com/christopherkobayashi/netatalk-classic/commit/daaed65a8a8deb2475c3d60778f1467ea682204e.
> [2.2] Remove bitrotted code

- etc/uams/openssl_compat.h
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_dhx_passwd.c
- [OpenSSL 1.0 backwards compatibility header](https://github.com/NJRoadfan/a2server/blob/ivanx-1.5.x/files/netatalkpatches.tar.gz), downstream patch from the A2SERVER project
- [Downstream patch from NetBSD](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/net/netatalk22/patches/patch-etc_uams_uams__dhx__pam.c?rev=1.2&content-type=text/x-cvsweb-markup&sortby=date)
Note: The latter patch was originally part of the cluster of NetBSD fixes for OpenSSL 1.1 that was merged in https://github.com/Netatalk/Netatalk/pull/131
> [2.2] Fixes for the OpenSSL 1.1 API; add OpenSSL 1.0 backwards compat

- config/Makefile.am
- include/atalk/ldapconfig.h
Reverts the change in https://github.com/Netatalk/Netatalk/commit/096575860727879781fe809b8ef4165ef5ac0297#diff-62bf7ac6043eccf1da242490184942eceb426dc601fb3215a3f89bef1fc59e68
> Correct an erroneous patch that was unfortunately submitted upstream.
> Providing an empty header because we do not support ACLs only serves to break ldap support.
\- hauke
[Downstream patch from NetBSD](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/net/netatalk22/patches/patch-include_atalk_ldapconfig.h?rev=1.3&content-type=text/x-cvsweb-markup&sortby=date)
> [2.2] Install afp_ldap.conf based on LDAP support, not availability of ACLs.

- contrib/macusers/macusers.in
- etc/atalkd/main.c
- Set interface address correctly for phase 1 networks on NetBSD. http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/net/netatalk22/patches/patch-etc_atalkd_main.c?rev=1.1&content-type=text/x-cvsweb-markup&sortby=date
- Explicitly support NetBSD in the macusers script. https://github.com/christopherkobayashi/netatalk-classic/commit/9c62cc37180efcce74adf0798d430cedaed6f40d
> [2.2] Downstream patches for NetBSD compatibility

- etc/papd/print_cups.c
Deprecated functions: Remove obsolete define, and disable compiler errors for deprecation warnings, as seen in the darktable print code.
Accessors: Cups has abstracted away access to ipp_t fields, use accessor functions.
(downstream patch from [NetBSD](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/net/netatalk22/patches/patch-etc_papd_print_cups.c?rev=1.3&content-type=text/x-cvsweb-markup&sortby=date))
> [2.2] Resolve papd compile time errors due to deprecated CUPS calls

- etc/atalkd/main.c
- etc/atalkd/rtmp.h
With PR #131 merged, compatibility with NetBSD that was originally fixed in bbc0d89 is again broken, while fixing it for Linux. 
This change captures this special case inside an #ifndef macro.
See also discussion in this Ubuntu bug ticket https://bugs.launchpad.net/ubuntu/+source/netatalk/+bug/1839015
> [2.2] Handle special FIRSTNET behavior on NetBSD 

- etc/papd/file.c
- etc/papd/file.h
- etc/papd/magics.c
- etc/papd/queries.c
- etc/papd/session.c
-  Comment out line length check since Apple LaserWriter 8 drivers don't respect line lengths.
-  Clear input queue and switch to query mode if Postscript magic string is detected after first line of text is sent to papd. This is needed for the GS/OS driver since that driver sends raw Postscript to the printer in order to change it's PAPStatus display before sending the magic string. This is poor driver behavior on Apple's part, but other PAP servers had no problem handling it.
-  Properly support %%EOF termination of queries. Needed for GS/OS driver. 
-  Add support for Product queries (return's printer model name). LaserWriter 7 queries this to enable/disable driver features.
-  Add support for %%?Begin/EndFontListQuery. Sends font names in individual PAP packets vs. one large packet to …
> [2.2] papd patches for compatibility with older Apple LaserWriter drivers on Mac and GS/OS

- etc/cnid_dbd/cmd_dbd_scanvol.c
Based on patch by hauke, [FreeBSD downstream](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/net/netatalk22/patches/patch-etc_cnid_dbd_cmd_dbd_scanvol.c?rev=1.1&content-type=text/x-cvsweb-markup&sortby=date)
> [2.2] Allow non-unicode volume to be scanned by the repair tool.

- NEWS
- etc/afpd/acls.c
- etc/afpd/directory.c
- etc/afpd/filedir.c
- etc/afpd/fork.c
- etc/afpd/quota.c
- etc/afpd/unix.c
- etc/afpd/volume.c
- etc/cnid_dbd/dbd_getstamp.c
- etc/uams/uams_dhx2_pam.c
- etc/uams/uams_dhx2_passwd.c
- libatalk/acl/uuid.c
- libatalk/vfs/ea.c
- macros/zeroconf.m4
* afpd: Return the correct error for non-existent volume https://sourceforge.net/p/netatalk/bugs/577/
* Native avahi API should be the default choice https://sourceforge.net/p/netatalk/bugs/586/
* Saving from Photoshop sometimes fails https://sourceforge.net/p/netatalk/bugs/542/
* Update Netatalk volume capacity reporting to match Samba behavior https://github.com/Netatalk/Netatalk/pull/79
* Fix possible alignment violations due to bad casts https://sourceforge.net/p/netatalk/code/ci/802908edf9df6d57637c0b3d410f0c0b4c3509c6/
* Fix crash when moving files with shortened file names https://github.com/Netatalk/Netatalk/issues/150
* Fix NFS detection, allow to use on remote fuse systems
> [2.2] Backport Netatalk 3 patches

- etc/papd/file.c
- etc/papd/file.h
- etc/papd/magics.c
Patch to provide status replies when printing with AppleTalk over PPP.
Background printing does not work, since papd would only send the first block and if a status reply was not sent it would not continue with the print
Original patches by Nat Sloss. [NetBSD downstream patch repo](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/net/netatalk22/patches/?sortby=date#dirlist).
> [2.2] papd: Send replies to client when printing to prompt more data

- config/afpd.conf.tmpl
- etc/afpd/afp_options.c
- libatalk/asp/asp_getsess.c
- man/man5/afpd.conf.5.tmpl
The ability to disable AFP session tickles. Needed when using AFP with AppleTalk tunneled with very slow connections such as PPP.
Original patch by Nat Sloss. [NetBSD downstream patch repo](http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/net/netatalk22/patches/?sortby=date#dirlist).
> [2.2] afpd: Add option to disable afp session tickles

- contrib/a2boot/a2boot.c
- etc/afpd/file.c
- etc/afpd/filedir.c
- etc/afpd/uid.c
This fixes some compile issues that happen if some obsolete features are being turned on
> Fix some compile errors

- libatalk/dsi/dsi_write.c
This commit fixes the buffer overflow in dsi_writeinit().
> fix CVE-2022-43634

- libatalk/util/netatalk_conf.c
- macros/largefile-check.m4
correct main definition is required as otherwise the test fails with implicit-int
include is required for:
```
netatalk_conf.c:84:32: error: 'LOCK_EX' undeclared (first use in this function)
84 |     result = flock(fileno(fp), LOCK_EX);
```
which comes from sys/file.h: https://linux.die.net/man/2/flock
> fixes for misc compiler issues

- etc/afpd/quota.c
This enables compilation on OmniOSce r151044k. Patch by Hauke Fath.
> [2.2] Provide MNTTYPE_NFS on OmniOS

- etc/afpd/extattrs.c
When we get a request to list xattrs of a file that:
o is an open fork file handle in use by the client
o has no associated metadata
we call ad_close() on the adouble handle which does a refcount decrement which closes the file handle.
The fix is remembering whether we the ad_open() actually succeeded and only call ad_close() in that case.
Bug: https://sourceforge.net/p/netatalk/bugs/619/
Signed-off-by: Ralph Boehme <slow@samba.org>
Reviewed-by: Andrew Stormont <andyjstormont@gmail.com>
> [2.2] afpd: reading from file may fail (backport from 3.x)

- macros/largefile-check.m4
main() without a return type fails with Werror=implicit-int, which makes it fail to detect largefile support with clang 16
Backport of https://github.com/Netatalk/Netatalk/commit/a08e6137afaf8f6ec2139c250482c8515ceb3e2f
> [2.2] fix largefile-check macro for largefile with clang16

- contrib/timelord/timelord.c
On Solaris/OmniOS `tm_gmtoff` is not available in `struct tm` in time.h, unlike *BSD/Linux.
https://www.gnu.org/software/libc/manual/html_node/Broken_002ddown-Time.html
As a fallback, use `timezone` (also from time.h). The main drawback is that timezone does not take daylight savings into consideration.
https://www.gnu.org/software/libc/manual/html_node/Time-Zone-Functions.html
> [2.2] Fall back to timezone when tm_gmtoff is unavailable

- libatalk/adouble/ad_open.c
Revert "Make the resource fork length equal to ad->ad_data in case it is larger. This avoids unwanted entry parsing errors when operating on small files in GS/OS and Classic Mac OS."
This reverts commit 60ce27db6fb69ef1301005637613af8b8d310b96.
Further analysis showed that the assertion in Netatalk was caused by invalid adouble headers created by the `cppo` tool which is part of [A2SERVER](https://github.com/RasppleII/a2server). The bug was fixed in cppo with https://github.com/NJRoadfan/a2server/commit/7e3637f6983ccec008b1e5c9f091efb687f7b0f7 so we can restore the stricter validation in Netatalk. See https://github.com/rdmark/Netatalk-2.x/issues/18 for the full discussion.
> [2.2] Revert "Make the resource fork length equal to ad->ad_data"

- etc/afpd/nfsquota.c
Since it is derived from the BSD sources written by Elz, it is under the CA regents copyright and usual license. But we need the more formal lanuage included for it to be valid.
This addresses one of the remaining license FIXME issues: https://github.com/adiknoth/netatalk-debian/blob/master/debian/copyright#L59 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=685878#56
Reviewed-by: Ralph Boehme <slow@samba.org>
> [2.2] Add missing license based on BSD origin.

- etc/afpd/spotlight.c
- etc/spotlight/sparql_parser.c
- etc/spotlight/sparql_parser.y
- include/atalk/spotlight.h
- macros/netatalk.m4
Spotlight: Allow building with Tracker 3.x
This recent Tracker series contain some changes wrt the older versions,
notably to netatalk:
- The TrackerSparqlConnection constructor changed, it is no longer
a singleton.
- The topology of the data graph is slightly different (even though
it conforms to the same ontology/schema). Tracker data is now split
between "physical" (e.g. a file in a filesystem) and "logical" (e.g.
a representation of the content) interrelated with each other. Before,
both aspects would be conflated in a single resource.
For the former, handle this new constructor if built with Tracker 3.x,
accessing the tracker-miner-fs instance specifically. For the latter,
adapt the SPARQL query so it works correctly on both 3.x and prior
versions, despite the difference.
Patch …
> add support for tracker3

- configure.ac
Hotfix for breakage introduced with https://github.com/Netatalk/Netatalk/pull/203
`doc/Makefile` should not be bootstrapped in configure.ac anymore, since we have a static Makefile imported from netatalk-docs
> Hotfix: Don't try to bootstrap doc/Makefile

- etc/afpd/directory.c
While debugging one of Netatalk installs I scrolled through logs and noticed unknown term 'came', dug into source code and found out it was just a typo, so I fixed it.
> Fix a typo in debug message

- etc/afpd/directory.c
Four more debug string fixes of typos in "cname". Today I looked at code more deeper than 2 days ago trying to fix (understand) one thing so found that these typos were not only in 1 string, but in more places. Now I searched through all sources to make sure no more left.
PS: Sorry, I don't know for sure why all three commits are submitted in this PR, I can't find how to submit only 
a955dc7 commit. But, anyway, changes in this PR are only from this commit.
> Fix more typos

- doc/.gitignore
- doc/Makefile
- doc/README
- doc/checkinmans.sh
- doc/manual/html.xsl
- doc/manual/man.xsl
Make the docbook makefile/script/docs work better with newer docbook & dir structure
- html.xsl and man.xsl import works relative to the tmp dir
- manpage install target to always install into ../man rather than as a variable
- Explicitly use "source" as "manual"
- Remove outdated workarounds
Interestingly, the last docbook release that is fully compatible with our man pages is 1.79.1, because in 1.79.2 and beyond the refmiscinfo date and manual overrides are ignored. What's bizarre is that [the authors claim](https://github.com/docbook/xslt10-stylesheets/releases/tag/release%2F1.79.2) that 1.79.1 and 1.79.2 are functionally identical, which is clearly a lie.
Edit: Digging around I figured out that they introduced new namespaces in 1.79.2, in particular the `:d` namespace that applies to …
> [2.2] Update docbook scripts and readme

- doc/manual/netatalk.html
- doc/manual/netatalk/configuration.xml
- doc/manual/netatalk/install.xml
- doc/manual/netatalk/intro.xml
- Backport applicable improvements from 3.1
- Fix broken external URLs
- Document the new `--enable-systemd` configuration option
- Improve documentation for papd and timelord
- Rewrite the intro page to make more sense in today's context
- Point to Github project pages
> [2.2] Overhaul html manual page sources

- .github/workflows/build.yml
- libatalk/cnid/mysql/cnid_mysql.c
- sonar-project.properties
- Add new build.yml file that builds the master branch and runs the Sonar scan
- Add new sonar_project.properties with baseline project settings
- Fixes a deprecated my_bool data type that blocked compilation on all available Linux runtime environments ([deprecated with MySQL 8.0.1](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-compiling))
> Create GitHub build file with Sonar scanning

- .github/workflows/build.yml
Scan only PRs coming from the present repo. Github does not pass tokens to forks, so Sonar jobs will fail for PRs originating from forks. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
Scan the two active stable branches in addition to main.
> Tweak Sonar scanning config

- etc/afpd/appl.c
This commit fixes the heap-based buffer overflow in afp_getappl()
> [2.2] fix CVE-2022-45188

- distrib/initscripts/service.systemd.tmpl
Declaring After=syslog.target is unnecessary:
syslog is socket-activated and will therefore be started when needed.
Author: Jonas Smedegaard <dr@jones.dk>
Signed off by: Daniel Markstedt <markstedt@gmail.com>
Downstream patch from Debian: https://sources.debian.org/src/netatalk/3.1.14~ds-1/debian/patches/104_modernize_systemd.patch/
> Modernize Systemd service file

- bin/uniconv/Makefile.am
- configure.ac
autoconf syntax fixes to silence deprecation warnings
- AC_CONFIG_MACRO_DIR is deprecated in favor of AC_CONFIG_MACRO_DIRS
https://www.gnu.org/software/autoconf/manual/autoconf-2.70/html_node/Input.html
- INCLUDES is deprecated in favor of AM_CPPFLAGS
https://www.gnu.org/software/automake/manual/html_node/Program-Variables.html
- The `subdir-objects` option is required for the structure of our code.
https://www.gnu.org/software/automake/manual/html_node/Program-and-Library-Variables.html
> Modernize autoconf syntax

- doc/manual/configuration.xml
Since the mysql cnid backend is configured slightly differently from the others, and it isn't clear from the configure helptext, document in the html manual.
> Document how the mysql cnid backend is configured.

- contrib/macusers/macusers.in
Description: Fix output of macusers script for long usernames
Author: Will Aoki <waoki@umnh.utah.edu>
https://sources.debian.org/src/netatalk/3.1.14~ds-1/debian/patches/114_fix_macusers_ps_parsing.patch/
Description: macusers script fails to account for usernames with non-word characters
Author: Marco Wessel <marco@mediamatic.nl>
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=740352
Description: macusers showed root user. Bug #495 ([Sourceforge](https://sourceforge.net/p/netatalk/bugs/495/)).
Author: hat001 https://github.com/Netatalk/netatalk/commit/5e8f0e662dd8aeadac3757f9716da6bf50f008ef
> [2.2] Improvements to the macusers script

- sonar-project.properties
This addresses a Sonar warning that it doesn't know which version of Python to analyze our code against.
https://docs.sonarqube.org/latest/analyzing-source-code/languages/python/
Python 3.9.2 is the default in Debian Bullseye. It's possible to add more versions if needed.
Note: With https://github.com/Netatalk/netatalk/pull/227 we're removing all Python code except `afpstats`.
> Sonar: Analyze against Python 3.9

- doc/Makefile
- doc/manual/man/man8/a2boot.8.xml
- doc/manual/manual.xml
- man/man8/Makefile.am
- man/man8/a2boot.8
This daemon never had a man page AFAICT. This PR adds one.
> [2.2] man pages: create an a2boot man page

- distrib/initscripts/a2boot.service.tmpl
- distrib/initscripts/afpd.service.tmpl
- distrib/initscripts/atalkd.service.tmpl
- distrib/initscripts/cnid.service.tmpl
- distrib/initscripts/papd.service.tmpl
- distrib/initscripts/timelord.service.tmpl
atalkd will fail to start unless a network connection is established. All other DDP services depend on atalkd to have started first, so make them do the same.
This is critical for when netatalk is running on a device that only has a wlan interface, such as an RPi Zero W.
Addresses https://github.com/Netatalk/netatalk/issues/232
Also pulls in the improvement from downstream https://sources.debian.org/src/netatalk/3.1.14~ds-1/debian/patches/104_modernize_systemd.patch/
> [2.2] Improve systemd services dependencies

- doc/manual/netatalk/configuration.xml
Overlooked updating the manual following the default configuration change
> [2.2] Update manual to match current behavior

- contrib/macusers/macusers.in
Description: Fix output of macusers script for long usernames
Author: Will Aoki <waoki@umnh.utah.edu>
https://sources.debian.org/src/netatalk/3.1.14~ds-1/debian/patches/114_fix_macusers_ps_parsing.patch/
Description: macusers script fails to account for usernames with non-word characters
Author: Marco Wessel <marco@mediamatic.nl>
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=740352
Description: Support NetBSD.
Author: Christopher Kobayashi
https://github.com/christopherkobayashi/netatalk-classic/commit/9c62cc37180efcce74adf0798d430cedaed6f40d
> Improvements to the macusers script

- include/atalk/dictionary.h
- include/atalk/iniparser.h
- libatalk/iniparser/dictionary.c
- libatalk/iniparser/iniparser.c
This commit removes deprecated strcpy calls from iniparser and fixes the associated buffer overflow causing afpd to crash when compiled with clang.
> Bring iniparser library codebase in line with current version 4.1

- etc/afpd/afprun.c
- macros/iconv.m4
- macros/netatalk.m4
- macros/tcp-wrappers.m4
Avoid build failures with future compilers.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC
> C99 compatibility fixes

- etc/afpd/fce_api.c
For every login and logout, fce_register() is called with a NULL path string. The function does a realpath() lookup earlier than required, which leads to unnecessary failed path lookups. Moving this lookup later on in the function bypasses this.
> afpd: look up paths later on in fce_register()

- etc/afpd/auth.c
- include/atalk/server_child.h
- include/atalk/server_ipc.h
- libatalk/util/server_child.c
- libatalk/util/server_ipc.c
Patch by @kenjiuno originally contributed in https://sourceforge.net/p/netatalk/bugs/634/
> libatalk: Check that FPDisconnectOldSession is successful

- doc/manpages/man5/afp.conf.5.xml
The behavior was changed with https://github.com/Netatalk/netatalk/commit/3343c2 but the manpage wasn't updated.
Reported in https://sourceforge.net/p/netatalk/bugs/617/
> manpages: afp.conf parameters are not quoted

- libatalk/iniparser/iniparser.c
Partially reverts https://github.com/Netatalk/netatalk/commit/b568955f3f970cffe70289bcaa7e7cf9ddaf0687
Restores the change originally made in https://github.com/Netatalk/netatalk/commit/3343c2
> libatalk: Remove dequoting of double quotes in the iniparser, again

- configure.ac
[This is evident when you type afpd -V
> configure.ac: Remove extraneous forward slash in UAMS path

- .gitignore
- bin/ad/ad_cp.c
- bootstrap
- distrib/initscripts/Makefile.am
- distrib/initscripts/com.netatalk.daemon.plist
- distrib/initscripts/netatalkd
- doc/manual/install.xml
- etc/uams/uams_passwd.c
- libatalk/adouble/ad_lock.c
- libatalk/util/socket.c
- macros/netatalk.m4
- macros/pam-check.m4
- macros/zeroconf.m4
This initial changeset adds support for macOS hosts which do not have a built-in afp server (macOS Big Sur onwards) or which do not support AFP 2.2, the version required to connect to vintage Macs running classic Mac OS. In summary:
is compatible with modern Intel and Apple Silicon based Macs
fixes compilation errors when using the macOS native compiler. Apple's version of clang is picky about header orders, it likes the system headers to be iterated before the atalk and same-dir headers.
fixes macro to enable Zeroconf support on macOS
fixes EA macro to ensure sys EA support
fixes the lock file location on macOS
fixes db3 and ssl macros to ensure OpenSSL and Berkeley DB dependencies installed via Homebrew are found
fixes PAM macro to enable authentication on macOS
disables ACL and dtrace …
> Add support for macOS hosts

- libatalk/util/netatalk_conf.c
gcc10 complains about discarded qualifiers, so removing the const keyword from a variable that has multiple assignments throughout the function
This was a minor regression introduced by https://github.com/Netatalk/netatalk/pull/299
> libatalk: remove const keyword for variable that changes

- etc/spotlight/sparql_parser.y
The gcc10 compiler throwing these warnings:
```
Making all in etc
make[2]: Entering directory '/home/dmark/dev/netatalk/etc'
Making all in spotlight
make[3]: Entering directory '/home/dmark/dev/netatalk/etc/spotlight'
YACC     sparql_parser.c
/home/dmark/dev/netatalk/etc/spotlight/sparql_parser.y:44.1-5: warning: POSIX Yacc does not support %code [-Wyacc]
44 | %code provides {
| ^~~~~
/home/dmark/dev/netatalk/etc/spotlight/sparql_parser.y:57.1-7: warning: POSIX Yacc does not support %expect [-Wyacc]
57 | %expect 5
| ^~~~~~~
/home/dmark/dev/netatalk/etc/spotlight/sparql_parser.y:58.1-14: warning: POSIX Yacc does not support %error-verbose [-Wyacc]
58 | %error-verbose
| ^~~~~~~~~~~~~~
/home/dmark/dev/netatalk/etc/spotlight/sparql_parser.y:58.1-14: warning: deprecated directive: …
```
> spotlight: Use current directive %define parse.error verbose

- NEWS
- etc/papd/print_cups.c
The `printer-is-accepting-jobs` attribute is a boolean, not an integer, so check for Boolean. 
Before this fix the client's driver would detect the printer but would fail to print, complaining that the printer was rejecting jobs. There would be a corresponding message in the `papd` log like `appletalk papd: CUPS_PAP_OPEN: Canon_MF632CDW is not accepting jobs`.
This fix causes `cups_get_printer_status` to return a non-zero `status` when the printer is ready, allowing printing to work. Tested on Mac OS 8.6 and 9.2.2 and 10.2.8
> [2.2] Fix incorrect type in printer status check

- .github/workflows/build.yml
- configure.ac
Temporarily reverting the subdir-objects option for bootstrapping. A more comprehensive solution will be required to make this work with the test/afpd/
https://github.com/Netatalk/netatalk/issues/313
> configure: Revert the subdir-objects option

- .github/workflows/build.yml
- bootstrap
- configure.ac
- doc/manpages/man1/Makefile.am
- doc/manpages/man5/Makefile.am
- doc/manpages/man8/Makefile.am
- macros/db3-check.m4
- macros/iconv.m4
- macros/largefile-check.m4
- macros/libgcrypt.m4
- macros/tcp-wrappers.m4
- test/afpd/Makefile.am
This PR:
1. Updates the autoconf syntax in bootstrap and configure.ac and updates all obsolete macros.
2. Fixes the make check error that occurs when AM_INIT_AUTOMAKE([subdir-objects]) is present in configure.ac.
> Modernize autotools bootstrapping

- macros/iconv.m4
- macros/summary.m4
This commit fixes the macOS native libiconv detection failure resulting from the library being moved into the dyld shared cache
> Fix native libiconv detection on macOS, #343

- .gitignore
- bootstrap
- configure.ac
- distrib/initscripts/Makefile.am
- macros/cups.m4
- macros/db3-check.m4
- macros/iconv.m4
- macros/largefile-check.m4
- macros/libgcrypt.m4
- macros/snprintf-check.m4
- macros/srvloc.m4
- macros/tcp-wrappers.m4
These commit fixes all the obsolete macros and syntax in bootstrap, configure.ac and the m4 macros #345
> [2.2] Fix all warnings on running  bootstrap

- .github/workflows/build.yml
- bin/ad/ad_cp.c
- bootstrap
- configure.ac
- etc/uams/uams_passwd.c
- include/atalk/netddp.h
- include/atalk/paths.h
- libatalk/atp/atp_open.c
- libatalk/nbp/nbp_lkup.c
- libatalk/netddp/netddp_open.c
- libatalk/netddp/netddp_recvfrom.c
- libatalk/netddp/netddp_sendto.c
- libatalk/util/module.c
- libatalk/util/socket.c
- macros/pam-check.m4
- macros/zeroconf.m4
- sys/netatalk/at.h
This commit enables the 2.2 branch to be compiled on macOS hosts. The DDP, a2boot and timelord configure options can be enabled in preparation for a possible development of a userland AppleTalk stack for modern macOS iterations. Note that compiling for macOS is _not_ the same as compiling for Mac OS X Server, the kernel has long since discarded all AppleTalk/DDP related code (xnu/netat) and use of the /netat header files is not indicated.
> [2.2] Enable compilation on macOS hosts v2

- .github/workflows/build.yml
The bad linker flags in mysql_config are now fixed the upstream Homebrew formula for mysql.
> Revert "Temporary workaround for -lzlib not found issue in upstream mysql version 8.0.33"

- macros/pam-check.m4
`pam_systemd.so` should not be loaded, as it causes dbus errors. See #361 and [here](https://bugs.launchpad.net/ubuntu/+source/netatalk/+bug/1538004) for details.
```
/etc/pam.d$ diff -u common-session common-session-noninteractive
--- common-session      2023-06-16 14:50:01.333615224 +0200
+++ common-session-noninteractive       2023-06-16 14:50:01.337615060 +0200
@@ -1,9 +1,10 @@
#
-# /etc/pam.d/common-session - session-related modules common to all services
+# /etc/pam.d/common-session-noninteractive - session-related modules
+# common to all non-interactive services
#
-# at the start and end of interactive sessions.
+# at the start and end of all non-interactive sessions.
#
@@ -21,5 +22,4 @@
session        required                        pam_permit.so
session        required …
```
> Use non-interactive PAM session, fixes #361 

- etc/afpd/desktop.c
- etc/afpd/directory.c
- etc/afpd/extattrs.c
- etc/afpd/file.c
- etc/afpd/volume.c
- libatalk/adouble/ad_attr.c
- libatalk/adouble/ad_date.c
- libatalk/adouble/ad_flush.c
- libatalk/adouble/ad_open.c
- Added guard check before access ad_entry()
- Allow zero length entry, for AppleDouble specification
> Fix CVE-2022-23121, CVE-2022-23123 regression

- distrib/initscripts/atalkd.service.tmpl
The original init scripts for atalkd registered the NBP entries of "Workstation" and "netatalk". This commit adds this functionality to the systemd unit file.
> [2.2] Update atalkd.service to be consistent with other init scripts.

- etc/afpd/Makefile.am
- libatalk/compat/Makefile.am
- macros/quota-check.m4
- test/afpd/Makefile.am
Support building against libtirpc as separate from glibc
Author: Iain Lane <laney@debian.org>
> [2.2] Support building against libtirpc as separate from glibc

- etc/afpd/Makefile.am
- macros/cnid-backend.m4
Description: Fix support for cross-compilation with mysql_config and dtrace
This patch makes netatalk consult pkg-config before mysql_config
and supports exporting the compiler as CC environment variable.
Author: Helmut Grohne <helmut@subdivi.de>
> Fix support for cross-compilation with mysql_config and dtrace

- etc/afpd/Makefile.am
- libatalk/compat/Makefile.am
- macros/quota-check.m4
- test/afpd/Makefile.am
Support building against libtirpc as separate from glibc
Author: Iain Lane <laney@debian.org>
> Support building against libtirpc as separate from glibc

- configure.ac
- distrib/initscripts/Makefile.am
This changeset makes it possible to choose a systemd dir prefix on configure time.
- Introduce `--with-systemd-prefix` option that takes PATH to prefix (typically /lib or /usr/lib)
- Make `--enable-system` option detect the most likely prefix (/lib or /usr/lib)
- Deprecate platform specific systemd options
> [2.2] Configurable systemd prefix

- configure.ac
- distrib/initscripts/Makefile.am
The systemctl hooks for make install don't seem to work consistently in fakeroot. This introduces a `--disable-install-privileged` option as a workaround, e.g. for distro package scripts.
> [2.2] autoconf: Option to skip privileged hooks for make install

- .github/workflows/build.yml
- test/afpd/Makefile.am
This solves https://github.com/Netatalk/netatalk/issues/377 by allowing automake to find the compiled objects for afpd when linking the test binary with the distcheck target.
Also adding a `make distcheck` step for the Ubuntu job to catch this kind of breakage earlier in the future. It adds about 2 min to the runtime.
The distcheck target is broken on macOS so won't run it there.
> Tell automake to look for compiled objects in top_builddir

- doc/manpages/man1/apple_dump.1.xml
- doc/manpages/man5/afp.conf.5.xml
- etc/afpd/spotlight.c
- etc/uams/uams_gss.c
- Removed two cases of explicit reference to the underlying implementation (Perl script)
- Improve English grammar for a few sentences
- Several typos reported by Debian's lintian
> Fix user visible typos and improve English grammar

- doc/manual/configuration.xml
- doc/manual/upgrade.xml
The localstatedir that contains the CNID database can be configured at compile time. This improves the documentation on this topic.
> Clarify localstate dir configurability in manual

- bin/cnid/Makefile.am
The cnid2_create script is used to convert a CNID database created by Netatalk 1.x to a format compatible with Netatalk 2.x.
Debian lintian is complaining about missing man pages, and rather than adding a man page I think it's time to stop distributing it. If someone needs a legacy tool like this, it is available in the 2.2 branch.
> Don't build and distribute cnid2_create

- contrib/timelord/timelord.c
Use the `NO_STRUCT_TM_GMTOFF` preprocessor symbol explicitly, which is what is defined in configure.ac, instead of the logical opposite `HAVE_STRUCT_TM_GMTOFF` which didn't work on FreeBSD.
> Flip the check for tm->tm_gmtoff to appease FreeBSD

- doc/manual/man/man1/ad.1.xml
- doc/manual/man/man1/apple_dump.1.xml
- doc/manual/man/man1/megatron.1.xml
- doc/manual/man/man4/atalk.4.xml
- doc/manual/man/man5/AppleVolumes.default.5.xml
- doc/manual/man/man5/afpd.conf.5.xml
- doc/manual/man/man8/afpd.8.xml
- doc/manual/man/man8/atalkd.8.xml
- doc/manual/man/man8/cnid_dbd.8.xml
- doc/manual/man/man8/cnid_metad.8.xml
- doc/manual/man/man8/papd.8.xml
- etc/afpd/main.c
- etc/cnid_dbd/cmd_dbd.c
- etc/uams/uams_gss.c
- Removed two cases of explicit reference to the underlying implementation (Perl script)
- Improve English grammar for a few sentences
- Several typos reported by Debian's lintian
- Capitalization fixes
- Word choice improvements
> [2.2] Fix user visible typos and improve English grammar

- configure.ac
Backport the defaults for UAM library installation location.
> [2.2] autoconf: put UAM libraries in $libdir

- config/Makefile.am
The source path of static config files must be prefixed with `$(srcdir)` for out of tree builds to work.
It was already fixed for netatalk3 with this commit: https://github.com/Netatalk/netatalk/commit/a67d6457dcfeba36068952929d170056da95210e
> [2.2] Correct install hook for static config files

- doc/manual/Makefile
- doc/manual/man/man1/cnid2_create.1.xml
- doc/manual/manual.xml
- man/man1/.gitignore
- man/man1/Makefile.am
- man/man1/cnid2_create.1.tmpl
The cnid2_create tool is used to convert a Netatalk 1 CNID database to a Netatalk 2 compatible CNID database. I don't think it ever had a man page, so here's one that's based on the Upgrade guide.
> [2.2] Create man page for cnid2_create tool

- configure.ac
- sys/netatalk/Makefile.am
The at.h header conflicts with at.h distributed with glibc. Therefore, install the header only on systems where glibc isn't distributed by default. We still want to distribute it in the tarball, however.
As a side note, our at.h is probably relevant only for NetBSD presently, which is the one non-Linux OS where an appletalk kernel module is being kept alive.
> [2.2] Do not install at.h when glibc header is present

- doc/manual/Makefile.am
- man/man1/Makefile.am
- man/man5/Makefile.am
- man/man8/Makefile.am
This commit fixes the failure to substitute installation path variables in manages and docbook man/html pages.
> Fix variable substitution in manpages and docbook man/html pages #383

- configure.ac
- contrib/Makefile.am
- macros/summary.m4
- man/man1/Makefile.am
- man/man3/Makefile.am
- man/man5/Makefile.am
- man/man8/Makefile.am
- Remove the distinct --enable-a2boot and --enable-timelord config options, and fold them under --enable-ddp.
- Simplify appletalk conditionals in man makefiles
> [2.2] autoconf: Fold a2boot and timelord under the appletalk conditional

- doc/manual/Makefile.am
This commit fixes the GNU sed syntax error resulting from commit ffbe839
> Change sed substitution syntax so it works for both GNU and BSD versions

- doc/manual/netatalk/install.xml
- macros/db3-check.m4
- Document recommended bdb version
- Don't list 'fhs' as a commonly used option -- it's meant for distribution packagers
- Improve layout
- Typo fixes
- Add checks to the autoconf macro for bdb 5.2 and 5.3
> [2.2] Recommend BerkeleyDB 5.3

- macros/netatalk.m4
- macros/pam-check.m4
This issue has been here since the dawn of time. Removed extraneous quotation marks from netatalk and pam macros, used AC_SUBST macro to perform sysconfdir substitution
> Fix variable substitution in configure summary

- doc/manual/html.xsl
- doc/manual/netatalk.html
The css stylesheet for html manual pages is currently hard coded to an old sourceforge domain that isn't used anymore. As a result, the stylesheet isn't found and the manual pages stay unstyled. I think this is because the user agent refuses to load resources over insecure http in a https context.
> [2.2] Update URL for css stylesheet in manual pages

- doc/html.xsl.in
- doc/manual/netatalk.html
The css stylesheet for html manual pages is currently hard coded to an old sourceforge domain that isn't used anymore. As a result, the stylesheet isn't found and the manual pages stay unstyled. I think this is because the user agent refuses to load resources over insecure http in a https context.
> Update URL for css stylesheet in manual pages

- configure.ac
- doc/manpages/man1/afpldaptest.1.xml
- doc/manpages/man1/afpstats.1.xml
- doc/manpages/man5/afp.conf.5.xml
- doc/manpages/man5/afp_signature.conf.5.xml
- doc/manpages/man5/afp_voluuid.conf.5.xml
- doc/manpages/man5/extmap.conf.5.xml
- doc/manpages/man8/afpd.8.xml
- doc/manpages/man8/cnid_metad.8.xml
- doc/manpages/man8/netatalk.8.xml
- doc/manual/Makefile.am
- macros/netatalk.m4
- macros/pam-check.m4
- man/man1/afpldaptest.1.in
- man/man1/afpstats.1.in
- man/man5/afp.conf.5.in
- man/man5/afp_signature.conf.5.in
- man/man5/afp_voluuid.conf.5.in
- man/man5/extmap.conf.5.in
- man/man8/afpd.8.in
- man/man8/cnid_metad.8.in
- man/man8/netatalk.8.in
Tested on FreeBSD, Debian and macOS:
Config summary works
Substitution in man/man1, man/man5 and man/man8 works
Substitution in manual html files works
make distcheck works in Debian and FreeBSD
No NONE's in sight
Never again...
> Use single substitution for all variables in macros, manpages and docbook man/html files #441

- doc/manual/man/man5/afpd.conf.5.xml
Found a critical typo "uams_randum.so" in the afpd.conf man page. Took the opportunity to make bunch more improvements.
> [2.2] manpages: Fix typos, improve layout in afpd.conf man page

- distrib/initscripts/atalkd.service.tmpl
Reverts Netatalk/netatalk#372
I found atalkd and the other appletalk services to be unable to start up when other instances of atalkd run on other hosts on the same LAN.
> Revert "[2.2] Update atalkd.service to be consistent with other init scripts."

- etc/afpd/spotlight.c
- libatalk/talloc/dalloc.c
A Type Confusion vulnerability was found in the Spotlight RPC functions in Netatalk's afpd daemon. When parsing Spotlight RPC packets, one encoded data structure is a key-value style dictionary where the keys are character strings, and the values can be any of the supported types in the underlying protocol. Due to a lack of type checking in callers of the dalloc_value_for_key() function, which returns the object associated with a key, a malicious actor may be able to fully control the value of the pointer and theoretically achieve Remote Code Execution on the host.
The underlying code for Spotlight queries in Netatalk shares a common heritage with Samba, and hence the root cause and fix are logically identical with those described in CVE-2023-34967.
> CVE-2023-42464: Validate data type in dalloc_value_for_key()

- libatalk/pap/.gitignore
> Remove unused pap directory in libatalk

- macros/netatalk.m4
This commit fixes a new compilation error on macOS 14 (Sonoma)
> No quota support on macOS

- macros/iconv.m4
> Fix syntax error in iconv.m4 macro

- etc/netatalk/Makefile.am
- macros/netatalk.m4
This error occurs because of incorrect syntax in the netatalk binary makefile and the libevent check macro
> Fix libevent2 linking on OpenIndiana

- libatalk/adouble/ad_open.c
I propose that we remove the assertion and restore the cleanup in main/3.2.0 while keeping it indefinitely in 3.1.x
> libatalk: Restore invalid metadata cleanup in ad_open.c

- doc/manpages/man1/afpldaptest.1.xml
- doc/manpages/man1/afpstats.1.xml
- doc/manpages/man5/afp.conf.5.xml
- doc/manpages/man5/afp_signature.conf.5.xml
- doc/manpages/man5/afp_voluuid.conf.5.xml
- doc/manpages/man5/extmap.conf.5.xml
- doc/manpages/man8/afpd.8.xml
- doc/manpages/man8/cnid_metad.8.xml
- doc/manpages/man8/netatalk.8.xml
Rewrite paragraphs that referred to specific configurable file system paths.
> Remove substitutions for configurable file paths in man pages

- doc/manual/man/man1/afpldaptest.1.xml
Some minor straggler cleanup of docbook xml sources
> [2.2] Remove redundant id properties in man page

- test/afpd/.gitignore
- test/afpd/Makefile.am
- test/afpd/test.sh
The new default location for autoconf (libdir) isn't valid on macOS.
> [2.2] Rearrange the dummy file system paths for the tests

- etc/afpd/afp_asp.c
A straggler patch from 2.x / netatalk-classic.
> [2.3] Don't seteuid() if process is already running as that uid.

- config/AppleVolumes.system
Re-enable the file type translation configurations. They were disabled back in 2009 with https://github.com/Netatalk/netatalk/commit/df237c9a38416b32bfdd2bcab4a0d7bcbc69f78d arguing that they may be inappropriate for Mac OS X.
With Classic Mac OS being the primary use case for netatalk2, it worth revisiting this, in particular for identification of binary files downloaded from the web directly to the netatalk server file system. F.e. disk images, sit files, zip files, etc.
> [2.3] Enable, sort, and flesh out file type translation

- etc/papd/main.c
Quoting Chris K:
> That was part of an attempt last year to make papd less dangerous.  The code
constructs packets by allocating a char buffer and scribbling into that --
the patch replaces that nonsense with packed structs that dramatically reduces
the possibility of stack smashing.
> [2.3] Add long-forgotten patch to make papd safer.

- config/afp.conf.tmpl
I think the `/xxxx` Homes basedir regex example is potentially confusing to less technically proficient users. Let's use the most baseline real life example instead.
> Better default Homes basedir regex example

- etc/afpd/acls.c
Avoiding a potential buffer overrun if the value is too large
Credits: Robert Morris
> Validate size of ace_count in FPSetACL request

- etc/afpd/acls.c
Avoid potential crash in FPSetACL, https://github.com/Netatalk/netatalk/issues/364
> [2.3] Validate size of ace_count in FPSetACL request

- .github/workflows/build.yml
According to https://github.com/actions/runner-images/issues/6488 is it recommended to always run "apt-get update" before installing packages with apt-get on github runners.
It is not consistent, but sometimes we run into errors in our jobs about packages not found on the azure deb mirrors. F.e. https://github.com/Netatalk/netatalk/actions/runs/6823100246
Also, cleaning up the line breaks and code comments.
> Run apt-get update before installing packages

- .github/workflows/build.yml
Running "apt-get update" before installing packages with apt.
Also, cleaning up the comments and line breaks a bit
> [2.3] Run apt-get update before installing packages

- etc/uams/uams_dhx2_pam.c
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_pam.c
Linux, NetBSD, and FreeBSD use this data structure in the PAM library:
```
struct pam_conv {
int (*conv)(int num_msg, const struct pam_message **msg,
struct pam_response **resp, void *appdata_ptr);
void *appdata_ptr;
};
```
e.g. FreeBSD https://man.freebsd.org/cgi/man.cgi?query=pam_conv&apropos=0&sektion=3&manpath=FreeBSD+14.0-RELEASE&arch=default&format=html
Out of our supported platforms, only Solarish (Solaris-like) OSes seem to use the non-const pam_message pointer.
```
struct pam_conv {
int (*conv)(int, struct pam_message **,
struct pam_response **, void *);
void *appdata_ptr;		/* Application data ptr */
};
```
e.g. Illumos https://github.com/illumos/illumos-gate/blob/master/usr/src/lib/libpam/pam_appl.h
> pam_conv: Only Solarish seems to use non-const struct type.

- configure.ac
- etc/afpd/Makefile.am
- etc/spotlight/Makefile.am
- include/atalk/spotlight.h
- libatalk/Makefile.am
- macros/netatalk.m4
- test/afpd/Makefile.am
1. Move talloc search macro to Spotlight support macro
2.  Compile Spotlight support only if all three components are present (talloc, tracker and tracker-sparql)
> Enable / disable the entire spotlight support toolchain at configure time

- etc/afpd/spotlight.c
- etc/afpd/spotlight_marshalling.c
- etc/spotlight/sparql_parser.c
- etc/spotlight/sparql_parser.y
- etc/spotlight/spotlight_rawquery_lexer.l
- include/atalk/dalloc.h
- include/atalk/spotlight.h
- libatalk/talloc/dalloc.c
The dalloc.h header depends on talloc so it shouldn't be imported without the Spotlight toolchain.
Also, the symbols in spotlight.h aren't needed without Spotlight to let's ifdef them away (unless there's a more graceful way to do this?)
> Compile spotlight.h only when Spotlight is enabled

- bin/ad/ad.c
- bin/misc/logger_test.c
- bin/misc/uuidtest.c
- doc/manpages/man5/afp.conf.5.xml
- etc/afpd/afp_dsi.c
- etc/cnid_dbd/cmd_dbd.c
- include/atalk/globals.h
- include/atalk/logger.h
- libatalk/util/logger.c
- libatalk/util/netatalk_conf.c
- test/afpd/test.c
Introduces a boolean afp.conf option "log microseconds", enabled by default, which turns on and off microsecond timestamps in file logs.
> Introduce option to control the format of file log timestamp

- etc/atalkd/main.c
This patch was causing unintended side effects, namely atalkd ceased broadcasting RTMP routing tuples to other routers on the network. Confirmed issue testing with a Shiva Fastpath 5 hardware router and a software router called TashRouter.
> Revert Asante and Dayna GS/OS Fix.

- doc/manual/man/man8/atalkd.8.xml
- etc/atalkd/main.c
- Introduce a `-q` parameter for atalkd which stops AppleTalk packet propagation from subnets under other routers. This improves compatibility with Asante and Dayna hardware AppleTalk bridges.
- Removed the unused quiet and chatty parameters
- A more helpful error message when using unknown parameters
- Fleshed out the atalkd man page
> atalkd: Introduce 3rd party bridge quirks mode

- etc/afpd/afp_dsi.c
- etc/afpd/auth.c
- etc/afpd/file.c
- include/atalk/spotlight.h
Tested on Fedora39 x86_64 and aarch64 with configuration as per the wiki. Also tested on FreeBSD14, Debian12
> Fix Spotlight support detection and compilation on Fedora

- bin/misc/.gitignore
- bin/misc/Makefile.am
- bin/misc/logger_test.c
- include/atalk/logger.h
Improved logger_test:
- log type identifiers should be lower case
- Uncommended the syslog tests, and brought their logging API calls up to date
- Added a switch to the default log scope when changing from syslog to file log, otherwise the file logging didn’t take effect.
- Fleshed out and numbered the test case outputs
Additionally: removed inline documentation of the log API that was outdated. The code itself is readable enough to serve as documentation.
> Improve logger_test and remove outdated comments

- configure.ac
- doc/manual/man/man5/afpd.conf.5.xml
- doc/manual/man/man8/afpd.8.xml
- doc/manual/man/man8/papd.8.xml
- etc/afpd/afp_asp.c
- etc/afpd/afp_options.c
- etc/afpd/desktop.c
- etc/afpd/file.c
- etc/afpd/fork.c
- etc/afpd/messages.c
- etc/afpd/ofork.c
- etc/atalkd/main.c
- etc/atalkd/rtmp.c
- etc/atalkd/zip.c
- etc/papd/headers.c
- etc/papd/lp.c
- etc/papd/main.c
- etc/uams/uams_dhx2_pam.c
- etc/uams/uams_gss.c
- libatalk/unicode/charcnv.c
- libatalk/util/bprint.c
- Remove the --enable-debug --enable-debug1 configure options 
- refactor the afpd non-forking debug mode, and flip the afpd.conf option from -nodebug to -debug
- Replace debug macros with debug9 level logs
- in papd and atalkd, use the runtime debug mode instead of compile time macro
> [2.3] Switch from compile-time debug to run-time debug where applicable

- etc/afpd/auth.c
It seems unlikely that a bug will occur, but it seems that a patch is needed just in case.
```
diff --git a/etc/afpd/auth.c b/etc/afpd/auth.c
index 15e16441..89a2a3b3 100644
--- a/etc/afpd/auth.c
+++ b/etc/afpd/auth.c
@@ -827,7 +827,7 @@ int afp_logout(AFPObj *obj, char *ibuf _U_, size_t ibuflen  _U_, char *rbuf  _U_
*/
int afp_changepw(AFPObj *obj, char *ibuf, size_t ibuflen, char *rbuf, size_t *rbuflen)
{
-    char username[MACFILELEN + 1], *start = ibuf;
+    char username[MAXUSERLEN], *start = ibuf;
struct uam_obj *uam;
struct passwd *pwd;
size_t len;
```
It could be overflowed when uam_getname is called in afp_changepw. (that function is in etc/afpd/uam.c)
(name buf size is 32 but MAXUSERLEN is 255)
> Fixing bugs that can cause system errors

- include/atalk/compat.h
- libatalk/util/netatalk_conf.c
This aligns netatalk_conf.c with the rest of the codebase which consistently uses fcntl() for file locking.
> libatalk: Use portable fcntl() instead of flock()

- etc/afpd/afp_dsi.c
- etc/afpd/auth.c
- include/atalk/volume.h
I decided to keep the "save euid" code since it is used by another feature now, namely the reloading of groups when a volume changes https://github.com/Netatalk/netatalk/commit/534030591702e03f002ae3e11f638d57925054e8
> [2.3] Minor cleanup of residual afprun code

- .github/workflows/build.yml
- macros/zeroconf.m4
This commit fixes a macro failure where the avahi-client/client.h header (and hence the library) is not detected on multiple *BSD platforms because of unconventional file locations. Avahi detection is now managed entirely by pkg_config and the use of the PKG_CONFIG_PATH configure variable where necessary.
> Fix Zeroconf support on *BSD platforms

- .github/workflows/build.yml
- test/afpd/Makefile.am
Add build workflows for three platforms that are relevant for netatalk v2, namely they have appletalk networking support:
- NetBSD
- Solaris
- Fedora Linux
> [2.3] Add NetBSD, Solaris, Fedora build workflows

- distrib/initscripts/Makefile.am
This fixes an error when building on NetBSD with stock make (not gmake)
> [2.3] Use correct BSD make syntax in initscripts Makefile

- contrib/macusers/macusers.in
Small improvement to the macusers script: When the user's full name is not available, out a `-` instead of nothing.
> [2.3] macusers: Fallback output when full name not available

- etc/papd/print_cups.c
The function cupsPrintFile() is being removed in CUPS 3.0. Use the CUPS destination API to send print jobs from papd from now on.
> [2.3] papd: Update cups_print_job() to use CUPS destination API

- etc/papd/print_cups.c
Replace deprecated cupsGetDests() with cupsGetDests2(). The original cupsGetDests() function is due to be removed in CUPS 3.0. Confusingly, cupsGetDest2() will be renamed to cupsGetDest() in libcups3, so we'll need a define macro for this in the future in order to maintain compatibility with both libcups2 and libcups3.
> [2.3] papd: Update cups_autoadd_printers() to use current API call.

- .github/workflows/build.yml
Adding a bunch of deb packages to enable configuring and compiling cracklib and ldap/acl on Ubuntu/Debian.
The quota autoconf macro doesn't seem to work anymore in Debian bookworm (or Ubuntu 22.04) so using Debian bullseye
> [2.3] workflow: Compile on Debian with cracklib, ldap, quota

- etc/afpd/afp_options.c
- etc/afpd/auth.c
- etc/netatalk/netatalk.c
- etc/spotlight/spotlight_rawquery_lexer.c
- etc/spotlight/spotlight_rawquery_lexer.l
- include/atalk/spotlight.h
- macros/netatalk.m4
Refactor Spotlight macro
Warn if any Spotlight support components are missing at configure time
> Remove unneeded HAVE_TRACKER conditional

- .github/workflows/build.yml
- Explicitly install berkeley-db with Homebrew (we didn't have to before, but mandatory now... what changed?)
- Clean up a few misspelled and duplicated packages and options
- Add packages and options to get tcp wrappers and cracklib to build on Debian/Ubuntu
- Compile PGP and Kerberos UAMs on more platforms (but skipped OmniOS and DragonflyBSD for now... errors)
> workflow: Sundry fixes to get more options to build on more OSes

- doc/manual/netatalk.html
I created a download.php page to link to instead of the sourceforge archive, and a self-hosted wiki mirror
> manual: Link to custom download and wiki mirrors in navbar

- etc/papd/print_cups.c
Another attempt to clean things up for CUPS 3.0. Removed yet more deprecated API calls. Updated IPP commands to current values. Also removed unneeded calls to get language information since CUPS does that for you automatically via ippNewRequest().
> [2.3] papd - More cleanup and moderization of print_cups.c

- etc/papd/print_cups.c
Code cleanup and de-duplication. We have the cups_get_language() function already, so we should be calling it when needed.
> [2.3] papd - Use cups_get_language() function

- etc/papd/print_cups.c
Use cupsGetOptions() to get the printer URI from CUPS instead of hard coding it.
> [2.3] papd: Use cupsGetOptions() to get printer URI

- doc/manual/man/man8/atalkd.8.xml
- etc/atalkd/main.c
If the (only) interface was configured with the `-router` switch, automatically enable quirks mode. Otherwise don't. This is a hack as the split horizon logic is clearly broken here. If a single interface is configured as a router, it should ALWAYS broadcast RTMP packets no matter what.
Note: This patch doesn't remove the "quirks mode" command line switch or manpage documentation.
> [2.3] atalkd: Fix for RTMP broadcast bug.

- etc/papd/print_cups.c
Clean up code to query a printer for creating a temporary PPD file. We no longer exploit cupsConnectDest() to create a temporary queue for DNS-SD discovered printers to query printer data. Instead we check for what type of printer the destination is and query it direct.
In addition indentation of code was cleaned up for readability.
> [2.3] papd: Refactor and cleanup cups_get_printer_ppd()

- etc/papd/print_cups.c
More code cleanup. Switch to using solely the CUPS Destination API to speak with the server instead of doing IPP queries ourselves. If we have a DNS-SD discovered printer, we query it directly for the status.
> [2.3] papd: update cups_get_printer_status()

- doc/html.xsl.in
- doc/manual/Makefile.am
Small updates to accommodate the move away from sourceforge hosting
> [2.3] manual: Remove obsoleted html-upload target, and update css URL

- .dockerignore
- .gitignore
- Dockerfile
- Makefile.am
- README.md
- contrib/shell_utils/Makefile.am
- contrib/shell_utils/docker-entrypoint.sh
Dockerfile and entry point script for running an AFP server + AppleTalk services.
Based on the original POC by eharmon
> [2.3] Create Dockerfile and entry point

- .gitignore
- Dockerfile
- Makefile.am
- README.md
- contrib/shell_utils/Makefile.am
- contrib/shell_utils/docker-entrypoint.sh
Ported from branch-netatalk-2-3 with modification
Using oldstable Debian bullseye-slim as base image because of OpenSSL 1.1 -- we get a working DHX UAM
> Docker configuration for netatalk v3

- Dockerfile
- README.md
- contrib/shell_utils/docker-entrypoint.sh
This changeset attempts to address an incompatibility with an older Synology NAS
- Revert to Bullseye image, and enable DHX UAM
- Bail out early if AFP_USER or AFP_PASS are undefined
- Introduce AFPD_LOGLEVEL and INSECURE_AUTH options
> [2.3] Docker: Check for mandatory env variables; more configurability

- distrib/initscripts/Makefile.am
- distrib/initscripts/com.netatalk.daemon.plist.tmpl
- distrib/initscripts/netatalkd.tmpl
This  commit fixes the failure of the macOS initscripts if Netatalk is installed in a non-standard location
> Make macOS initscripts prefix sensitive

- distrib/initscripts/.gitignore
A small oversight from the recent move to templates for macOS initscripts
> Update .gitignore for generated macOS initscripts

- doc/manpages/man1/ad.1.xml
- doc/manpages/man1/afppasswd.1.xml
- doc/manpages/man1/uniconv.1.xml
- doc/manpages/man5/AppleVolumes.default.5.xml
- doc/manpages/man5/afp_ldap.conf.5.xml
- doc/manpages/man5/afp_signature.conf.5.xml
- doc/manpages/man5/afp_voluuid.conf.5.xml
- doc/manpages/man5/afpd.conf.5.xml
- doc/manpages/man5/atalkd.conf.5.xml
- doc/manpages/man5/netatalk.conf.5.xml
- doc/manpages/man5/papd.conf.5.xml
- doc/manpages/man8/a2boot.8.xml
- doc/manpages/man8/atalkd.8.xml
- doc/manpages/man8/cnid_dbd.8.xml
- doc/manpages/man8/cnid_metad.8.xml
The purpose of this changeset is to make the man page descriptions more accurate, to allow for at a glance overview when looking at a list of the man page (e.g. https://netatalk.io/oldstable/htmldocs/man-pages )
> [2.3] docs: Improve man page summaries

- configure.ac
- doc/html.xsl.in
- doc/manual/.gitignore
- doc/manual/Makefile.am
- doc/manual/manual.xml.in
- doc/manual/netatalk.html
- doc/manual/netatalk.html.in
This change is meant to make it clearer in the generated html manual which version of Netatalk it is for. We now put a header with the version number on each generated html chunk.
> [2.3] docs: Print netatalk version as subtitle, and header on each html page

- doc/html.xsl.in
- doc/manual/manual.xml.in
- doc/manual/netatalk.html.in
Another batch of minor improvements to the docbook docs:
- Limit TOC depth to 2 in the generated html manual: improves readability of the top level TOC, without sacrificing the detailed TOC on individual chapter pages.
- Bump to DocBook 4.5 DTD from 4.2 -- the GPL DocBook uses the 4.4 DTD, so I bumped to the last 4.x series DTD for good measure. I ran a diff test on the generated html/man files and there was no difference in how the XML was transformed.
- Small wording tweaks
> docs: Limit max TOC depth to 2 in html manual; use DocBook 4.5 DTD

- configure.ac
- distrib/initscripts/.gitignore
- distrib/initscripts/Makefile.am
- distrib/initscripts/com.netatalk.daemon.plist.tmpl
- distrib/initscripts/netatalkd.tmpl
- doc/manual/install.xml
macOS style launchd template and helper script
> [2.3] Create init scripts for macOS 

- .github/workflows/build.yml
- doc/manpages/man5/afp.conf.5.xml
- libatalk/acl/ldap.c
- macros/netatalk.m4
- man/man5/afp.conf.5.in
- meson.build
- Use the more modern ldap_initialize to init LDAP, which enables the use of advanced server URI schemes
- **BREAKING** The `ldap server` options has been replaced by `ldap uri` in afp.conf and has a new syntax
- **BREAKING** Make both build systems check for the ldap_initialize symbol, which requires the system ldap library to supply this symbol
- Update the documentation
- Update the OmniOS CI job to look for libldap in /opt/local
- Fix error handling for vmactions jobs
- Disable failing integration tests for FreeBSD and OpenBSD (existing issue; not caused by this changeset)
- Various syntax fixes in the CI job yml file
> Swap out the old ldap_init for the wonderful ldap_initialize

- configure.ac
- doc/manpages/man5/afp_ldap.conf.5.xml
- libatalk/acl/ldap.c
- Use the more modern ldap_initialize to init LDAP, which enables the use of advanced server URI schemes
- **BREAKING** The `ldap_server` options has been replaced by `ldap_uri` in afpd.conf and has a new syntax
- **BREAKING** Make the build system check for the ldap_initialize symbol, which requires the system ldap library to supply this symbol
- Update the documentation
> [2.4] Swap out the old ldap_init for the wonderful ldap_initialize

- .github/CODEOWNERS
This is needed for automatic PR assignment for 2.3 branch PRs.
> [2.4] Add GitHub CODEOWNERS file

- distrib/initscripts/.gitignore
- distrib/initscripts/Makefile.am
- distrib/initscripts/io.netatalk.daemon.plist.tmpl
- distrib/initscripts/meson.build
This is a breaking change. Users need to manually disable com.netatalk.daemon.plist first. 
```
sudo launchctl disable system/com.netatalk.daemon
```
And in my experience, restart macOS for the old com.netatalk.daemon record to go away completely (i.e. from `launchctl list` )
> Rename launchd plist to io.netatalk* and sort file names

- meson.build
This commit fixes errors in the meson tcpwrap macro and widens the search for gssapi/kerberos headers so they are picked up on more platforms
> meson: Refactor tcpwrap macro and widen gssapi/kerberos header searches

- distrib/initscripts/meson.build
- meson.build
- meson_options.txt
- Fixes for PAM detection on Solaris and Omnios: The preferred mechanism for PAM configuration on Solaris is now using per-service files in /etc/pam.d. Some solaris-based systems still use the /etc/pam.conf configuration file
- Fix typos in root meson.build and meson options file
- Fix error in redhat_sysv custom target
> Meson hotfixes

- distrib/initscripts/meson.build
- meson.build
- meson_options.txt
* Fix typos in root meson.build
* Fixes for PAM detection on solaris-based systems
The preferred mechanism for PAM configuration on Solaris is now using per-service files in /etc/pam.d. Some solaris-based operating systems (e.g Omnios) use the old /etc/pam.conf configuration file
* Fix error in redhat_sysv custom target
> [2.4] Meson hotfixes

- bin/ad/meson.build
- bin/afppasswd/meson.build
- etc/afpd/meson.build
- etc/cnid_dbd/meson.build
- etc/netatalk/meson.build
- meson.build
> meson: Fix executables not linking correctly with libatalk shared library

- doc/manual/compile.xml
- doc/manual/generate_compile_docs.py
- doc/manual/install.xml
- doc/manual/manual.xml.in
- Add a python script for generating a docbook XML manual page derived from the GitHub workflow build.yml
- Add the new manual page as an appendix to the html manual
- Remove autotools specific human written steps
To run the python script, the `xmltodict` package is required. The other libraries are built in. On debian, you can get this package by installing `python3-xmltodict` with apt. Elsewhere you may have to install it with pip (system or virtual env.)
> docs: Generate compilation manual page from build.yml

- doc/DEVELOPER
- doc/README.AppleTalk
Refreshing the readmes under doc/
- Move portability chapter to DEVELOPER
- Add section on AppleTalk on NetBSD, and remove way outdated OpenBSD section
- Remove build instructions now in INSTALL
> [2.4] docs: Refresh DEVELOPER and AppleTalk readmes

- Dockerfile
- contrib/shell_utils/docker-entrypoint.sh
- Passes a few prefixes to meson to make the build pass with docker on macOS
- Installs more libraries that are needed to build and run netatalk
- Preemptive cleanup of the build dir
> docker: Platform independent image building

- doc/manpages/man5/afp.conf.5.xml
- etc/afpd/fce_api.c
- include/atalk/globals.h
- libatalk/util/netatalk_conf.c
Two measures to allow for better handling of very large numbers of simultaneous FCE events
- If fce holdfmod is 0 the modification events must be thrown directly
- Added configurable wait between fce event sending to avoid udp event loss
Both patches by @seiman
> afpd: Deal better with large numbers of FCE events

- doc/manual/configuration.xml
- doc/manual/install.xml
- Document all of the supporting libraries
- Simplify the binary package repo section
- Removed all explicit references to autotools configure options
- Moved 'starting and stopping' section from configuration to install chapter
- More logical nesting of configuration chapter sections
- Proofreading of the configuration chapter
- Used the XMLmind editor to autoformat the XML
> docs: Overhaul the install and configuration chapters

- .github/workflows/build.yml
- distrib/initscripts/Makefile.am
- distrib/initscripts/meson.build
- Because openSUSE Tumbleweed doesn't have a insserv or insserv-compat package available, cannot use `suse-sysv`
- Tried using openSUSE Leap (each 15.x release image) for a more stable base OS but all of them fails in GitHub Actions (cannot find `tar` which points to PATH being bad)
- The `zypper` command is split up into two because it bugs out when installing too many packages at once 👎
> GitHub CI job with openSUSE Tumbleweed

- bin/meson.build
- meson.build
This commit also enables all options within the Alpine Linux job
> meson: Fix false positive for DHX support in Alpine when SSL headers absent

- .github/workflows/build.yml
- bootstrap
It seems the github actions runner for macOS was upgraded from 12.7.4 to 14.4.1 this morning. Some assumptions about the CI job have to be revisited.
> GitHub CI: macOS runner was upgraded to Sonoma

- distrib/initscripts/Makefile.am
- distrib/initscripts/rc.freebsd.tmpl
- macros/zeroconf.m4
- meson.build
Takes in the FreeBSD rc script from FreeBSD ports, by Joe Marcus Clarke, with minor modification.
- Added a copyright notice with the BSD 2-clause license
- Changed substitution deliminator from %%%% to :: to match our build system
Implementation note: `avahi_daemon` and `mdnsd` is what the respective zeroconf daemon is named in FreeBSD. We need one of these to be injected into the rc script for the startup ordering to work properly.
> Adopt rc script from FreeBSD ports.

- meson.build
The zeroconf macro now searches for avahi first, if not found then it searches for mDNS
> meson: Fix zeroconf detection on Alpine Linux

- config/meson.build
Default is /etc/dbus-1/system.d
> meson: Match netatalk-dbus.conf install dir to value of -Dwith-dbus-sysconf-dir option

- .github/workflows/build.yml
- Dockerfile
- README.md
Use the latest stable alpine 3.19 docker image instead of bookworm-slim.
Pros:
- About half the size, ~1GB -> ~500MB
- Zero vulnerabilities (down from almost 200)
- Builds so, so quickly
> docker: Alpine based container

- contrib/shell_utils/afpstats.in
While tinkering with the afpstats script, I thought it would be nice to give the output a more human readable format.
This is an example of what it looks like now:
```
name: dmark, pid: 396739, logintime: Apr 26 22:56:08, state: active, volumes: dmark's Home
name: dmark, pid: 397710, logintime: Apr 26 23:56:11, state: active, volumes: My AFP Volume
```
This is what it looks like after this PR:
```
Username         PID      Login time        State          Volumes
dmark            452547   Apr 28 21:58:50   active         Test Volume
dmark            451969   Apr 28 21:21:32   active         My AFP Volume
```
> Pretty formatting of afpstats output

- contrib/macusers/meson.build
- contrib/shell_utils/meson.build
- distrib/initscripts/meson.build
- doc/manpages/man1/asip-status.1.xml
- doc/manpages/man1/meson.build
- doc/manual/install.xml
- macros/grep-check.m4
- macros/perl-check.m4
- man/man1/meson.build
- meson.build
- make perl and grep build system checks optional
- do not build or install perl scripts when either is not found
- update documentation on perl requirements
- automated meson script formatting
> [2.4] Remove hard dependencies on perl and grep

- configure.ac
- etc/papd/lp.c
- etc/papd/lp.h
- meson.build
- meson_config.h
This commit:
- Fixes the missing rresvport function on linux systems using musl, credit @daimh
> [2.4] Fix missing rresvport function on systems using musl C library

- distrib/initscripts/rc.openrc.tmpl
We should only attempt to load timelord and a2boot if atalkd is running. Also register NBP entries on port 4 to be consistent with other init scripts.
> [2.4] Update rc.openrc.tmpl: a2boot and timelord depend on atalkd

- .github/workflows/build.yml
Notes:
- The archlinux docker container is not booted with systemd set up as the init system so  the initscript for systemd (the default init system on archlinux) fails with both autotools and meson.
- For some reason the meson /autotools compilation of afpd fails with an undeclared glib-related function when spotlight support is enabled. This does not occur on my archlinux vm.
> Add archlinux GitHub actions job

- config/netatalk.conf
- distrib/initscripts/atalkd.service.tmpl
- distrib/initscripts/rc.debian.tmpl
- distrib/initscripts/rc.openrc.tmpl
- distrib/initscripts/rc.redhat.tmpl
- distrib/initscripts/rc.solaris.tmpl
- distrib/initscripts/rc.suse.tmpl
- Bring back hostname-as-servicename logic to init scripts
- Enable appletalk services by default in netatalk.conf
- Disable charset env variables, which afpd already has built-in defaults for
(Pardon the trailing whitespace cleanup. I'm using an "opinionated" editor.)
> Set service name as hostname in init scripts

- macros/netatalk.m4
- meson.build
> Fix broken cracklib macro in autotools and meson

- bin/ad/meson.build
- bin/afppasswd/meson.build
- bin/misc/meson.build
- etc/afpd/meson.build
- etc/cnid_dbd/meson.build
- etc/netatalk/meson.build
This commit ensures that all executables are correctly linked to libatalk at build-time
> meson: Fix 'libatalk not found' error on NetBSD

- .github/workflows/build.yml
Introducing "start netatalk" and "stop netatalk" steps for the jobs. This constitutes a very simple sanity test that the netatalk/afpd deamon starts up and serves an AFP service on port 548
A 2s delay is inserted after starting netatalk until attempting to ping it with asip-status. This is because it always takes a moment for afpd to start up fully.
Note: There are slight differences between the "stop netatalk" steps in autotools and meson. This is because meson do not have support for post uninstall scripts. See https://github.com/mesonbuild/meson/issues/1974
Additional changes:
- Move Fedora from rawhide to latest (stable OS)
- Don't install soft requirements in the Fedora job
- Fix and enable the DragonflyBSD job (required `usesh: true` to enable the shell)
- Make the Alpine job …
> Start netatalk in GitHub CI jobs

- doc/ja/manpages/man1/ad.1.xml
- doc/ja/manpages/man1/afpldaptest.1.xml
- doc/ja/manpages/man1/afppasswd.1.xml
- doc/ja/manpages/man1/afpstats.1.xml
- doc/ja/manpages/man1/apple_dump.1.xml
- doc/ja/manpages/man1/asip-status.1.xml
- doc/ja/manpages/man1/dbd.1.xml
- doc/ja/manpages/man1/macusers.1.xml
- doc/ja/manpages/man1/netatalk-config.1.xml
- doc/ja/manpages/man5/afp.conf.5.xml
- doc/ja/manpages/man5/afp_signature.conf.5.xml
- doc/ja/manpages/man5/afp_voluuid.conf.5.xml
- doc/ja/manpages/man5/extmap.conf.5.xml
- doc/ja/manpages/man8/afpd.8.xml
- doc/ja/manpages/man8/cnid_dbd.8.xml
- doc/ja/manpages/man8/cnid_metad.8.xml
- doc/ja/manpages/man8/netatalk.8.xml
- doc/ja/manual/compile.xml
- doc/ja/manual/configuration.xml
- doc/ja/manual/install.xml
- doc/ja/manual/intro.xml
- doc/ja/manual/manual.xml.in
- doc/ja/manual/meson.build
- doc/ja/manual/upgrade.xml
- doc/manual/.gitignore
- doc/manual/generate_compile_docs.py
- Translate new and changed strings
- Standardize punctuation to 。、
- Autoformat XML with XMLmind
- Generate Japanese compile.xml
- Regenerate the English compile.xml
> docs: Update Japanese manual for 3.2.0

- Dockerfile
- config/afpd.conf.tmpl
- config/netatalk.conf
- contrib/shell_utils/docker-entrypoint.sh
- doc/manpages/man5/afpd.conf.5.xml
- doc/manual/configuration.xml
- etc/afpd/afp_options.c
With embedded wolfssl DHX is now built in the standard configuration, enable this as the default afpd configuration, as well as the default Docker container configuration.
> [2.4] Enable the DHX UAM with embedded WolfSSL in default conf

- config/AppleVolumes.default.tmpl
- config/afp_ldap.conf
- config/afpd.conf.tmpl
- config/atalkd.conf
- config/papd.conf
- doc/manpages/man5/atalkd.conf.5.xml
- doc/manpages/man5/papd.conf.5.xml
- doc/manpages/man8/atalkd.8.xml
- doc/manpages/man8/papd.8.xml
- Move docs and examples from conf files to man pages, leaving only a file description and reference to the man page in the former
- Move docs concerning the conf file from the daemon man pages to the conf file man pages
- Grammar and organization touchups
- Format with XMLmind
> [2.4] docs: Move documentation from conf file templates to man pages

- doc/manpages/man5/afpd.conf.5.xml
- etc/afpd/afp_options.c
- etc/afpd/uam.c
- etc/uams/uams_pam.c
- include/atalk/globals.h
- include/atalk/uam.h
Resolves https://github.com/Netatalk/netatalk/issues/1001 and https://github.com/Netatalk/netatalk/issues/1004
Sorry for the noise in the changeset. Pulsar and XMLmind are opinionated when it comes to trailing line endings etc.
> [2.4] afpd: Remove multiple deprecated options

- distrib/initscripts/.gitignore
- distrib/initscripts/Makefile.am
- distrib/initscripts/meson.build
- meson.build
- meson_options.txt
- BerkeleyDB detection on openSUSE: Overlooked backport of https://github.com/Netatalk/netatalk/pull/875
- Bring disable-privileged-install into Meson, and apply it consistently across Meson and existing makefiles https://github.com/Netatalk/netatalk/issues/1024
- Correct naming when installing NetBSD rc scripts. https://github.com/Netatalk/netatalk/issues/1030
> [2.4] meson: Fix platform specific issues

- distrib/initscripts/netatalkd.tmpl
An overlooked backport from 3.x
> [2.4] netatalkd: Netatalk service can only be stopped if it is already running

- etc/afpd/nfsquota.c
- meson.build
This is a small backport from the 3.x quota PR. It explicitly disables quota when either rpcsvc or quota isn't found. This addresses compilation errors on DragonflyBSD.
> [2.4] quota: Stricter check for rpcsvc in meson

- .github/workflows/build.yml
- NEWS
- configure.ac
- etc/afpd/Makefile.am
- etc/afpd/afp_options.c
- etc/afpd/meson.build
- etc/afpd/nfsquota.c
- etc/afpd/quota.c
- etc/afpd/unix.h
- etc/afpd/volume.c
- include/atalk/volume.h
- libatalk/compat/Makefile.am
- libatalk/compat/meson.build
- libatalk/compat/rquota_xdr.c
- macros/Makefile.am
- macros/netatalk.m4
- macros/quota-check.m4
- macros/summary.m4
- meson.build
- meson_config.h
- meson_options.txt
- test/afpd/Makefile.am
- test/afpd/meson.build
As per discussion in https://github.com/Netatalk/netatalk/issues/1028, bring back quota which was removed within this release cycle.
- Revert https://github.com/Netatalk/netatalk/issues/493
- Forward-port NetBSD patch that was only in 2.x https://github.com/Netatalk/netatalk/commit/bf1bbf20b105c69712d786465ce3452c3617af9f
- Modernize quota code, removing ancient platform workarounds
- Linux ifdefs for code introduced with https://github.com/Netatalk/netatalk/commit/450114e8c52574c5444d856e8a0208f2bbaab80c (caused build errors for DragonflyBSD; might be a cleaner way to do this...)
- Forward-port Meson build system scripts from 2.x with modifications
> Reintroduce quota support, modernized with meson build system

- .github/workflows/build.yml
- NEWS
- libatalk/compat/rquota_xdr.c
- macros/quota-check.m4
- meson.build
- meson_config.h
configuring with quota and libtirpc -- turned out that we need a capability check to make this work on Fedora
tracker isn't a dependency of tracker-devel in Fedora, so let's install it explicitly
> GitHub CI: quota and tracker on Fedora

- meson.build
> [2.4] meson: Check for ldap_initialize symbol

- distrib/initscripts/meson.build
One install step was missing from the Meson script for the Solaris init script, as compared to Autotools.
> [2.4] meson: Missing install step for Solaris

- contrib/shell_utils/meson.build
Update the meson build script not to install :
-            make-casetable.pl
-            make-precompose.h.pl
These are perl scripts that generate character encoding / unicode source files, and are of use only for netatalk developers. AFAIK. :)
Note that the Autotools build system does not install these files.
> [2.4] meson: Do not install char encoding scripts

- contrib/shell_utils/meson.build
This fixes two issues with the shell_utils meson script:
- afpstats should only be processed & installed when Perl+grep are detected (forgot to update this after rewriting it in Perl)
- Do not install dev scripts (FCE sample script, unicode header generator script, etc.)
> meson: afpstats should depend on Perl; don't install dev scripts

- contrib/a2boot/meson.build
- contrib/timelord/meson.build
- etc/papd/meson.build
- meson.build
This commit:
- Fixes the logic of the UCS-2-INTERNAL macro that was causing the crash (credit: @NJRoadfan)
- Creates the required empty spooldir on install
- Fixes the linking of a2boot and timelord with libatalk
> [2.4] meson: Fix papd crash when cupsautoadd is enabled

- .github/workflows/build.yml
The tracker-miners package adds the missing daemon command to tracker3 on Alpine Linux
> Alpine workflow: Add missing tracker-miners package

- .github/workflows/build.yml
- bin/ad/meson.build
- bin/afppasswd/meson.build
- bin/misc/meson.build
- doc/ja/manual/compile.xml
- doc/manual/compile.xml
- etc/afpd/meson.build
- etc/afpd/unix.h
- etc/cnid_dbd/meson.build
- etc/netatalk/meson.build
- libatalk/acl/meson.build
- libatalk/compat/meson.build
- libatalk/compat/rquota_xdr.c
- libatalk/dsi/meson.build
- libatalk/meson.build
- libatalk/vfs/meson.build
- meson.build
- meson_options.txt
- test/afpd/meson.build
This changeset refines the meson build system:
- Enables quota support on all flavours of linux and BSD (including macOS)
- Adds the quota provider to the configuration summary
- Adds a user option to disable LDAP support
- Sets dependencies according to user configuration
- Improves the syntax of the ACL macro
> meson: Address various issues with the meson build system

- .github/workflows/build.yml
- bin/ad/meson.build
- bin/afppasswd/meson.build
- bin/misc/meson.build
- etc/afpd/meson.build
- etc/afpd/unix.h
- etc/cnid_dbd/meson.build
- libatalk/acl/meson.build
- libatalk/compat/meson.build
- libatalk/compat/rquota_xdr.c
- libatalk/dsi/meson.build
- libatalk/meson.build
- libatalk/vfs/meson.build
- meson.build
- meson_options.txt
- test/afpd/meson.build
This changeset refines the meson build system:
- Enables quota support on all flavours of linux and BSD (including macOS)
- Adds the quota provider to the configuration summary
- Adds user options to disable gssapi, cracklib and LDAP support
- Sets dependencies according to user configuration
- Improves the syntax of the ACL macro
- Automates Berkeley DB library detection on macOS
> [2.4] meson: Address various issues with the meson build system

- etc/afpd/unix.h
- libatalk/compat/rquota_xdr.c
- libatalk/meson.build
- meson.build
- meson_config.h
This changeset:
- Fixes quota support on macOS hosts
- Restores missing configuration option for linux hosts (taken from autotools netatalk.m4 macro)
- Removes obsolete quota configuration data for linux and macOS hosts
macOS quota support tested on Sonoma host with Mac OS 9 client
> [2.4] meson: Fix issues with quota support on macOS and linux hosts

- contrib/a2boot/meson.build
When built with meson, a2boot wasn't able to find the boot block files due to invalid path. Fixes #1095
> [2.4] a2boot - Update meson.build file paths

- .github/workflows/build.yml
Also removes the shallow clone rule. The job is fast enough without it.
> Update the SonarCloud scanner command

- Dockerfile
Alpine 3.20.1 has two busybox security patches. Let's bump from 3.19
https://alpinelinux.org/posts/Alpine-3.20.1-released.html
https://alpinelinux.org/posts/Alpine-3.20.0-released.html
> docker: Bump to Alpine 3.20 base image

- etc/afpd/unix.h
Missing backport of fix in main branch
> [2.4] meson: Fix MAXQUOTAS redefined warnings on linux systems

- meson.build
If you try to do `-Dwith-rpath=true` you get error
```
../meson.build:414:7: ERROR: Tried to access unknown option 'enable-rpath'.
```
I think that part should just be removed, no?
> meson: with-rpath syntax is invalid

- doc/ja/manual/intro.xml
- doc/manual/intro.xml
This is to clarify that the manual's legal notice to not only regard the documentation, but also the software package itself.
And then, adds the SSLeay legal notice to comply with the terms of the source files we borrowed from OpenSSL.
Formatting applied by the XMLmind editor.
> docs: Indicate license for software package, and add SSLeay notice

- doc/manual/intro.xml
This is to clarify that the manual's legal notice to not only regard the documentation, but also the software package itself.
And then, adds the SSLeay legal notice to comply with the terms of the source files we borrowed from OpenSSL.
Formatting applied by the XMLmind editor.
> [2.4] docs: Indicate license for software package, and add SSLeay notice

- distrib/initscripts/Makefile.am
- distrib/initscripts/meson.build
- macros/netatalk.m4
This means Debian aligns with all the other known Linux distros, so the special case in our build scripts is removed.
Also sorting the options a bit for readability.
> Debian Trixie expects systemd scripts in /usr/lib

- libatalk/unicode/charsets/mac_roman.h
All code in this file is lifted verbatim from lib/mac_roman.h in libiconv.
Therefore, adding the same copyright year and author as in libiconv 1.9.2 which was contemporaneous to when mac_roman.h was added to Netatalk.
https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.9.2.tar.gz
> Add copyright for mac_roman.h

- libatalk/unicode/charsets/mac_roman.h
All code in this file is lifted verbatim from lib/mac_roman.h in libiconv.
Therefore, adding the same copyright year and author as in libiconv 1.9.2 which was contemporaneous to when mac_roman.h was added to Netatalk.
https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.9.2.tar.gz
> [2.4] Add copyright for mac_roman.h

- distrib/initscripts/atalkd.service.tmpl
In some configurations, the NBP registrations of "workstation" and "netatalk" may fail. Don't attempt to restart the atalkd service as these are not critical failures. Note, this fixes the issue that lead to these changes being reverted in #473.
> [2.4] Don't attempt to restart atalkd if NBP registrations fail

- etc/afpd/mangle.c
- etc/papd/lp.c
- etc/papd/printcap.c
- libatalk/cnid/last/cnid_last.c
- libatalk/compat/rquota_xdr.c
- libatalk/util/volinfo.c
Also includes trailing space cleanup, caused by my editor.
> [2.4] Cleanup of copyright headers to make them more scanner friendly

- etc/afpd/auth.c
- etc/afpd/directory.c
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_pam.c
- etc/uams/uams_passwd.c
* Check that input buffer can accommodate null terminator
* Input buffer null pointer and length checks
> CVE-2024-38439,CVE-2024-38440,CVE-2024-38441: Harden user login

- etc/afpd/auth.c
- etc/afpd/directory.c
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_pam.c
- etc/uams/uams_passwd.c
* Check that input buffer can accommodate null terminator
* Input buffer null pointer and length checks
> [2.4] CVE-2024-38439,CVE-2024-38440,CVE-2024-38441: Harden user login

- doc/ja/manual/install.xml
- doc/manual/install.xml
This is to avoid talking about specific compression techniques (we currently don't distribute bzip2)
> docs: Rephrase tarball section of manual

- .github/workflows/build.yml
- INSTALL.md
- bin/afppasswd/afppasswd.c
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_dhx_passwd.c
- etc/uams/uams_pgp.c
- etc/uams/uams_randnum.c
- meson.build
- meson_config.h
This commit enables meson to detect if a native WolfSSL library with the correct configuration is present and use it in preference to built-in SSL support
> meson: Prioritize native WolfSSL package over built-in SSL library if it has the correct configuration

- etc/afpd/meson.build
- meson.build
- meson_options.txt
- test/afpd/meson.build
Tested on Debian 11 VM with OpenSLP installed from source (Debian does not have a package for OpenSLP)
> meson: Restore SLP (srvloc) support

- config/pam/meson.build
- meson.build
- meson_options.txt
Restore missing option to set PAM config path
Install PAM config file to correct location
Fix PAM_SESSION entry in PAM config file for Debian/SuSE
> meson: Fix errors in PAM support macro

- config/pam/meson.build
- meson.build
- meson_options.txt
Restore missing option to set PAM config path
Install PAM config file to correct location
Fix PAM_SESSION entry in PAM config file for Debian/SuSE
> [2.4] meson: Fix errors in PAM support macro

- meson.build
- meson_options.txt
This commit fixes errors in setting the correct dbus-daemon and dbus-sysconf path variables. The variables now match those set by autotools.
> meson: Fix operation of D-Bus path macros

- macros/libgcrypt.m4
> autotools: gcc 8.5 expects explicit library flags for libgcrypt

- macros/libgcrypt.m4
> [2.4] autotools: gcc 8.5 expects explicit library flags for libgrypt

- Dockerfile
- NEWS
- meson.build
This restores functionality of the Docker container in 2.4:
- Missing fix for https://github.com/Netatalk/netatalk/pull/1155 in 2.4
- openssl needs to be a LIB_DEV, otherwise it gets purged before exporting the layers
- avahi compatibility libraries are required
- Disabling quota for now, as I was seeing errors in the afpd logs
- More explicit configuration flags
> [2.4] Fix Zeroconf on Alpine Linux, and in the Docker configuration

- README.md
- contrib/shell_utils/docker-entrypoint.sh
This option exists in the 2.x docker configuration. It can be handy for 3.x as well.
> docker: Add option to enable ClearText and Guest UAMs

- doc/ja/manpages/man1/netatalk-config.1.xml
- doc/ja/manual/Makefile.am
- doc/ja/manual/meson.build
- doc/manpages/man1/netatalk-config.1.xml
- doc/manual/Makefile.am
- doc/manual/meson.build
netatalk-config manual page reference entries have inconsistent naming: some with and some without hyphen. This uses the hyphen across the board.
Note that this change was made in the 2.x branch long time ago
> docs: Standardize reference entry naming for netatalk-config man page

- doc/manual/meson.build
An oversight from when the meson build script was created
> [2.4] meson: Generate papd.conf manual html page

- meson.build
Fixes the syntax of the with-rpath option.
This commit also removes the obsolete atalk_libname path variab
> [2.4] meson: Remove obsolete 64 bit library check

- meson.build
This commit also removes the obsolete atalk libname path variable
> meson: Remove obsolete 64 bit library check

- .github/workflows/build.yml
- bin/ad/meson.build
- bin/afppasswd/meson.build
- bin/misc/meson.build
- etc/afpd/meson.build
- etc/cnid_dbd/meson.build
- etc/netatalk/meson.build
- etc/uams/meson.build
- meson.build
This change enables rpath for compiled binaries only when with-rpath is enabled, or when the OS is NetBSD or Solaris[h]. There might a more graceful way to do this than duplicating each executable() call, but I couldn't find out how.
It also tweaks the GitHub CI actions to:
1. Use the latest stable Debian image, and with systemd instead of sysv (Trixie seems to finally do away with sysv init script wrappers.) We lose the ability to test the dynamic execution of netatalk on Debian, unfortunately, but we still test it on Ubuntu, so... 
2. Turn off kerberos for openSUSE, since they keep breaking the dependencies for their krb5 package.
3. Bumps the openldap library version for FreeBSD
> meson: Enable rpath for binaries only when with-rpath is enabled

- .github/workflows/build.yml
- bin/ad/meson.build
- bin/adv1tov2/meson.build
- bin/aecho/meson.build
- bin/afppasswd/meson.build
- bin/getzones/meson.build
- bin/megatron/meson.build
- bin/misc/meson.build
- bin/nbp/meson.build
- bin/pap/meson.build
- bin/psorder/meson.build
- bin/uniconv/meson.build
- contrib/a2boot/meson.build
- contrib/timelord/meson.build
- etc/afpd/meson.build
- etc/atalkd/meson.build
- etc/cnid_dbd/meson.build
- etc/papd/meson.build
- etc/psf/meson.build
- etc/uams/meson.build
- meson.build
This change enables rpath for compiled binaries only when with-rpath is enabled, or when the OS is NetBSD or Solaris[h]. There might a more graceful way to do this than duplicating each executable() call, but I couldn't find out how.
It also tweaks the GitHub CI actions to:
Use the latest stable Debian image, and with systemd instead of sysv (Trixie seems to finally do away with sysv init script wrappers.) We lose the ability to test the dynamic execution of netatalk on Debian, unfortunately, but we still test it on Ubuntu, so...
Turn off kerberos for openSUSE, since they keep breaking the dependencies for their krb5 package.
Bumps the openldap library version for FreeBSD
> [2.4] meson: Enable rpath for binaries only when with-rpath is enabled

- .github/workflows/build.yml
- etc/afpd/meson.build
- etc/uams/meson.build
- meson.build
- test/afpd/meson.build
Validate the kerberos flag in addition to gssapi capability check when enabling the krb5 UAM.
Also apply the have-krb5-uam capability flag rather than the enable flag when injecting dependencies across the build system.
> meson: Require kerberos before enabling krb5 UAM, not just GSSAPI

- .github/workflows/build.yml
- etc/uams/meson.build
- meson.build
- meson_config.h
- meson_options.txt
Backport the build system check for Kerberos headers / APIs from main. Check for both kerberos and gssapi before enabling the krbV UAM.
> [2.4] meson: Introduce check for Kerberos API when building krbV UAM

- .github/workflows/build.yml
- meson.build
In https://github.com/Netatalk/netatalk/pull/1207 the broad legacy check for 64 bit library paths was removed. This PR restores a limited version of that for sunos specifically.
This also adds tentative CI workflow steps for building on Solaris with Meson (currently disabled, pending an update to the solaris vmactions image.)
> meson: Restore linking with 64-bit libdb on Solaris

- .github/workflows/build.yml
- meson.build
In https://github.com/Netatalk/netatalk/pull/1211 the broad legacy check for 64 bit library paths was removed. This PR restores a limited version of that for sunos specifically.
This also adds tentative CI workflow steps for building on Solaris with Meson (currently disabled, pending an update to the solaris vmactions image.)
> [2.4] meson: Restore linking with 64-bit libdb on Solaris

- .github/workflows/build.yml
- meson.build
- meson_options.txt
This introduces a `with-pkgconfdir-path` Meson option.
It also removes the hard-coded "netatalk/" path suffix to sysconfdir as the default pkgconfdir.
> [2.4] meson: Introduce pkgconfdir override option

- config/meson.build
- config/pam/meson.build
The old logic was buggy, and lead to config files not being installed properly sometimes.
> [2.4] meson: Correct overwrite install logic for package config files

- config/meson.build
- config/pam/meson.build
- meson.build
The old logic was buggy, and lead to config files not being installed properly sometimes.
> meson: Correct overwrite install logic for afp.conf

- libatalk/meson.build
This should bring the resulting library symlinks in line with what autotools produce
> meson: Define long-form libatalk soversion as 18.0.0

- libatalk/meson.build
As a side note, the 2.x libatalk wasn't versioned in Autotools. The soversion scheme was introduced with 3.0.0.
In hindsight I don't know it was the right choice to version 2.x libatalk, but what's done is done.
> [2.4] meson: Define long-form libatalk soversion as 18.0.0

- libatalk/meson.build
This aligns with the versioning produced by Autotools.
The soversion was previously set to 18, which was a mistake from when backporting the Meson build scripts from 3.x.
Compare https://github.com/Netatalk/netatalk/pull/269
Versions before 3.0.0-beta2 had libatalk soversion 0.0.0, while 3.1.9 and later got soversion 18.0.0
> [2.4] meson: Adjust libatalk soversion to 0.0.0

- Dockerfile
- contrib/shell_utils/docker-entrypoint.sh
Changing the default pkgconfdir path caused existing 2.x docker containers to start failing. This moves config files from the old /usr/local/etc/netatalk to /usr/local/etc to accommodate volumes created by docker images <2.4.3
> docker: Move config files from the old pkgconfdir location

- .github/workflows/build.yml
- libatalk/Makefile.am
The libatalk binary API versioning scheme was removed after discussion in GitHub #262 and effective with v3.1.16
However, since then, external consumers of libatalk have been found, such as macipgw. Additionally, ABI versioning allows distinguishing 3.x libatalk (18.0.0) from 2.x libatalk (0.0.0) in the wild.
This changeset also includes a modification to the OpenBSD CI job, due to bug https://github.com/Netatalk/netatalk/issues/1262
> autotools: Restore ABI versioning of libatalk, set to 18.0.0

- etc/afpd/afpstats_obj.c
- etc/cnid_dbd/cmd_dbd_scanvol.c
- libatalk/compat/rquota_xdr.c
- Fix buffer overflow warning in etc/cnid_dbd/cmd_dbd_scanvol.c
- Fix deprecated-non-prototype warnings in rquota_xdr.c
- Fix incompatible pointer types discards qualifiers warning in afpstats_obj.c
> Fix some compiler warnings generated by clang on macOS

- .github/workflows/build.yml
- distrib/initscripts/meson.build
- meson.build
- meson_options.txt
Introduce an 'auto' init-style option, selected by default, which attempts to cleanly choose the appropriate init system style for the host OS.
> meson: Detect init style and allow multiple init styles

- .github/workflows/build.yml
- Dockerfile
- bin/afppasswd/meson.build
- etc/uams/meson.build
- meson.build
- subprojects/wolfssl/meson.build
- The bundled libwolfssl library has to be explicitly installed on at least Alpine Linux and macOS
- Refactor the bundled SSL override logic to reduce code duplication
- Fix syntax error in libiconv path assignment
- Supply missing unicode data and perl build dependencies in Dockerfile
- Supply missing avahi dependency for Arch CI job
> meson: Install wolfssl lib, refactor SSL logic, fix Dockerfile

- meson.build
Fixing a mistake from a Meson refactor early on.
> [2.4] meson: Fix syntax error with libiconv path

- meson.build
Fixing a mistake from a Meson refactor early on.
> meson: Fix syntax error with libiconv path

- meson_options.txt
Fixing a copy-paste mistake from when the meson build system was set up.
> meson: Correct description for with-manual option

- .github/workflows/build.yml
- doc/html-www.xsl.in
- doc/ja/html-www.xsl.in
- doc/ja/html.xsl.in
- doc/ja/meson.build
- doc/meson.build
- meson.build
- meson_options.txt
Turns the `with-manual` option into a combo option with none, local, and www as options. Default is local.
The www option is only meant for publishing on the web, i.e. the netatalk homepage.
> Option to build html manual for local or Web consumption

- meson.build
Fixing a copy-paste mistake from when the Meson build system was first set up.
> meson: Correct prefix lookup for tracker-control

- meson.build
The default OPEN_NOFOLLOW_ERRNO substitution comes after the platform specific ones.
> meson: default OPEN_NOFOLLOW_ERRNO overwrites platform customization

- meson.build
The default OPEN_NOFOLLOW_ERRNO substitution comes after the platform specific ones.
> [2.4] meson: default OPEN_NOFOLLOW_ERRNO overwrites platform customization

- meson.build
Fix an incorrect nesting of dtags under rpath.
> meson: Don't make dtags depend on rpath

- meson.build
Fix an incorrect nesting of dtags under rpath.
> [3.2] meson: Don't make dtags depend on rpath

- meson.build
The exact same check for posix threads is done further down in the main script.
> [3.2] meson: Remove duplicate dependency check for posix threads

- meson.build
The exact same check for posix threads is done further down in the main script.
> [2.4] meson: Remove duplicate dependency check for posix threads

- meson.build
Explicit output in summary when DHX or DHX2 aren't built. And correct warning when SSL dependencies missing.
> meson: Better output when cryptographic UAMs aren't built

- meson.build
Explicit output in summary when DHX or DHX2 aren't built.
> [2.4] meson: Better output when cryptographic UAMs aren't built

- meson.build
Explicit output in summary when DHX or DHX2 aren't built.
> [3.2] meson: Better output when cryptographic UAMs aren't buil

- bin/ad/meson.build
- bin/afppasswd/meson.build
- bin/misc/meson.build
- etc/afpd/meson.build
- etc/cnid_dbd/meson.build
- etc/netatalk/meson.build
- etc/uams/meson.build
- meson.build
Instead of repeating each executable target with and without rpath, this defines a global variable that controls the same.
> meson: Better way to handle rpath executable targets

- test/afpd/meson.build
The integration tests are designed to be run sequentially in order. This stops Meson from trying to run them out of order or in parallel.
> [3.2] meson: Prioritize tests and run single-threaded to avoid race condition

- test/afpd/meson.build
The integration tests are designed to be run sequentially in order. This stops Meson from trying to run them out of order or in parallel.
> [2.4] meson: Prioritize tests and run single-threaded to avoid race condition

- .github/workflows/build.yml
- test/afpd/meson.build
The integration tests are designed to be run sequentially in order. This stops Meson from trying to run them out of order or in parallel.
> meson: Prioritize tests and run single-threaded to avoid race condition

- bin/ad/meson.build
- bin/afppasswd/meson.build
- bin/misc/meson.build
- etc/afpd/meson.build
- etc/cnid_dbd/meson.build
- etc/netatalk/meson.build
- etc/uams/meson.build
- meson.build
Instead of repeating each executable target with and without rpath, this defines a global variable that controls the same.
> [3.2] meson: Better way to handle rpath executable targets

- etc/uams/meson.build
- meson.build
- Correct handling of Randnum/DHX/PGP UAM build scripts when libcrypto is missing
- Correct summary status of Randnum and PPG when libcrypto is missing
- Refactoring
> [3.2] meson: Refactor libcrypto check and print better status messages

- .github/workflows/build.yml
- doc/ja/manual/meson.build
- doc/manual/meson.build
- doc/meson.build
- meson.build
- meson_options.txt
- Install generated html manual files into a htmldocs subdir to doc/netatalk
- Generate the Japanese localized html manual files only when building for Web publishing
- Install readme files, optionally processed from markdown to plain text (new `with-readmes` option)
> meson: Install more documentation by default and organize it better

- etc/uams/meson.build
- meson.build
- Build Randnum and PGP UAMs only when the SSL dependency is present.
- In the summary, print the access control method separately, and have simple yes/no for individual UAMs
> meson: Refactor UAM detection and simplify summary

- bin/ad/meson.build
- bin/adv1tov2/meson.build
- bin/aecho/meson.build
- bin/afppasswd/meson.build
- bin/getzones/meson.build
- bin/megatron/meson.build
- bin/misc/meson.build
- bin/nbp/meson.build
- bin/pap/meson.build
- bin/psorder/meson.build
- bin/uniconv/meson.build
- contrib/a2boot/meson.build
- contrib/timelord/meson.build
- etc/afpd/meson.build
- etc/atalkd/meson.build
- etc/cnid_dbd/meson.build
- etc/papd/meson.build
- etc/psf/meson.build
- etc/uams/meson.build
- meson.build
Instead of repeating each executable target with and without rpath, this defines a global variable that controls the same.
> [2.4] meson: Better way to handle rpath executable targets

- bin/afppasswd/meson.build
- etc/uams/meson.build
- meson.build
- sys/netatalk/meson.build
- Build Randnum and PGP UAMs only when the SSL dependency is present.
- In the summary, print the access control method separately, and have simple yes/no for individual UAMs
- Make use of the use_glibc_at_header flag
> [2.4] meson: Refactor libcrypto check and print better status messages

- .github/workflows/build.yml
- test/afpd/afpfunc_helpers.c
Using `type` as the data type at the same time as `type` as the variable name causes the compiler on NetBSD to bail out.
This PR also includes changes to the GitHub CI workflow to build and run the tests on NetBSD, in addition to some general cleanup of the test steps elsewhere.
> [2.4] Avoid using reserved keyword to build the tests on NetBSD

- .github/workflows/build.yml
- test/afpd/afpfunc_helpers.c
Using `type` as the data type at the same time as `type` as the variable name causes the compiler on NetBSD to bail out.
This PR also includes changes to the GitHub CI workflow to build and run the tests on NetBSD, in addition to some general cleanup of the test steps elsewhere.
> [3.2] Avoid using reserved keyword to build the tests on NetBSD

- etc/uams/meson.build
- libatalk/meson.build
Use the standard `library()` target for libatalk and UAM libraries, which makes the build system sensitive to the `-Ddefault_library` option to control whether to build static, shared, or both libraries.
The UAM libraries need a few workarounds since they're not true shared libraries, but rely on symbols from other netatalk modules.
Note that building static libraries on macOS doesn't work. It didn't work before, and it doesn't work after this change.
> meson: Allow choosing shared or static libraries to build

- .github/workflows/build.yml
- libatalk/cnid/meson.build
- libatalk/cnid/mysql/meson.build
- meson.build
- meson_options.txt
- When MySQL dependencies aren't available, fall back to MariaDB
- Introduce a `with-cnid-mysql-backend' option
- Remove obsolete `with-mysql-config' option
- Install *SQL dependencies in GitHub CI workflows
> [3.2] meson: Control the MySQL CNID backend, and support MariaDB

- .github/workflows/build.yml
- libatalk/cnid/meson.build
- libatalk/cnid/mysql/meson.build
- meson.build
- meson_options.txt
- When MySQL dependencies aren't available, fall back to MariaDB
- Introduce a `with-cnid-mysql-backend' option
- Remove obsolete `with-mysql-config' option
- Install *SQL dependencies in GitHub CI workflows
Note that the only platform where I failed to build the mysql backend, is Solaris 11. The stock mysql package is `mysql-57` which I think is a bit too old, and building mariadb from scratch in the CI workflow is too resource intensive and slow.
> meson: Control the MySQL CNID backend, and support MariaDB

- .github/workflows/build.yml
- distrib/initscripts/meson.build
Non-system base packages should install their init scripts into `/usr/local/etc/rc.d` on FreeBSD.
> meson: Install FreeBSD init script into correct location

- .github/workflows/build.yml
- distrib/initscripts/meson.build
- macros/netatalk.m4
Non-system base packages should install their init scripts into `/usr/local/etc/rc.d` on FreeBSD.
> [3.2] meson: Install FreeBSD init script into correct location

- etc/uams/meson.build
- libatalk/meson.build
This change respects the `-Ddefault_library` meson option and enables or disables the building or shared or static libraries.
> [3.2] meson: Allow choosing shared or static libraries to build

- distrib/initscripts/meson.build
- meson_options.txt
The `with-init-dir` build system option overrides the default that's hard coded in this build script.
One known shortcoming is that it cannot be used with the `debian` init style since this applies both to sysv and systemd dirs which will break things.
> [3.2] meson: Implement with-init-dir option

- .github/workflows/build.yml
- meson.build
Fedora doesn't expose a `mariadb` dependency, but only `libmariadb` when using the recommended `mariadb-connector-c-devel` package.
> meson: Look for libmariadb dependency to appease Fedora

- .github/workflows/build.yml
- meson.build
Fedora doesn't expose a `mariadb` dependency, but only `libmariadb` when using the recommended `mariadb-connector-c-devel` package.
> [3.2] meson: Look for libmariadb dependency to appease Fedora

- .github/workflows/build.yml
DragonflyBSD, FreeBSD, and macOS (Homebrew) ship WolfSSL libraries that are compatible with Netatalk 4.x.
Adding to Debian/Ubuntu for a total of 5 known OSes that provide native WolfSSL support.
> GitHub CI: Build with system provided WolfSSL library

- meson.build
Bail out early if the compiler can't compile any C code.
> meson: Do a compiler sanity check before header checks

- meson.build
The build script expected the have_atfuncs check to always succeed. This change avoids an error when it fails.
> meson: Declare have_atfuncs globally to avoid failure later

- meson.build
Bail out early if the compiler can't compile any C code.
> [3.2] meson: Do a compiler sanity check before header checks

- meson.build
Bail out early if the compiler can't compile any C code.
> [2.4] meson: Do a compiler sanity check before header checks

- meson.build
The build script expected the have_atfuncs check to always succeed. This change avoids an error when it fails.
> [3.2] meson: Declare have_atfuncs globally to avoid failure later

- meson.build
The build script expected the have_atfuncs check to always succeed. This change avoids an error when it fails.
> [2.4] meson: Declare have_atfuncs globally to avoid failure later

- .github/workflows/build.yml
- meson_options.txt
The PGP UAM was disabled by default some time after branching off 3.2. I think it should be treated as the other UAMs.
> meson: Build the PGP UAM by default

- DOCKER.md
- README.md
- meson.build
- Break out Docker section into a separate readme
- Overheal the contents of the main readme
- Install markdown readmes only when conversion is available
> Create Docker readme; install only converted markdown readme

- config/meson.build
Installing the exact same README in a parent and child dir seems superfluous to me.
> meson: Install only one CNID README

- .github/workflows/build.yml
- distrib/initscripts/meson.build
- meson.build
- meson_options.txt
This turns the `-Dwith-init-style` from the combo type to the array type. It takes a list of options like this:
```
-Dwith-init-style=openrc,systemd
```
Note that you cannot use `-Dwith-init-dir` when you select multiple init styles since it will affect all of them.
As part of the changeset, I also remove the platform variants of cross-platform init systems (openrc and systemd) because they all behave the same now with the same standard paths. If a future OS uses a different path, you the with-init-dir override.
> meson: Allow selecting multiple init styles

- .github/workflows/build.yml
- meson.build
Use `/etc/os-release` to detect which Linux distro we are running on.
> meson: Detect Linux distro and choose an appropriate init style

- config/README
- config/meson.build
This partially reverts https://github.com/Netatalk/netatalk/pull/1367 because it turns out we rely on the build system to create the CNID subdir used to store CNID databases.
> Flesh out CNID README and put it in the proper subdir

- doc/DEVELOPER
- doc/README.AppleTalk
- doc/manual/appletalk.xml
- doc/manual/manual.xml.in
- doc/manual/meson.build
- doc/meson.build
This brings over the AppleTalk docs from 2.x. Some more copy editing will be required as we go along (depending on specific solutions and features.)
> Merge the brunt of AppleTalk documentation

- .github/workflows/build.yml
- etc/uams/uams_dhx2_pam.c
- etc/uams/uams_dhx2_passwd.c
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_pgp.c
- meson.build
- meson_config.h
- meson_options.txt
- Building of DHX/DHX2/PGP/PAM UAMs are controlled by Meson flags now, so the C macros aren't needed
- The largefile fallbacks are long gone from the codebase, so let's make largefile mandatory
> Make largefile mandatory, and clean up Meson controlled features

- doc/html.xsl.in
- doc/ja/html.xsl.in
- doc/manual/meson.build
- doc/manual/netatalk.css
- doc/meson.build
- meson_options.txt
- New meson option `-Dwith-manual-l10n` which takes an array of locales (currently only one, `ja`). Default is empty array, which leads to only the English l10n being built.
- Brings over the netatalk.css stylesheet from the netatalk-homepage repo and uses it when building the manual for local consumption.
> meson: Introduce option to control which manual l10n to build

- meson.build
Contemporary gcc fails with the old -R linker argument. Moreover, the "new dtags" override is redundant these days.
> meson: Use modern linker flag for rpath, remove dtag override

- meson.build
Contemporary gcc fails with the old -R linker argument. Moreover, the "new dtags" override is redundant these days.
> [3.2] meson: Use modern linker flag for rpath, remove dtag override

- meson.build
Contemporary gcc fails with the old -R linker argument.
> meson: Use modern linker flag for rpath

- .github/workflows/build.yml
- config/libatalk.conf.in
- config/meson.build
- libatalk/meson.build
- meson_options.txt
- Run ldconfig on glib based Linux as an install hook, so that the libatalk shared library path can be cached.
- Install a config file to `/etc/ld.so.conf.d` if needed to enable ldconfig to find libatalk.
- Introduce a `-Dwith-install-hooks` boolean option to disable this, if running in a non-privileged mode.
- In the CI workflow: run netatalk -V on OSes that lack an init system.
> meson: Refresh the dynamic linker cache when installing on Linux

- .github/workflows/build.yml
- config/libatalk.conf.in
- config/meson.build
- libatalk/meson.build
- meson_options.txt
- Run ldconfig on glib based Linux as an install hook, so that the libatalk shared library path can be cached.
- Install a config file to `/etc/ld.so.conf.d` if needed to enable ldconfig to find libatalk.
- Introduce a `-Dwith-install-hooks` boolean option to disable this, if running in a non-privileged mode.
- In the CI workflow: run netatalk -V on OSes that lack an init system.
> [3.2] meson: Refresh the dynamic linker cache when installing on Linux

- .github/workflows/build.yml
- config/libatalk.conf.in
- config/meson.build
- libatalk/meson.build
- meson_options.txt
- Run ldconfig on glib based Linux as an install hook, so that the libatalk shared library path can be cached.
- Install a config file to `/etc/ld.so.conf.d` if needed to enable ldconfig to find libatalk.
- Introduce a `-Dwith-install-hooks` boolean option to disable this, if running in a non-privileged mode.
- In the CI workflow: run netatalk -V on OSes that lack an init system.
> [2.4] meson: Refresh the dynamic linker cache when installing on Linux

- doc/ja/manual/meson.build
- doc/manual/meson.build
Previously, all generated html pages were interspersed with other docs. This allows for a cleaner separation.
> [3.2] meson: Install htmldocs into htmldocs subdir

- doc/meson.build
- meson_options.txt
New option `-Dwith-manual-l10n=ja` to build the Japanese manual localization. Defaults to none.
> [3.2] meson: Introduce option to control which manual l10n to build

- doc/manual/meson.build
Previously, all generated html pages were interspersed with other docs. This allows for a cleaner separation.
> [2.4] meson: Install htmldocs into htmldocs subdir

- config/meson.build
- meson_options.txt
Introducing boolean meson build option `-Dwith-ldsoconf` ... when true, a /etc/ld.so.conf.d/libatalk.conf file is created with the custom run-time linker search path. When false, this file is not created. Default is true.
> [2.4] meson: Ability to control the run-time linker path config file

- config/meson.build
- meson_options.txt
Introducing boolean meson build option `-Dwith-ldsoconf` ... when true, a /etc/ld.so.conf.d/libatalk.conf file is created with the custom run-time linker search path. When false, this file is not created. Default is true.
> [3.2] meson: Ability to control the run-time linker path config file

- config/meson.build
- meson_options.txt
Introducing boolean meson build option `-Dwith-ldsoconf` ... when true, a /etc/ld.so.conf.d/libatalk.conf file is created with the custom run-time linker search path. When false, this file is not created. Default is true.
> meson: Ability to control the run-time linker path config file

- etc/psf/meson.build
- include/atalk/meson.build
- sys/netatalk/meson.build
Three files that were overlooked when setting up the Meson build system, plus flipped logic for installing at.h
> [2.4] meson: Correctly install AppleTalk headers and etc2ps.sh

- include/atalk/meson.build
Two files that were left out of the meson build when first set up.
> meson: Install two AppleTalk headers

- libatalk/meson.build
Should fix the issue of ldconfig not being run as an install hook on Debian Bookworm.
> meson: Allow ldconfig to run unprivileged during setup

- distrib/initscripts/meson.build
- meson_options.txt
Backporting the with-init-dir meson option from 3.2
> [2.4] meson: Introduce a with-init-dir option

- config/meson.build
- libatalk/meson.build
Should fix the issue of ldconfig not being run as an install hook on Debian Bookworm.
> [3.2] meson: Allow ldconfig to run unprivileged during setup

- libatalk/meson.build
Should fix the issue of ldconfig not being run as an install hook on Debian Bookworm.
> [2.4] meson: Allow ldconfig to run unprivileged during setup

- doc/manpages/man5/afp.conf.5.xml
- etc/afpd/volume.c
- include/atalk/volume.h
- libatalk/util/netatalk_conf.c
Adds back the limit volume size and ProDOS options from Netatalk 2.x. Update man page. Fixes #1332
> Add Back Legacy Options

- contrib/shell_utils/docker-entrypoint.sh
Avoiding a corner case fail state when a residual lock file prevents netatalk from starting up.
> docker: Add entry script step to clean up any residual lock file

- contrib/shell_utils/docker-entrypoint.sh
Avoiding a corner case fail state when a residual lock file prevents netatalk from starting up.
> [3.2] docker: Add entry script step to clean up any residual lock file

- .gitignore
- DOCKER.md
- Dockerfile
- contrib/shell_utils/docker-entrypoint.sh
- docker-compose.yml
Ship a sample docker-compose.yml that was previously in the Docker readme. Add a warning to entry script that warns when using the default password.
> Docker: Ship a docker-compose.yml sample file

- contrib/shell_utils/docker-entrypoint.sh
Bail out when these two env variables are not set.
> [3.2] Docker: Check for AFP_USER and AFP_PASS when launching container

- include/atalk/paths.h
- meson.build
- meson_options.txt
Use with-lockfile-path to set a lockfile path that is not defined in paths.h
This leverages the special `-D_PATH_LOCKDIR` compiler flag that is only in 2.x (refactored away in 3.x and later)
> [2.4] meson: Introduce a with-lockfile-path option

- NEWS
- meson_options.txt
Changing the Meson config defaults for these two flags.
> [3.2] meson: Enable rpath and disable ldsoconf by default

- meson_options.txt
Changing the Meson config defaults for these two flags.
> [2.4] meson: Enable rpath and disable ldsoconf by default

- meson_options.txt
Changing the Meson config defaults for these two flags.
> meson: Enable rpath and disable ldsoconf by default

- bin/afppasswd/afppasswd.c
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_dhx_passwd.c
- etc/uams/uams_pgp.c
- etc/uams/uams_randnum.c
Fixes for compiler errors when building against a shared WolfSSL 5.7.2 library
> [2.4] Enable building with WolfSSL 5.7.2

- doc/manpages/man5/afp.conf.5.xml
- etc/afpd/afp_asp.c
- etc/afpd/afp_config.c
- etc/afpd/afp_config.h
- etc/afpd/afp_dsi.c
- etc/afpd/afp_options.c
- etc/afpd/auth.c
- etc/afpd/desktop.c
- etc/afpd/file.c
- etc/afpd/fork.c
- etc/afpd/fork.h
- etc/afpd/main.c
- etc/afpd/meson.build
- etc/afpd/messages.c
- etc/afpd/ofork.c
- etc/afpd/status.c
- etc/afpd/status.h
- etc/afpd/uam.c
- etc/afpd/volume.c
- include/atalk/globals.h
- include/atalk/uam.h
- include/atalk/util.h
- libatalk/adouble/ad_conv.c
- libatalk/asp/asp_getsess.c
- libatalk/util/logger.c
- libatalk/util/netatalk_conf.c
- libatalk/util/socket.c
- test/afpd/test.c
Fixes #1333 This pull request adds back support for Apple Session Protocol in afpd. This is very much a work in progress, but is  fully functional. Some legacy options like `authprintdir` and `ddpaddr` have not been enabled yet. To enable, add `appletalk = yes` under the `[global]` section of your `afp.conf`
> Add AppleTalk support back into afpd

- meson.build
Remove superfluous rpath linker arguments
> [3.2] meson: Do not define rpath with a linker argument

- meson.build
Remove superfluous rpath linker arguments
> [2.4] meson: Do not define rpath with a linker argument

- doc/manpages/man5/afp.conf.5.xml
- libatalk/util/netatalk_conf.c
Allow user to configure DDP address the server listens on by default if they have multiple interfaces running AppleTalk. Addresses part of #1442. Tested in multi-interface configuration and confirmed working.
> Add back "ddp address" option.

- DOCKER.md
- Dockerfile
- contrib/shell_utils/docker-entrypoint.sh
- docker-compose.yml
Adapt the Docker container to build and launch AppleTalk services.
> docker: Build and start AppleTalk services

- .github/workflows/build.yml
- distrib/initscripts/meson.build
The old way of doing this is triggering warning messages in an up to date Solaris 11 system.
Sleeps have been added to the CI workflow because it takes a moment for manifest-import to restart.
> [3.2] Update the Solaris manifest import command per Oracle docs

- .github/workflows/build.yml
Updating to the newly released v1.0.6 of the solaris vm runner
> [3.2] GitHub CI: Enable Solaris job and use latest image

- etc/uams/uams_dhx_pam.c
- etc/uams/uams_dhx_passwd.c
Fixes: when Mb (the server's "public" key part in the Diffie-Hellman exchange) or K (the "private" key) are shorter than KEYSIZE, the UAM code does not verify that they are aligned correctly to the memory regions they're being placed in.
> [3.2] uams: Fix DHCAST128 key alignment problem.

- etc/uams/uams_dhx_pam.c
- etc/uams/uams_dhx_passwd.c
Fixes: when Mb (the server's "public" key part in the Diffie-Hellman exchange) or K (the "private" key) are shorter than KEYSIZE, the UAM code does not verify that they are aligned correctly to the memory regions they're being placed in.
> uams: Fix DHCAST128 key alignment problem.

- doc/manpages/man5/afp.conf.5.xml
- etc/afpd/afp_config.c
- etc/afpd/main.c
- etc/afpd/status.c
- include/atalk/globals.h
- libatalk/util/netatalk_conf.c
Adds new option called "ddp zone" to allow a user to register the server in an AppleTalk zone other then the default zone of an interface. Fixes #1462.
> Add configuration option for AppleTalk Zone.

- etc/afpd/uam.c
Attempts to connect with the "Cleartxt" UAM over an AppleTalk connection were crashing afpd.
> Fix crash in uam.c when connecting via ASP

- DOCKER.md
- contrib/shell_utils/docker-entrypoint.sh
- docker-compose.yml
The AFP users are now added to their own groups as well as AFP_GROUP, for consistency.
The shared dirs are owned by root:AFP_GROUP
Also adds a second AFP user controlled with AFP_USER2/AFP_PASS2
Clean up atalkd and papd lockfiles
> docker: Make AFP_GROUP mandatory, refactor group assignments

- doc/manpages/man5/afp.conf.5.xml
These substitutions don't result in consistent results cross platform. The others were removed some time ago.
> [3.2] docs: Remove straggler path substitution in afp.conf

- DOCKER.md
- contrib/shell_utils/docker-entrypoint.sh
Rather than hard coding the secondary shared volume as Time Machine, allow the user to use it as a regular volume.
This is required for afptest.
> docker: The ability to customize the secondary shared volume

- bin/afppasswd/afppasswd.c
- bin/afppasswd/meson.build
- etc/uams/meson.build
- etc/uams/uams_randnum.c
Switches the RandNum UAM and afppasswd utility from using WolfSSL+Nettle to libgcrypt for DES encryption functions.
Adopted from : https://sourceforge.net/p/netatalk/feature-requests/60/
> Switch Randnum UAM to use libgcrypt

- include/wolfssl/openssl/evp.h
- include/wolfssl/wolfcrypt/cryptocb.h
- meson_config.h
We don't use AES crypto in the first place. It was just a matter of finding the right combination of configuration flags.
> wolfssl: Disable AES crypto to avoid symbol conflict with Nettle

- .github/workflows/build.yml
- meson.build
The code snippet used to detect a working libwrap was incorrect.
> meson: Use a valid code snippet for the TCP Wrappers check

- .github/workflows/build.yml
- meson.build
The code snippet used to detect a working libwrap was incorrect.
> [3.2] meson: Use a valid code snippet for the TCP Wrappers check

- .github/workflows/build.yml
- meson.build
The code snippet used to detect a working libwrap was incorrect.
> [2.4] meson: Use a valid code snippet for the TCP Wrappers check

- .github/workflows/build.yml
- INSTALL.md
- doc/ja/manual/install.xml
- doc/manual/install.xml
- meson.build
Some distributions package the cracklib library and the cracklib dictionary separately. Both are required to build netatalk with cracklib support. This change is to indicate which one is missing in the setup log.
> meson: Throw missing cracklib dictionary warning separately

- .github/workflows/build.yml
- meson.build
Some distributions package the cracklib library and the cracklib dictionary separately. Both are required to build netatalk with cracklib support. This change is to indicate which one is missing in the setup log.
> [3.2] meson: Throw missing cracklib dictionary warning separately

- .github/workflows/build.yml
- meson.build
Some distributions package the cracklib library and the cracklib dictionary separately. Both are required to build netatalk with cracklib support. This change is to indicate which one is missing in the setup log.
> [2.4] meson: Throw missing cracklib dictionary warning separately

- meson.build
Inject spaces between the two EA types, to synchronize the output of afpd -V build by Meson and Autotools.
> meson: Format afpd help text output to match autotools

- meson.build
Inject spaces between the two EA types, to synchronize the output of afpd -V build by Meson and Autotools.
> [2.4] meson: Format afpd help text output to match autotools

- .github/workflows/build.yml
Bumping all images except Solaris which I keep at 1.0.7 because the runtime balloons by 3min in 1.0.9
> GitHub CI: Bump vmactions image versions

- .github/workflows/build.yml
Bumping all images except Solaris and OmniOS which I keep at 1.0.7 and 1.0.6 respectively, because the runtime balloons by several minutes in the latest images.
> [3.2] GitHub CI: Bump vmactions image versions

- .github/workflows/build.yml
Bumping all images except Solaris and OmniOS which I keep at 1.0.7 and 1.0.6 respectively, because the runtime balloons by several minutes in the latest images.
> [2.4] GitHub CI: Bump vmactions image versions

- etc/cnid_dbd/main.c
Addresses one rpmlint bug reported in https://github.com/Netatalk/netatalk/issues/1308
> cnid_dbd: Run setgroups() before changing user

- meson_options.txt
Debugging was enabled by default in `meson_options.txt` in 3.x branch causing tickles to not be sent out. Fixes #1514.
> [3.x] Fix tickle handler

- meson_options.txt
Debugging was enabled by default in `meson_options.txt` in 3.x branch causing tickles to not be sent out. Fixes #1514.
> Fix tickle handler

- Dockerfile
Removing an unused dependent library.
> [3.2] docker: We disable afpstats so dbus-glib is superfluous

- etc/cnid_dbd/db_param.c
Security vulnerability flagged by Sonarcloud and picked up by GitHub. 
https://github.com/Netatalk/netatalk/security/code-scanning/2
> cnid_dbd: Set explicit max length of db_params to prevent buffer overflow

- etc/cnid_dbd/db_param.c
Security vulnerability flagged by Sonarcloud and picked up by GitHub. 
https://github.com/Netatalk/netatalk/security/code-scanning/2
> [2.4] cnid_dbd: Set explicit max length of db_params to prevent buffer overflow

- etc/cnid_dbd/db_param.c
Security vulnerability flagged by Sonarcloud and picked up by GitHub. 
https://github.com/Netatalk/netatalk/security/code-scanning/2
> [3.2] cnid_dbd: Set explicit max length of db_params to prevent buffer overflow

- doc/manual/install.xml
- etc/uams/meson.build
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_dhx_passwd.c
- meson.build
- meson_config.h
Switches the DHCAST128 UAM from WolfSSL+Nettle to libgcrypt for CAST encryption functions.
> Switch DHCAST128 UAM to use libgcrypt

- etc/afpd/auth.c
Addresses regression introduced with #1517.
> Fix sighandler crash when using AppleTalk

- etc/uams/uams_passwd.c
ibuflen should be '8' after stripping the username (and optional one byte pad) and match PASSWDLEN
> uams: Correct shadow password length check for ClearTxt

- etc/uams/uams_passwd.c
ibuflen should be '8' after stripping the username (and optional one byte pad) and match PASSWDLEN
> [3.2] uams: Correct shadow password length check for ClearTxt

- etc/uams/uams_passwd.c
ibuflen should be '8' after stripping the username (and optional one byte pad) and match PASSWDLEN
> [2.4] uams: Correct shadow password length check for ClearTxt

- distrib/initscripts/systemd.netatalk.service.in
Allow for loading atalkd before starting the AFP server, like 2.x did.
> Update systemd.netatalk.service.in to support atalkd

- etc/uams/uams_dhx_pam.c
- etc/uams/uams_dhx_passwd.c
- etc/uams/uams_randnum.c
Fix for libgcrypt libraries that weren't consistently being initialized depending on how a user logged in.
> Cleanup libgcrypt initialization

- .github/workflows/build.yml
- macros/netatalk.m4
- meson.build
The default location for the dbus config files is datadir rather than sysconfdir as per https://dbus.freedesktop.org/doc/dbus-daemon.1.html
> [3.2] Install netatalk-dbus.conf into datadir by default

- .github/workflows/build.yml
- meson.build
The default location for the dbus config files is datadir rather than sysconfdir as per https://dbus.freedesktop.org/doc/dbus-daemon.1.html
> Install netatalk-dbus.conf into datadir by default

- .github/workflows/build.yml
- meson.build
Use a more specific pattern to match the wolfssl capability definitions. This avoids a false positive with the wolfssl headers that Arch Linux distributes.
> [3.2] meson: Capture only defined capability flags in wolfssl check

- .github/workflows/build.yml
- meson.build
Use a more specific pattern to match the wolfssl capability definitions. This avoids a false positive with the wolfssl headers that Arch Linux distributes.
> [2.4] meson: Capture only defined capability flags in wolfssl check

- distrib/initscripts/debian.a2boot.in
- distrib/initscripts/debian.atalkd.in
- distrib/initscripts/debian.netatalk.in
- distrib/initscripts/debian.papd.in
- distrib/initscripts/debian.timelord.in
- distrib/initscripts/openrc.atalkd.in
- distrib/initscripts/openrc.netatalk.in
Touching up the Debian sysv and OpenRC init script handling of atalkd startup and shutdown.
> initscripts: add atalkd dependencies and remove NBP unregister steps

- etc/uams/uams_dhx2_pam.c
- etc/uams/uams_dhx2_passwd.c
- etc/uams/uams_dhx_pam.c
- etc/uams/uams_dhx_passwd.c
- etc/uams/uams_randnum.c
- include/atalk/uam.h
This removes the overzealous check for the exact libgcrypt version that netatalk was linked with.
At the same time, add scaffolding for future libgcrypt minimum version validation.
> uams: Disable incorrect libgcrypt library version validation
