NEWS, bin/afppasswd/afppasswd.c, doc/DEVELOPER, etc/uams/uams_randnum.c
not use des_old.h
merged from OpenBSD
http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/net/netatalk3/patches/
=> LibreSSL support

distrib/initscripts/Makefile.am, distrib/initscripts/rc.a2boot.netbsd.tmpl, distrib/initscripts/rc.atalk.bsd.tmpl, distrib/initscripts/rc.atalk.debian.tmpl, distrib/initscripts/rc.atalk.gentoo.tmpl, distrib/initscripts/rc.atalk.suse-sysv.tmpl, distrib/initscripts/rc.atalk.sysv.tmpl, distrib/initscripts/rc.atalk.tru64.tmpl
Adapted from patch by NJRoadfan: https://github.com/rdmark/Netatalk/pull/1
=> [2.2] Update init script templates to start/stop a2boot daemon.

contrib/shell_utils/asip-status.pl.in, man/man1/asip-status.pl.1.tmpl
* IPv6 support. New option [-4 | -6]
* Show GSS-UAM SPNEGO blob
* Improved layout of output
* Updated man page
Based on patches by hat001 and slowfranklin
=> [2.2] Backport improvements to the asip-status.pl script

etc/afpd/quota.c
Forward-port of https://github.com/Netatalk/Netatalk/pull/190
=> Provide MNTTYPE_NFS on OmniOS / Solaris

contrib/shell_utils/apple_dump.in, doc/manual/man/man1/apple_dump.1.xml, man/man1/apple_dump.1
Backport from 3.1
Patches by hat001
=> [2.2] EA support in apple_dump script

libatalk/util/unix.c
Change log level to error, from debug, for `realpath() cannot resolve path` error
Requested in https://sourceforge.net/p/netatalk/bugs/666/
=> Change log level for realpath() error

etc/afpd/spotlight.c, etc/spotlight/sparql_parser.c, etc/spotlight/sparql_parser.y, include/atalk/spotlight.h, macros/netatalk.m4
Forward port of https://github.com/Netatalk/netatalk/pull/202
=> add support for tracker3

NEWS, etc/spotlight/sparql_parser.y
Author: Andrew Stormont <andyjstormont@gmail.com>
Signed off by: Daniel Markstedt <markstedt@gmail.com>
Bug: https://github.com/Netatalk/Netatalk/issues/56
=> Fix afpd segfault in Spotlight SPARQL parser

configure.ac, etc/afpd/Makefile.am, etc/afpd/spotlight.c, etc/afpd/spotlight_marshalling.c, etc/spotlight/Makefile.am, etc/spotlight/sparql_parser.y, etc/spotlight/spotlight_rawquery_lexer.l, include/atalk/dalloc.h, libatalk/cnid/tdb/cnid_tdb.h, libatalk/talloc/Makefile.am, libatalk/talloc/dalloc.c, macros/netatalk.m4, macros/summary.m4
Description: Support linking with system shared libraries
Author: Jonas Smedegaard <dr@jones.dk>
Signed Off By: Daniel Markstedt <markstedt@gmail.com>
Downstream Debian patch https://sources.debian.org/src/netatalk/3.1.14~ds-1/debian/patches/101_shared_libs.patch/
=> Support linking with system shared libraries

bin/misc/uuidtest.c, etc/afpd/afp_dsi.c, etc/afpd/fce_api.c, etc/afpd/fce_api_internal.h, etc/afpd/fce_util.c, etc/afpd/status.c, etc/netatalk/afp_mdns.c, etc/uams/uams_gss.c, include/atalk/cnid.h
Deprecated in all versions of C
=> Fix all function declarations without a prototype

doc/manpages/man1/afpstats.1.xml, doc/manpages/man1/apple_dump.1.xml, doc/manpages/man5/afp.conf.5.xml, doc/manpages/man5/extmap.conf.5.xml, man/man1/ad.1.in, man/man1/afpldaptest.1.in, man/man1/afppasswd.1.in, man/man1/afpstats.1.in, man/man1/apple_dump.1.in, man/man1/asip-status.pl.1.in, man/man1/dbd.1.in, man/man1/macusers.1.in, man/man1/megatron.1.in, man/man1/netatalk-config.1.in, man/man1/uniconv.1.in, man/man5/afp.conf.5.in, man/man5/afp_signature.conf.5.in, man/man5/afp_voluuid.conf.5.in, man/man5/extmap.conf.5.in, man/man8/afpd.8.in, man/man8/cnid_dbd.8.in, man/man8/cnid_metad.8.in, man/man8/netatalk.8.in
Using docbook-xsl 1.79.1
https://sourceforge.net/projects/docbook/files/docbook-xsl/1.79.1/
=> Regenerate man pages from xml sources, while fixing minor syntax issues

include/atalk/dictionary.h, include/atalk/iniparser.h, libatalk/iniparser/dictionary.c, libatalk/iniparser/iniparser.c
This PR fixes errors made when creating PR #271. Please let me know if you would like to revert commit b568955 and have me prepare a fresh full PR or are happy just to apply this PR. I have compiled this fix in an Archlinux VM and all is well. Compiles fine in my fork, afp.conf is read correctly and shared volumes mount successfully.
=> Fix errors made in merged PR #271 (commit b568955)

etc/afpd/filedir.c, libatalk/util/unix.c
Drops the log level to warning for three very chatty non-fatal errors.
=> Drop log level to warning for non-lethal errors

libatalk/util/netatalk_conf.c
Patch by Jason in https://sourceforge.net/p/netatalk/bugs/449/
=> libatalk: Make valid users work in the Homes section

.github/workflows/build.yml
This introduces a separate job to the github workflow that builds the code and runs the integration test suite in test/
=> Introducing a github workflow job to run integration tests

.github/workflows/build.yml
This introduces a separate job to the github workflow that builds the code and runs the integration test suite in test/
=> [2.2] Introduce a job to run tests in the github workflow

etc/afpd/directory.c, libatalk/bstring/bstrlib.c
Forward port of https://github.com/Netatalk/netatalk/pull/139
=> Remove bitrotted code

bootstrap
=> [2.2] bootstrap: Add checks for required packages

macros/db3-check.m4
Description: Fix detection of Berkeley DB installed in multiarch location
Author: Helmut Grohne <helmut@subdivi.de>
=> Fix detection of Berkeley DB installed in multiarch location

distrib/initscripts/rc.debian.tmpl
Description: Source init-functions in Debian init.d-script
Author: Adrian Knoth <adi@drcomp.erfurt.thur.de>
=> Source init-functions in Debian init.d-script

libatalk/adouble/ad_open.c
Remove special handling of COMMENT ad entries, since empty entries are now allowed as of the code changes in https://github.com/Netatalk/netatalk/pull/178
=> libatalk: Remove special case for COMMENT metadata validation

macros/netatalk.m4
Make distcheck now passes on aarch64 FreeBSD
=> Dtrace support in netatalk fails to compile on aarch64 FreeBSD

etc/afpd/desktop.c
* Check that source path is a dir before moving .AppleDesktop
* Use C APIs for renaming files rather than a system call to mv
* Call become_root() before the first lstat() call
Signed-off-by: Daniel Markstedt <daniel@mindani.net>
=> CVE-2022-22995: Harden create_appledesktop_folder()

NEWS
Let's keep the NEWS up to date in main (I forgot when tagging the last release)
=> NEWS for 3.1.18 and 3.1.17

etc/afpd/afprun.c
=> add return 0 into become_user_permanently()

configure.ac, doc/manual/man/man5/AppleVolumes.default.5.xml, etc/afpd/afp_options.c, etc/afpd/file.c, etc/afpd/filedir.c, etc/afpd/unix.c, etc/afpd/volume.c, include/atalk/unix.h, include/atalk/volume.h, libatalk/util/volinfo.c, libatalk/vfs/unix.c, libatalk/vfs/vfs.c, macros/summary.m4
This removes the underlying sticky dir code as well. From my reading of the code this shouldn't impact anything else, but there could be breakages somewhere potentially.
=> [2.3] Remove experimental Dropbox Kludge feature

README.md
Addressing a very commonly asked question / misunderstanding.
=> Update README.md with a blurb about AppleTalk

.github/workflows/build.yml
- Add Fedora VM to GitHub workflow
- Optimize VM's for speed
=> Add Fedora VM workflow

doc/manual/netatalk.html
I created a new landing page for documentation on the website.
=> manual: Link to docs landing page

.github/workflows/build.yml, doc/manual/Makefile.am
Validate that the xsltproc docbook process works.
=> CI workflow: generate manpages from XML

bin/pap/pap.c, bin/pap/papstatus.c
Based on code from kakwa - https://github.com/kakwa/image-writer/tree/master/bin/pap
=> [2.3] pap,papstatus:  changes to allow Imagewriters to print, and nicer status messages

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Templates to help guide users to file more thorough issue tickets
=> Create GitHub issue templates

.github/workflows/build.yml, distrib/initscripts/meson.build
Fixes syntax errors in initscripts meson.build leading to failure of script installation.
=> Fix errors in initscripts meson.build

configure.ac
Backport of https://github.com/Netatalk/netatalk/issues/746 to v2.3 branch
=> [2.3] Detect system docbook stylesheets at configure time

README.md
Tweaking the README after feedback about the ease of finding 2.x releases.
=> README.md: Improve AppleTalk and Benchmark paragraphs

README.md, doc/manual/install.xml
More fixes following feedback in https://github.com/Netatalk/netatalk/issues/739
I also brought in some improvements to README.md from the main branch
=> [2.4] docs: Update git instructions and README.md

doc/manual/install.xml
Forward-port of the earlier improvement to the v2 branch
=> docs: Update the git instructions in the Install chapter

bin/ad/meson.build, bin/adv1tov2/meson.build, bin/aecho/meson.build, bin/afppasswd/meson.build, bin/getzones/meson.build, bin/megatron/meson.build, bin/nbp/meson.build, bin/pap/meson.build, bin/psorder/meson.build, bin/uniconv/meson.build, etc/afpd/meson.build, etc/atalkd/meson.build, etc/cnid_dbd/meson.build, etc/papd/meson.build, etc/psf/meson.build, meson.build
=> [2.4] meson: Fix executables not linking correctly with libatalk shared library 

distrib/initscripts/io.netatalk.daemon.plist.tmpl
=> Remove extraneous line in launchd plist template

.github/workflows/build.yml, distrib/initscripts/io.netatalk.daemon.plist.tmpl
Same change that was made in main
=> [2.4] Remove superfluous env variable from io.netatalk.daemon.plist.tmpl

configure.ac, doc/Makefile.am, doc/ja/Makefile.am, doc/ja/manpages/Makefile.am, doc/ja/manpages/man1/Makefile.am, doc/ja/manpages/man5/Makefile.am, doc/ja/manpages/man8/Makefile.am, doc/ja/manual/.gitignore, doc/ja/manual/Makefile.am
Turned out to be easy to do with autotools, so I propose pulling this in for completeness sake.
=> docs: Build Japanese manual with the autotools build system

.github/workflows/build.yml
Also, use libcups package instead of remote tarball
=> [2.4] Bump netbsd vmactions version to 1.0.7

doc/manual/Makefile.am, doc/manual/meson.build
The build system rules had fallen off the main PR somehow...
=> docs: Build system rules for compile.xml manual

.github/workflows/build.yml, macros/netatalk.m4
Minimal feature set Alpine build.
Also contains a hotfix for https://github.com/Netatalk/netatalk/issues/862 to enable the autotools build to succeed.
=> GitHub CI job with Alpine Linux

.github/workflows/build.yml
The openSUSE Tumbleweed docker image got updated this morning. Adjustment of packages needed.
=> Fix openSUSE CI job

meson.build
Extremely minor, but it's kind of been bothering me...
=> meson: Fix typos in spotlight configure messages

meson.build
Tiny capitalization thing that has been bothering me
=> UAMs in summary

Dockerfile
- The tracker-miner package is mandatory for spotlight indexing to launch.
- A few more explicit compile time disabled features
- Tighter user/group creation
- Refactoring to reduce total number of stages
=> docker: add missing tracker-miner package; refactoring

config/meson.build, meson.build
All .conf files are now installed in their correct location (/etc/netatalk)
=> [2.4] meson: Fix conf file installation

bin/afppasswd/afppasswd.c
Turns out my initial go at this only worked for passwords of length = 8...
It is required to null out the padding for the rest of the password scrambling logic to work.
=> [2.4] afppasswd: Correct setting of <8 length passwords with -w option

Dockerfile, README.md, contrib/shell_utils/docker-entrypoint.sh
Use Alpine Linux base image for Docker, and build with Meson for SPEED.
=> [2.4] docker: Alpine based container + Meson build

bin/afppasswd/afppasswd.c
- create a single-use variable for cracklib check, to avoid a null pointer reference later
- better error handling
- indentation
=> afppasswd: Prevent null pointer reference

contrib/shell_utils/docker-entrypoint.sh
We can restore DHX when WolfSSL gets integrated
=> docker: Use RandNum UAM instead of DHX

etc/uams/meson.build
=> meson: Fix duplicate dependency from commit 0f9cae5

.github/workflows/build.yml
- Add Alpine and openSUSE jobs
- Sort all jobs alphabetically
- Bump OS versions to the latest stable across the board
- Run netatalk after installing where feasible
=> [2.4] GitHub CI: Add Alpine and openSUSE; run netatalk after installing

.github/workflows/build.yml
This gets us to parity between 2.x and 3.x CI configurations.
=> [2.4] GitHub CI: More OSes: Arch, DragonflyBSD, FreeBSD, OpenBSD, OmniOS

.github/workflows/build.yml
=> [2.4] GitHub CI: Build with libtirpc on Alpine

etc/afpd/meson.build, libatalk/compat/meson.build, meson.build, meson_options.txt, test/afpd/meson.build
This changeset:
Adds further refinements to quota macro
Adds user options to disable cracklib and GSSAPI support
Automates Berkeley DB library detection on macOS (via Homebrew or MacPorts)
=> meson: Further refinements to meson build system

.github/workflows/build.yml
...with a more descriptive code comment
=> GitHub CI: Restore the fetch-depth rule

README.md
A few factual corrections and other improvements.
=> [2.4] Freshen up README.md

meson.build
These were overlooked in a recent PR
=> meson: netatalk version not propagated properly

doc/ja/manual/meson.build, doc/manual/meson.build
An oversight from when the meson build scripts were created
=> meson: Generate afppasswd manual html page

include/atalk/bstrlib.h, libatalk/bstring/bstrlib.c
https://github.com/websnarf/bstrlib/releases/tag/v1.0.0
=> Bump to version 1.0.0 of bstrlib

meson.build
- Group into options (choice in a mandatory category) and features (optional functionality)
- Print the library type to build
=> meson: Rearrange the setup summary for brevity and clarity

etc/uams/meson.build, libatalk/meson.build
This change respects the `-Ddefault_library` meson option and enables or disables the building or shared or static libraries.
=> [2.4] meson: Allow choosing shared or static libraries to build 

.gitignore, docker-compose.yml
Ship a basic sample file without username or password set.
=> [3.2] Docker: Ship a docker-compose.yml sample file

.gitignore, docker-compose.yml
Ship a basic sample file without username or password set.
=> [2.4] Docker: Ship a docker-compose.yml sample file

bin/afppasswd/afppasswd.c, etc/uams/uams_dhx_pam.c, etc/uams/uams_dhx_passwd.c, etc/uams/uams_pgp.c, etc/uams/uams_randnum.c
same pr as #1422, but targets branch-netatalk-3-2 instead of main.
=> [3.2] include wolfssl/settings.h

bin/afppasswd/afppasswd.c, etc/uams/uams_randnum.c
=> define DES_KEY_SZ if its not defined

bin/aecho/meson.build, bin/getzones/meson.build, bin/nbp/meson.build, bin/pap/meson.build, contrib/a2boot/meson.build, contrib/timelord/meson.build, meson.build
Remove superfluous rpath linker arguments
=> meson: Do not define rpath with a linker argument

.github/workflows/build.yml, distrib/initscripts/meson.build
Updating to the newly released v1.0.6 of the solaris vm runner.
Also, updates the Solaris init system manifest import command.
=> Enable Solaris CI job, use latest vmactions image, update manifest import command

README.md, doc/ja/manpages/man1/netatalk-config.1.xml, doc/manpages/man1/netatalk-config.1.xml, doc/manpages/man5/afp.conf.5.xml, doc/manual/appletalk.xml, doc/manual/configuration.xml, doc/manual/install.xml, doc/manual/intro.xml, doc/manual/upgrade.xml
Touch up the documentation and run the XML through XMLmind for automatic formatting.
=> docs: Update with manual 4.x capabilities and dependencies

etc/uams/uams_dhx_pam.c, etc/uams/uams_dhx_passwd.c
Fixes: when Mb (the server's "public" key part in the Diffie-Hellman exchange) or K (the "private" key) are shorter than KEYSIZE, the UAM code does not verify that they are aligned correctly to the memory regions they're being placed in.
=> [2.4] uams: Fix DHCAST128 key alignment problem.

include/wolfssl/openssl/opensslv.h, libatalk/ssl/src/bio.c, libatalk/ssl/src/ssl.c
Port of upstream patch by Daniel Pouzzner
=> wolfssl: OpenSSL coexistence tweaks

include/wolfssl/openssl/opensslv.h, libatalk/ssl/src/bio.c, libatalk/ssl/src/ssl.c
Port of upstream patch by Daniel Pouzzner
=> [2.4] wolfssl: OpenSSL coexistence tweaks

include/wolfssl/openssl/opensslv.h, libatalk/ssl/src/bio.c, libatalk/ssl/src/ssl.c
Port of upstream patch by Daniel Pouzzner
=> [3.2] wolfssl: OpenSSL coexistence tweaks

etc/uams/uams_randnum.c
Users can now change their password successfully.
=> Fix RandNum UAM password change

contrib/macipgw/tunnel_linux.c
Merge `tunnel_linux.c` from https://github.com/jasonking3/macipgw
Minor changes to match local coding style and remove dead code.
=> macipgw: Merge Jason King's rewrite of the Linux tunnel

NEWS
Changelog for 4.0.0 stable release.
=> NEWS for 4.0.0 release

.github/workflows/build.yml
Attempt to use wildcard on .md files
=> GitHub CI: Update ignore rules

etc/papd/lp.c, etc/papd/printcap.c
References:
https://krbdev.mit.edu/rt/m/ticket/history?id=4561
https://spdx.org/licenses/BSD-4-Clause-UC.html
ftp://ftp.cs.berkeley.edu/pub/4bsd/README.Impt.License.Change
=> Update license grant to reflect the retroactive rescission of U.C Berkeley clause 3

etc/afpd/afp_asp.c, etc/afpd/afp_config.c, etc/afpd/fork.c, etc/afpd/main.c
My opinionated editor is also cleaning up trailing whitespace...
=> Explicitly import headers to appease gcc on Debian Unstable

Dockerfile
For those not familiar, Docker multistage builds reduce the size of the final image and keep a cleaner separation between build artifacts vs. what actually needs to be deployed.  The general idea is to build and then copy the artifacts into a fresh base.
In this case, it looks like this cuts the image size from ~300MB to ~120MB.
I'll note that I only did basic testing (seems fine), but if something's wrong, I would guess it's a missing dependency that wasn't declared explicitly before I changed the Dockerfile.
=> docker: use multistage build to isolate build from final image

doc/ja/manpages/man5/afp.conf.5.xml, doc/ja/manual/configuration.xml, doc/ja/manual/install.xml, doc/ja/manual/upgrade.xml, doc/manpages/man5/afp.conf.5.xml, doc/manual/configuration.xml, doc/manual/install.xml, doc/manual/upgrade.xml
XML autoformatted with XMLmind
=> docs: Touch up Tracker documentation and translate to Japanese

etc/papd/lp.c, etc/papd/lp.h, meson.build, meson_config.h
Fall back to internal implementation if not found.
=> meson: Detect rresvport() function in system libraries

test/testsuite/logintest.c
Take parts of `main()` and move it into four new test cases with setup, teardown, and results reporting.
=> testsuite: Break down login testsuite into atomic tests

.github/workflows/build.yml, .github/workflows/containers.yml
Ignore more READMEs and Dockerfiles.
=> GitHub CI: More fine grained file ignores for the workflows

CONTRIBUTORS, contrib/macipgw/macip.c, contrib/macipgw/main.c, doc/ja/manpages/man8/macipgw.8.xml, doc/manpages/man8/macipgw.8.xml
Ports these two commits by Adam Seering:
- https://github.com/jasonking3/macipgw/commit/daa2620c6323ac0b563c5d16ef66f0e9a3749669
- https://github.com/jasonking3/macipgw/commit/5aacd8e498e4fdaa988c73bed295da9f9d28a54f
Redistributed under the GPL v2 with permission by the author. https://github.com/Netatalk/netatalk/issues/1204
=> macipgw: Unprivileged user feature and Linux arp fix

doc/ja/manual/meson.build, doc/manpages/man1/meson.build, doc/manpages/man5/meson.build, doc/manpages/man8/meson.build, doc/manual/meson.build, doc/meson.build
fixes #1753 
tested to work properly on el9 and f41
=> only build appletalk docs when enabled

doc/manual/netatalk.css
We added a CSS style in the homepage repo. This brings that change over.
=> docs: Sync css styles from homepage

.github/workflows/build.yml, config/meson.build, meson.build, meson_options.txt
Remove spurious hard coded defaults. Leverage the existence of dirs or dbus libs.
=> meson: Configure dbus paths and config files only if dbus exists

doc/ja/manual/install.xml, doc/manual/install.xml
Flesh out descriptions of Avahi, D-Bus and GLib dependencies.
=> docs: More accurate descriptions of optional dependencies in Install chapter

Dockerfile, Dockerfile.testsuite, contrib/shell_utils/docker-entrypoint.sh
Upgrade from Alpine 3.20 to 3.21
=> docker: Bump base image to Alpine 3.21

test/testsuite/lantest.c
Use thread safe `getpwuid_r()` to get current user in lantest
=> testsuite: Improve memory management in lantest

contrib/macipgw/main.c
config file is optional with this change.
Addresses https://github.com/Netatalk/netatalk/issues/1887
=> macipgw: Handle scenario when config file is missing

.github/workflows/build.yml
Latest vmrunner image upstream
=> GitHub CI: Bump to DragonFlyBSD vmactions runner 1.1.0

etc/atalkd/main.c, etc/papd/print_cups.c, etc/papd/print_cups.h, libatalk/adouble/ad_conv.c
Addressing a number of code quality issues raised by Sonarqube
=> Prevent illegal null pointer calls

libatalk/adouble/ad_conv.c, test/testsuite/afpcmd.c, test/testsuite/lantest.c, test/testsuite/speedtest.c
Addressing compiler warnings thrown when building in a Debian buildd environment.
=> Matching format specifiers in C strings

etc/uams/uams_dhx2_pam.c, etc/uams/uams_dhx_pam.c, etc/uams/uams_pam.c
Flagged by Sonarqube:
> You should call "pam_acct_mgmt" after calling "pam_authenticate" to check account validity
Also addresses the surrounding code smells: error handling for seteuid(), and global pointer pointing to local variable address.
=> uams: Check account validity after calling pam_authenticate()

etc/uams/uams_dhx2_pam.c
Straggler PAM account validation in DHX2
=> uams: Validate PAM account after root auth in DHX2 UAM

bin/ad/ad_mv.c, etc/cnid_dbd/cmd_dbd_scanvol.c, etc/papd/lp.c, test/testsuite/speedtest.c
Addresses a number of file access race conditions, as flagged by Sonarqube.
=> Avoid TOCTOU conditions

meson.build
Reduce repetition of include dir lists.
=> meson: Refactor root includes list

contrib/webmin_module/control.cgi, contrib/webmin_module/delete_atalk.cgi, contrib/webmin_module/delete_sections.cgi, contrib/webmin_module/edit_atalk.cgi, contrib/webmin_module/edit_global_section.cgi, contrib/webmin_module/edit_print.cgi, contrib/webmin_module/edit_vol_section.cgi, contrib/webmin_module/index.cgi, contrib/webmin_module/save_atalk.cgi, contrib/webmin_module/save_global_section.cgi, contrib/webmin_module/save_print.cgi, contrib/webmin_module/save_vol_section.cgi
Keep track of originating index tab when navigating the module.
=> webmin: Redirect the appropriate tab when returning from actions

libatalk/util/netatalk_conf.c
Free memory, and restore error handling removed before.
=> libatalk: Plug yet another potential memory leak

libatalk/vfs/ea_ad.c
The previous solution didn't work when replacing existing EA files
=> libatalk: Refactor vfs write_ea() to write directly without temp file

libatalk/vfs/ea_ad.c
The previous attempt at addressing the TOCTOU race condition in write_ea() didn't fully work. This is try two at refactoring.
=> libatalk: Refactor vfs write_ea() to avoid TOCTOU race condition (take 2)

DOCKER.md, contrib/shell_utils/docker-entrypoint.sh
A handful of new and updated options: modern and legacy icons, server and volume names, etc.
=> docker: New and improved env variable options

etc/cnid_dbd/cmd_dbd_scanvol.c
When handling .AppleDouble dirs in dbd, we access and chown dirs separately, opening up for TOCTOU file access race conditions. This refactors this one function to open file handlers instead.
=> cnid_dbd: Use file descriptors for managing access in scanvol check dir

etc/afpd/appl.c
In the appl module of afpd, when adding/copying/removing data in the desktop file we use pointer arithmetic to write to buffers without strict boundary checks. This changeset refactors these functions to use explicitly sized buffers instead for memory safety.
=> afpd: Use explicitly sized buffer for desktop file with appl data

etc/afpd/enumerate.c
- More precise check for buffer space that exactly matches what's being copied
- If reallocation fails, it restores sd_last to prevent partial/invalid data
- Removed the unused lenm variable to avoid confusion
=> afpd: In enumerate module, more precise check for buffer space

libatalk/util/ftw.c
The realloc() method leaves openings for unexpected outcomes in the source buffer. This manually allocate and deallocate the same memory for better control.
=> libatalk: In the ftw library, use manual memory allocation instead of realloc()

libatalk/util/ftw.c
- Added bounds checking to prevent integer overflow
- Implemented a maximum size limit for individual entries
- Made the boundary checks consistent
- Added safer arithmetic operations for size calculations
=> libatalk: Protect against very large entry sizes in ftw dirstream

etc/afpd/fork.c, libatalk/cnid/dbd/cnid_dbd.c, test/testsuite/T2_FPResolveID.c
Added error handling and initializations.
=> Address a last handful of accessing garbage values

CONTRIBUTORS.md, contrib/macusers/macusers.in, distrib/initscripts/freebsd.netatalk.in, etc/afpd/afp_util.c, etc/afpd/mangle.c
As requested, refresh the contact point for Joe.
=> Update email address for contributor Joe Clarke

contrib/webmin_module/edit_global_section.cgi
=> [webmin] Add RandNum UAM option to Global config.

meson.build
This gets us a unified look for UAMs / auth methods / CNID backends
=> meson: Standardize lists of features as bar separated lower-case words

doc/po/Configuration.md.ja.po, doc/po/Installation.md.ja.po, doc/po/Upgrading.md.ja.po, doc/po/ad.1.md.ja.po, doc/po/addump.1.md.ja.po, doc/po/afp.conf.5.md.ja.po, doc/po/afp_signature.conf.5.md.ja.po, doc/po/afp_voluuid.conf.5.md.ja.po, doc/po/afpd.8.md.ja.po, doc/po/afpldaptest.1.md.ja.po, doc/po/afppasswd.1.md.ja.po, doc/po/afpstats.1.md.ja.po, doc/po/asip-status.1.md.ja.po, doc/po/cnid_dbd.8.md.ja.po, doc/po/cnid_metad.8.md.ja.po, doc/po/dbd.1.md.ja.po, doc/po/extmap.conf.5.md.ja.po, doc/po/getzones.1.md.ja.po, doc/po/index.md.ja.po, doc/po/macusers.1.md.ja.po, doc/po/netatalk.8.md.ja.po
Clarify the people who touched these translations.
=> docs: Reflect accurate authorship of the Japanese localization

contrib/webmin_module/index.cgi, contrib/webmin_module/lang/en
The volume name can now be different from section name. Let's list bothin the webmin module index page.
=> webmin: Print volume name as well as section name in volumes list

contrib/webmin_module/edit_vol_section.cgi, contrib/webmin_module/index.cgi
This fixes a handful of scenario where the incorrect tab was returned to.
=> webmin: Consistently return to the correct index tab from other actions

doc/manual/_Sidebar.md, doc/po/_Sidebar.md.ja.po
Minor tweak to make the website manual more navigation friendly
=> docs: Join chapters and appendices in website manual sidebar

libatalk/bstring/LICENSE, libatalk/bstring/README.md
This adds the full text of Paul Hsieh's BSD 3-clause license as well as a README with excerpts from the original documentation
=> Create bstring README with redistribution notes and full credits

libatalk/cnid/mysql/cnid_mysql.c
Previously, you had to create the designated MySQL database manually; this code creates it if not found during a pre-connection check
=> libatalk: Create MySQL CNID database automatically if needed

contrib/shell_utils/codefmt.sh
Rather than making it mandatory to select one or the other, both astyle and muon are now ran, and will be skipped with a warning if either is missing rather than bailing out
We now allow for running without git as well, although no diff will be produced afterwards
=> Code formatting script runs both meson and C formatter by default

libatalk/unicode/make-casetable.pl, libatalk/unicode/make-precompose.h.pl
Tweak indentation and padding of the generated code, so that future regrenerations of these sources lead to compliant style
=> Ouput of Unicode generation script compliant with coding standards

etc/spotlight/sparql_parser.y
Ran the project astyle rules against the yacc code, and then some manual touch-up of overcorrection due to astyle not understanding yacc properly
Therefore we will not run continuous styling of this code
=> Reformat yacc code with astyle

doc/manpages/man1/dbd.1.md, doc/manpages/man8/netatalk.8.md
In the netatalk man page, describe the daemon structure in more detail
In the dbd man page, explain a few practical usage scenarios
=> docs: Flesh out netatalk and dbd man pages

contrib/bin_utils/afpstats.pl, contrib/webmin_module/edit_vol_section.cgi, contrib/webmin_module/save_vol_section.cgi
Bugfixes between v20250311 and v20250616 of perltidy leads to improved indentation and padding layout in a handful of files
=> Reformat Perl code with perltidy v20250616

.github/workflows/scorecard.yml
The OSSF Scorecard allows automated assessment of the project's security practices
https://github.com/ossf/scorecard
=> GitHub CI: Create OSSF Scorecard action

README.md
This merges and removes a few sections, moving the documentation info higher up while rephrasing other sections
=> Touch up and rearrange README.md

.github/workflows/code_analysis.yml, .github/workflows/containers.yml
The previous attempt didn't work when merged into a branch, so trying yet another approach
=> GitHub CI: Use yet another strategy for detecting dependabot PRs

COMPILATION.md, INSTALL.md, NEWS.md, doc/manpages/man5/afp.conf.5.md, doc/manual/Installation.md, doc/po/Installation.md.ja.po, doc/po/afp.conf.5.md.ja.po
Fixing a few typos and refreshing the compilation readme
Document the bstring dependency in the install readme and manual
=> Minor touch-up of documentation

NEWS.md
A few last-minute additions to the release
=> Touch up changelog for 4.3.0

.github/workflows/release.yml
This workflow will run when tags are pushed to remote, and will create a release with release notes
=> GitHub CI: Create a release workflow

.github/workflows/release.yml, DOCKER.md
Automate the process of building and publishing the container images for release versions to Docker Hub
Switch the entire release workflow over to manual dispatch
=> GitHub CI: Build and publish container images to Docker Hub

.github/workflows/release.yml
In addition to Docker Hub, publish release containers to GutHub Container Registry
This also adds support for the Webmin Module container
=> GitHub CI: Build and publish containers to ghcr.io

README.md
Remove a handful of vanity badges that are of less value to end users, and consolidate two sections into one
=> Cut down on badges on README.md

etc/afpd/uam.c
Since afpd isn't a threading application, there is no pressing need to use the reentrant-safe way to fetch the passwd entry in uam_getname()
The reverted solution had flaws that led to a critical failure when attempting to authenticate in a complex ActiveDirectory environment
=> [4.2] afpd: Revert to non-reentrant getpwnam() in the uam module
